<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/isa/v1/common.proto

namespace Sah\Isa\Api\V1\Meta;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x93\x09\x0A\x17api/isa/v1/common.proto\x12\x0Aapi.isa.v1\"\xFF\x01\x0A\x0EProblemDetails\x12\x12\x0A\x04type\x18\x01 \x01(\x09R\x04type\x12\x14\x0A\x05title\x18\x02 \x01(\x09R\x05title\x12\x16\x0A\x06status\x18\x03 \x01(\x05R\x06status\x12)\x0A\x04code\x18\x04 \x01(\x0E2\x15.api.isa.v1.ErrorCodeR\x04code\x12\x16\x0A\x06detail\x18\x05 \x01(\x09R\x06detail\x12\x1A\x0A\x08instance\x18\x06 \x01(\x09R\x08instance\x12\x1D\x0A\x0Arequest_id\x18\x07 \x01(\x09R\x09requestId\x12\x14\x0A\x05param\x18\x08 \x01(\x09R\x05param\x12\x17\x0A\x07doc_url\x18\x09 \x01(\x09R\x06docUrl*\xF3\x03\x0A\x09ErrorCode\x12\x1A\x0A\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1B\x0A\x17ERROR_CODE_UNAUTHORIZED\x10\x01\x12\x1C\x0A\x18ERROR_CODE_TOKEN_EXPIRED\x10\x02\x12\x1C\x0A\x18ERROR_CODE_INVALID_TOKEN\x10\x03\x12\x18\x0A\x14ERROR_CODE_FORBIDDEN\x10\x04\x12\x18\x0A\x14ERROR_CODE_NOT_FOUND\x10\x05\x12!\x0A\x1DERROR_CODE_METHOD_NOT_ALLOWED\x10\x06\x12\x17\x0A\x13ERROR_CODE_CONFLICT\x10\x07\x12\x1F\x0A\x1BERROR_CODE_VALIDATION_ERROR\x10\x08\x12\x1D\x0A\x19ERROR_CODE_LICENSE_LOCKED\x10\x09\x12\"\x0A\x1EERROR_CODE_RATE_LIMIT_EXCEEDED\x10\x0A\x12\x1D\x0A\x19ERROR_CODE_INTERNAL_ERROR\x10\x0B\x12\x1A\x0A\x16ERROR_CODE_BAD_GATEWAY\x10\x0C\x12\x1E\x0A\x1AERROR_CODE_GATEWAY_TIMEOUT\x10\x0D\x12\"\x0A\x1EERROR_CODE_SERVICE_UNAVAILABLE\x10\x0E\x12\x1E\x0A\x1AERROR_CODE_NOT_IMPLEMENTED\x10\x0F*\xB1\x01\x0A\x05Scope\x12\x15\x0A\x11SCOPE_UNSPECIFIED\x10\x00\x12#\x0A\x1FSCOPE_RAPIDSIGN_DOCUMENTS_WRITE\x10\x01\x12\"\x0A\x1ESCOPE_RAPIDSIGN_DOCUMENTS_READ\x10\x02\x12\"\x0A\x1ESCOPE_RAPIDSIGN_DOCUMENTS_SIGN\x10\x03\x12\$\x0A SCOPE_RAPIDSIGN_DOCUMENTS_NOTIFY\x10\x04B\xB7\x01\x0A\x0Ecom.api.isa.v1B\x0BCommonProtoP\x01ZEgithub.com/Software-Automation-Holdings-LLC/sdk/core/api/isa/v1;isav1\xA2\x02\x03AIX\xAA\x02\x12IsaSdk.Core.Api.V1\xCA\x02\x0ESah\\Isa\\Api\\V1\xE2\x02\x13Sah\\Isa\\Api\\V1\\Meta\xEA\x02\x0CApi::Isa::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

