// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api/rapidsign/v1/common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IsaSdk.RapidSign.Api.V1 {

  /// <summary>Holder for reflection information generated from api/rapidsign/v1/common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for api/rapidsign/v1/common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1hcGkvcmFwaWRzaWduL3YxL2NvbW1vbi5wcm90bxIQYXBpLnJhcGlkc2ln",
            "bi52MULlAQoUY29tLmFwaS5yYXBpZHNpZ24udjFCC0NvbW1vblByb3RvUAFa",
            "VmdpdGh1Yi5jb20vU29mdHdhcmUtQXV0b21hdGlvbi1Ib2xkaW5ncy1MTEMv",
            "c2RrL3JhcGlkc2lnbi9hcGkvcmFwaWRzaWduL3YxO3JhcGlkc2lnbnYxogID",
            "QVJYqgIXSXNhU2RrLlJhcGlkU2lnbi5BcGkuVjHKAhRTYWhcUmFwaWRTaWdu",
            "XEFwaVxWMeICGVNhaFxSYXBpZFNpZ25cQXBpXFYxXE1ldGHqAhJBcGk6OlJh",
            "cGlkc2lnbjo6VjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
