import { describe, expect, it } from 'vitest';
import { compress, decompress } from '../../src/core/compression';
import fixtures from './fixtures.json';

/**
 * These fixtures were generated by running the original
 * `eapp-system/resources/js/lib/Compression.js#SAH_Compress` against 12
 * canonical inputs. The `body` values are the exact strings the PHP
 * decompressor receives today; if any of these tests fail we have a
 * wire-format regression, not a test bug.
 */
const compressionVectors = fixtures.compressionFixtures as ReadonlyArray<{
  input: string;
  body: string;
}>;

describe('compression', () => {
  describe('compress', () => {
    it('wraps output in the {compressed: true, body} Form.enc envelope', async () => {
      const envelope = await compress('hello');
      expect(envelope.compressed).toBe(true);
      expect(typeof envelope.body).toBe('string');
      expect(envelope.body.length).toBeGreaterThan(0);
    });

    it.each(compressionVectors)(
      'produces the exact wire body for input %#',
      async ({ input, body }) => {
        const envelope = await compress(input);
        expect(envelope.body).toBe(body);
      },
    );

    it('accepts Uint8Array input and produces the same output as the UTF-8 string form', async () => {
      const text = 'Hello, World!';
      const asString = await compress(text);
      const asBytes = await compress(new TextEncoder().encode(text));
      expect(asBytes.body).toBe(asString.body);
    });
  });

  describe('decompress', () => {
    it.each(compressionVectors)(
      'round-trips wire body %# back to the original input',
      async ({ input, body }) => {
        const roundTrip = await decompress({ compressed: true, body });
        expect(roundTrip).toBe(input);
      },
    );

    it('rejects an envelope missing compressed: true', async () => {
      await expect(
        decompress({ compressed: false as unknown as true, body: 'abc' }),
      ).rejects.toThrow(/envelope/);
    });

    it('rejects a malformed envelope', async () => {
      await expect(
        decompress(undefined as unknown as { compressed: true; body: string }),
      ).rejects.toThrow(/envelope/);
    });
  });

  describe('round-trip', () => {
    it.each(compressionVectors)('compress ∘ decompress is identity for fixture %#', async ({ input }) => {
      const roundTrip = await decompress(await compress(input));
      expect(roundTrip).toBe(input);
    });
  });
});
