// Barrel for @isa-sdk/proxy — re-exports generated Protobuf-ES modules.
// Generated by `buf generate --template shared/schemas/buf.gen.sdk.yaml`.
// DO NOT hand-edit.
export * from "./api/proxy/v1/proxy_pb.js";
