// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api/zyins/v1/common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IsaSdk.ZyINS.Api.V1 {

  /// <summary>Holder for reflection information generated from api/zyins/v1/common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for api/zyins/v1/common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlhcGkvenlpbnMvdjEvY29tbW9uLnByb3RvEgxhcGkuenlpbnMudjEaHGdv",
            "b2dsZS9wcm90b2J1Zi9zdHJ1Y3QucHJvdG8iiQEKCEVudmVsb3BlEhYKBm9i",
            "amVjdBgBIAEoCVIGb2JqZWN0EhoKCGxpdmVtb2RlGAIgASgIUghsaXZlbW9k",
            "ZRIdCgpyZXF1ZXN0X2lkGAMgASgJUglyZXF1ZXN0SWQSKgoEZGF0YRgEIAEo",
            "CzIWLmdvb2dsZS5wcm90b2J1Zi5WYWx1ZVIEZGF0YSpECgZHZW5kZXISFgoS",
            "R0VOREVSX1VOU1BFQ0lGSUVEEAASDwoLR0VOREVSX01BTEUQARIRCg1HRU5E",
            "RVJfRkVNQUxFEAIqkQEKC1Rva2VuU3RhdHVzEhwKGFRPS0VOX1NUQVRVU19V",
            "TlNQRUNJRklFRBAAEhcKE1RPS0VOX1NUQVRVU19BQ1RJVkUQARIYChRUT0tF",
            "Tl9TVEFUVVNfUkVWT0tFRBACEhgKFFRPS0VOX1NUQVRVU19FWFBJUkVEEAMS",
            "FwoTVE9LRU5fU1RBVFVTX0JBTk5FRBAEKoMBCg1BY2NvdW50U3RhdHVzEh4K",
            "GkFDQ09VTlRfU1RBVFVTX1VOU1BFQ0lGSUVEEAASGQoVQUNDT1VOVF9TVEFU",
            "VVNfQUNUSVZFEAESHAoYQUNDT1VOVF9TVEFUVVNfU1VTUEVOREVEEAISGQoV",
            "QUNDT1VOVF9TVEFUVVNfQ0xPU0VEEAMqggEKDUxpY2Vuc2VTdGF0dXMSHgoa",
            "TElDRU5TRV9TVEFUVVNfVU5TUEVDSUZJRUQQABIYChRMSUNFTlNFX1NUQVRV",
            "U19WQUxJRBABEhoKFkxJQ0VOU0VfU1RBVFVTX0lOVkFMSUQQAhIbChdMSUNF",
            "TlNFX1NUQVRVU19JTkFDVElWRRADKqcBCgxQcm9kdWN0Q2xhc3MSHQoZUFJP",
            "RFVDVF9DTEFTU19VTlNQRUNJRklFRBAAEhUKEVBST0RVQ1RfQ0xBU1NfRkVY",
            "EAESFgoSUFJPRFVDVF9DTEFTU19URVJNEAISGAoUUFJPRFVDVF9DTEFTU19N",
            "RURTVVAQAxIZChVQUk9EVUNUX0NMQVNTX1BSRU5FRUQQBBIUChBQUk9EVUNU",
            "X0NMQVNTX1dMEAUqsQEKEERlYXRoQmVuZWZpdFJhbmsSIgoeREVBVEhfQkVO",
            "RUZJVF9SQU5LX1VOU1BFQ0lGSUVEEAASIAocREVBVEhfQkVORUZJVF9SQU5L",
            "X0lNTUVESUFURRABEh0KGURFQVRIX0JFTkVGSVRfUkFOS19HUkFERUQQAhIa",
            "ChZERUFUSF9CRU5FRklUX1JBTktfUk9QEAMSHAoYREVBVEhfQkVORUZJVF9S",
            "QU5LX09USEVSEAQqYwoJUXVvdGVUeXBlEhoKFlFVT1RFX1RZUEVfVU5TUEVD",
            "SUZJRUQQABIbChdRVU9URV9UWVBFX0ZBQ0VfQU1PVU5UUxABEh0KGVFVT1RF",
            "X1RZUEVfTU9OVEhMWV9CVURHRVQQAkLFAQoQY29tLmFwaS56eWlucy52MUIL",
            "Q29tbW9uUHJvdG9QAVpKZ2l0aHViLmNvbS9Tb2Z0d2FyZS1BdXRvbWF0aW9u",
            "LUhvbGRpbmdzLUxMQy9zZGsvenlpbnMvYXBpL3p5aW5zL3YxO3p5aW5zdjGi",
            "AgNBWliqAhNJc2FTZGsuWnlJTlMuQXBpLlYxygIQU2FoXFp5SU5TXEFwaVxW",
            "MeICFVNhaFxaeUlOU1xBcGlcVjFcTWV0YeoCDkFwaTo6WnlpbnM6OlYxYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::IsaSdk.ZyINS.Api.V1.Gender), typeof(global::IsaSdk.ZyINS.Api.V1.TokenStatus), typeof(global::IsaSdk.ZyINS.Api.V1.AccountStatus), typeof(global::IsaSdk.ZyINS.Api.V1.LicenseStatus), typeof(global::IsaSdk.ZyINS.Api.V1.ProductClass), typeof(global::IsaSdk.ZyINS.Api.V1.DeathBenefitRank), typeof(global::IsaSdk.ZyINS.Api.V1.QuoteType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::IsaSdk.ZyINS.Api.V1.Envelope), global::IsaSdk.ZyINS.Api.V1.Envelope.Parser, new[]{ "Object", "Livemode", "RequestId", "Data" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Gender captures biological sex for underwriting. Canonical wire values
  /// are lowercase full words (`male`, `female`) per ADR-012. The server
  /// normalizes legacy inputs (`M`, `F`, `Male`) to canonical values in
  /// responses.
  /// </summary>
  public enum Gender {
    /// <summary>
    /// Default zero value. Never emitted by the server.
    /// </summary>
    [pbr::OriginalName("GENDER_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Male biological sex for underwriting (wire value: `male`).
    /// </summary>
    [pbr::OriginalName("GENDER_MALE")] Male = 1,
    /// <summary>
    /// Female biological sex for underwriting (wire value: `female`).
    /// </summary>
    [pbr::OriginalName("GENDER_FEMALE")] Female = 2,
  }

  /// <summary>
  /// TokenStatus is the API token lifecycle state per ADR-012.
  /// </summary>
  public enum TokenStatus {
    /// <summary>
    /// Default zero value. Never emitted by the server.
    /// </summary>
    [pbr::OriginalName("TOKEN_STATUS_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Token is usable (wire: `active`).
    /// </summary>
    [pbr::OriginalName("TOKEN_STATUS_ACTIVE")] Active = 1,
    /// <summary>
    /// Token was intentionally terminated (wire: `revoked`). Permanent.
    /// </summary>
    [pbr::OriginalName("TOKEN_STATUS_REVOKED")] Revoked = 2,
    /// <summary>
    /// Token aged out of its validity window (wire: `expired`). Permanent.
    /// </summary>
    [pbr::OriginalName("TOKEN_STATUS_EXPIRED")] Expired = 3,
    /// <summary>
    /// Token was permanently banned by an administrator (wire: `banned`).
    /// Unlike revoked, a banned token can never be reinstated.
    /// </summary>
    [pbr::OriginalName("TOKEN_STATUS_BANNED")] Banned = 4,
  }

  /// <summary>
  /// AccountStatus is the account lifecycle state per ADR-012.
  /// </summary>
  public enum AccountStatus {
    /// <summary>
    /// Default zero value. Never emitted by the server.
    /// </summary>
    [pbr::OriginalName("ACCOUNT_STATUS_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Account is in normal operation (wire: `active`).
    /// </summary>
    [pbr::OriginalName("ACCOUNT_STATUS_ACTIVE")] Active = 1,
    /// <summary>
    /// Reversible admin hold (wire: `suspended`).
    /// </summary>
    [pbr::OriginalName("ACCOUNT_STATUS_SUSPENDED")] Suspended = 2,
    /// <summary>
    /// Permanent admin closure; archival only (wire: `closed`).
    /// </summary>
    [pbr::OriginalName("ACCOUNT_STATUS_CLOSED")] Closed = 3,
  }

  /// <summary>
  /// LicenseStatus is the license validation state.
  /// </summary>
  public enum LicenseStatus {
    /// <summary>
    /// Default zero value. Never emitted by the server.
    /// </summary>
    [pbr::OriginalName("LICENSE_STATUS_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// License is authenticated and currently usable (wire: `valid`).
    /// </summary>
    [pbr::OriginalName("LICENSE_STATUS_VALID")] Valid = 1,
    /// <summary>
    /// Credentials do not match a known license (wire: `invalid`).
    /// </summary>
    [pbr::OriginalName("LICENSE_STATUS_INVALID")] Invalid = 2,
    /// <summary>
    /// License exists but is not currently usable (wire: `inactive`).
    /// </summary>
    [pbr::OriginalName("LICENSE_STATUS_INACTIVE")] Inactive = 3,
  }

  /// <summary>
  /// ProductClass is the insurance product family classification.
  /// </summary>
  public enum ProductClass {
    /// <summary>
    /// Default zero value. Never emitted by the server.
    /// </summary>
    [pbr::OriginalName("PRODUCT_CLASS_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Final expense (wire: `fex`).
    /// </summary>
    [pbr::OriginalName("PRODUCT_CLASS_FEX")] Fex = 1,
    /// <summary>
    /// Term life (wire: `term`).
    /// </summary>
    [pbr::OriginalName("PRODUCT_CLASS_TERM")] Term = 2,
    /// <summary>
    /// Medicare supplement (wire: `medsup`).
    /// </summary>
    [pbr::OriginalName("PRODUCT_CLASS_MEDSUP")] Medsup = 3,
    /// <summary>
    /// Pre-need funeral (wire: `preneed`).
    /// </summary>
    [pbr::OriginalName("PRODUCT_CLASS_PRENEED")] Preneed = 4,
    /// <summary>
    /// Whole life (wire: `wl`).
    /// </summary>
    [pbr::OriginalName("PRODUCT_CLASS_WL")] Wl = 5,
  }

  /// <summary>
  /// DeathBenefitRank is the underwriting rank category.
  /// </summary>
  public enum DeathBenefitRank {
    /// <summary>
    /// Default zero value. Never emitted by the server.
    /// </summary>
    [pbr::OriginalName("DEATH_BENEFIT_RANK_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Policy takes effect immediately (wire: `immediate`).
    /// </summary>
    [pbr::OriginalName("DEATH_BENEFIT_RANK_IMMEDIATE")] Immediate = 1,
    /// <summary>
    /// Waiting period applies (wire: `graded`).
    /// </summary>
    [pbr::OriginalName("DEATH_BENEFIT_RANK_GRADED")] Graded = 2,
    /// <summary>
    /// Return of premium (wire: `rop`).
    /// </summary>
    [pbr::OriginalName("DEATH_BENEFIT_RANK_ROP")] Rop = 3,
    /// <summary>
    /// Remaining classifications (wire: `other`).
    /// </summary>
    [pbr::OriginalName("DEATH_BENEFIT_RANK_OTHER")] Other = 4,
  }

  /// <summary>
  /// QuoteType is the quote computation mode.
  /// </summary>
  public enum QuoteType {
    /// <summary>
    /// Default zero value. Never emitted by the server.
    /// </summary>
    [pbr::OriginalName("QUOTE_TYPE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Compute premiums for given face-value amounts (wire: `face_amounts`).
    /// </summary>
    [pbr::OriginalName("QUOTE_TYPE_FACE_AMOUNTS")] FaceAmounts = 1,
    /// <summary>
    /// Compute coverage achievable for a given monthly budget (wire: `monthly_budget`).
    /// </summary>
    [pbr::OriginalName("QUOTE_TYPE_MONTHLY_BUDGET")] MonthlyBudget = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Envelope is the standard response wrapper per the response-envelope
  /// contract. Every success response carries `object`, `livemode`, and
  /// `request_id`; resource-specific bodies live in a typed `data` field on
  /// each response message (not this shared type — proto does not inherit).
  /// This message exists for documentation of the contract; concrete
  /// responses duplicate the three fields explicitly so each has a typed
  /// `data` shape rather than a `google.protobuf.Any`.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Envelope : pb::IMessage<Envelope>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Envelope> _parser = new pb::MessageParser<Envelope>(() => new Envelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Envelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IsaSdk.ZyINS.Api.V1.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope(Envelope other) : this() {
      object_ = other.object_;
      livemode_ = other.livemode_;
      requestId_ = other.requestId_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope Clone() {
      return new Envelope(this);
    }

    /// <summary>Field number for the "object" field.</summary>
    public const int ObjectFieldNumber = 1;
    private string object_ = "";
    /// <summary>
    /// Resource type discriminator. Concrete values depend on the endpoint
    /// (e.g. "quote_result", "license", "token").
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Object {
      get { return object_; }
      set {
        object_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "livemode" field.</summary>
    public const int LivemodeFieldNumber = 2;
    private bool livemode_;
    /// <summary>
    /// True in production; false for test-mode responses.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Livemode {
      get { return livemode_; }
      set {
        livemode_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 3;
    private string requestId_ = "";
    /// <summary>
    /// Unique request identifier; echoed into all log lines for the request.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Value data_;
    /// <summary>
    /// Endpoint-specific payload. Concrete responses replace this with a
    /// typed message; it appears here only to document the envelope shape.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Value Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Envelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Envelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Object != other.Object) return false;
      if (Livemode != other.Livemode) return false;
      if (RequestId != other.RequestId) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Object.Length != 0) hash ^= Object.GetHashCode();
      if (Livemode != false) hash ^= Livemode.GetHashCode();
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Object.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Object);
      }
      if (Livemode != false) {
        output.WriteRawTag(16);
        output.WriteBool(Livemode);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RequestId);
      }
      if (data_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Object.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Object);
      }
      if (Livemode != false) {
        output.WriteRawTag(16);
        output.WriteBool(Livemode);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RequestId);
      }
      if (data_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Object.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Object);
      }
      if (Livemode != false) {
        size += 1 + 1;
      }
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Envelope other) {
      if (other == null) {
        return;
      }
      if (other.Object.Length != 0) {
        Object = other.Object;
      }
      if (other.Livemode != false) {
        Livemode = other.Livemode;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Protobuf.WellKnownTypes.Value();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Object = input.ReadString();
            break;
          }
          case 16: {
            Livemode = input.ReadBool();
            break;
          }
          case 26: {
            RequestId = input.ReadString();
            break;
          }
          case 34: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Value();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Object = input.ReadString();
            break;
          }
          case 16: {
            Livemode = input.ReadBool();
            break;
          }
          case 26: {
            RequestId = input.ReadString();
            break;
          }
          case 34: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Value();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
