// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api/zyins/v1/preferences.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IsaSdk.ZyINS.Api.V1 {

  /// <summary>Holder for reflection information generated from api/zyins/v1/preferences.proto</summary>
  public static partial class PreferencesReflection {

    #region Descriptor
    /// <summary>File descriptor for api/zyins/v1/preferences.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PreferencesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5hcGkvenlpbnMvdjEvcHJlZmVyZW5jZXMucHJvdG8SDGFwaS56eWlucy52",
            "MRocZ29vZ2xlL2FwaS9hbm5vdGF0aW9ucy5wcm90byKFAQoYQmFja3VwUHJl",
            "ZmVyZW5jZXNSZXF1ZXN0EhQKBWVtYWlsGAEgASgJUgVlbWFpbBIYCgdrZXlj",
            "b2RlGAIgASgJUgdrZXljb2RlEjkKBXByZWZzGAMgASgLMiMuYXBpLnp5aW5z",
            "LnYxLldoaXRlbGFiZWxQcmVmZXJlbmNlc1IFcHJlZnMiSwoZUmVzdG9yZVBy",
            "ZWZlcmVuY2VzUmVxdWVzdBIUCgVlbWFpbBgBIAEoCVIFZW1haWwSGAoHa2V5",
            "Y29kZRgCIAEoCVIHa2V5Y29kZSKjAQoTUHJlZmVyZW5jZXNFbnZlbG9wZRIW",
            "CgZvYmplY3QYASABKAlSBm9iamVjdBIaCghsaXZlbW9kZRgCIAEoCFIIbGl2",
            "ZW1vZGUSHQoKcmVxdWVzdF9pZBgDIAEoCVIJcmVxdWVzdElkEjkKBXByZWZz",
            "GAQgASgLMiMuYXBpLnp5aW5zLnYxLldoaXRlbGFiZWxQcmVmZXJlbmNlc1IF",
            "cHJlZnMi0QIKFVdoaXRlbGFiZWxQcmVmZXJlbmNlcxIbCgluYXZfY29sb3IY",
            "ASABKAlSCG5hdkNvbG9yEh0KCm1haW5fY29sb3IYAiABKAlSCW1haW5Db2xv",
            "chIqChFoZWFkZXJfdGV4dF9jb2xvchgDIAEoCVIPaGVhZGVyVGV4dENvbG9y",
            "EkgKEGRlZmF1bHRfc2V0dGluZ3MYBCABKAsyHS5hcGkuenlpbnMudjEuRGVm",
            "YXVsdFNldHRpbmdzUg9kZWZhdWx0U2V0dGluZ3MSIQoMZGlzcGxheV9uYW1l",
            "GAUgASgJUgtkaXNwbGF5TmFtZRIjCg1jb250YWN0X2VtYWlsGAYgASgJUgxj",
            "b250YWN0RW1haWwSIwoNY29udGFjdF9waG9uZRgHIAEoCVIMY29udGFjdFBo",
            "b25lEhkKCGxvZ29fdXJsGAggASgJUgdsb2dvVXJsIr4BCg9EZWZhdWx0U2V0",
            "dGluZ3MSFAoFc3RhdGUYASABKAlSBXN0YXRlEiUKDnByb2R1Y3RfZmFtaWx5",
            "GAIgASgJUg1wcm9kdWN0RmFtaWx5Eh8KC2ZhY2VfYW1vdW50GAMgASgFUgpm",
            "YWNlQW1vdW50EiUKDm1vbnRobHlfYnVkZ2V0GAQgASgFUg1tb250aGx5QnVk",
            "Z2V0EiYKD21vZGVfb2ZfcGF5bWVudBgFIAEoCVINbW9kZU9mUGF5bWVudDKc",
            "AgoSUHJlZmVyZW5jZXNTZXJ2aWNlEoEBChFCYWNrdXBQcmVmZXJlbmNlcxIm",
            "LmFwaS56eWlucy52MS5CYWNrdXBQcmVmZXJlbmNlc1JlcXVlc3QaIS5hcGku",
            "enlpbnMudjEuUHJlZmVyZW5jZXNFbnZlbG9wZSIhgtPkkwIbOgEqIhYvdjIv",
            "cHJlZmVyZW5jZXMvYmFja3VwEoEBChJSZXN0b3JlUHJlZmVyZW5jZXMSJy5h",
            "cGkuenlpbnMudjEuUmVzdG9yZVByZWZlcmVuY2VzUmVxdWVzdBohLmFwaS56",
            "eWlucy52MS5QcmVmZXJlbmNlc0VudmVsb3BlIh+C0+STAhkSFy92Mi9wcmVm",
            "ZXJlbmNlcy9yZXN0b3JlQsoBChBjb20uYXBpLnp5aW5zLnYxQhBQcmVmZXJl",
            "bmNlc1Byb3RvUAFaSmdpdGh1Yi5jb20vU29mdHdhcmUtQXV0b21hdGlvbi1I",
            "b2xkaW5ncy1MTEMvc2RrL3p5aW5zL2FwaS96eWlucy92MTt6eWluc3YxogID",
            "QVpYqgITSXNhU2RrLlp5SU5TLkFwaS5WMcoCEFNhaFxaeUlOU1xBcGlcVjHi",
            "AhVTYWhcWnlJTlNcQXBpXFYxXE1ldGHqAg5BcGk6Olp5aW5zOjpWMWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::IsaSdk.ZyINS.Api.V1.BackupPreferencesRequest), global::IsaSdk.ZyINS.Api.V1.BackupPreferencesRequest.Parser, new[]{ "Email", "Keycode", "Prefs" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::IsaSdk.ZyINS.Api.V1.RestorePreferencesRequest), global::IsaSdk.ZyINS.Api.V1.RestorePreferencesRequest.Parser, new[]{ "Email", "Keycode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::IsaSdk.ZyINS.Api.V1.PreferencesEnvelope), global::IsaSdk.ZyINS.Api.V1.PreferencesEnvelope.Parser, new[]{ "Object", "Livemode", "RequestId", "Prefs" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::IsaSdk.ZyINS.Api.V1.WhitelabelPreferences), global::IsaSdk.ZyINS.Api.V1.WhitelabelPreferences.Parser, new[]{ "NavColor", "MainColor", "HeaderTextColor", "DefaultSettings", "DisplayName", "ContactEmail", "ContactPhone", "LogoUrl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::IsaSdk.ZyINS.Api.V1.DefaultSettings), global::IsaSdk.ZyINS.Api.V1.DefaultSettings.Parser, new[]{ "State", "ProductFamily", "FaceAmount", "MonthlyBudget", "ModeOfPayment" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// BackupPreferencesRequest is the body for POST /v2/preferences/backup.
  /// The identity tuple is `(email, keycode)`; both are required and both
  /// participate in the storage key.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BackupPreferencesRequest : pb::IMessage<BackupPreferencesRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BackupPreferencesRequest> _parser = new pb::MessageParser<BackupPreferencesRequest>(() => new BackupPreferencesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BackupPreferencesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IsaSdk.ZyINS.Api.V1.PreferencesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BackupPreferencesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BackupPreferencesRequest(BackupPreferencesRequest other) : this() {
      email_ = other.email_;
      keycode_ = other.keycode_;
      prefs_ = other.prefs_ != null ? other.prefs_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BackupPreferencesRequest Clone() {
      return new BackupPreferencesRequest(this);
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 1;
    private string email_ = "";
    /// <summary>
    /// Account email used as part of the lookup key. Required.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "keycode" field.</summary>
    public const int KeycodeFieldNumber = 2;
    private string keycode_ = "";
    /// <summary>
    /// BPP keycode used as part of the lookup key. Required.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Keycode {
      get { return keycode_; }
      set {
        keycode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prefs" field.</summary>
    public const int PrefsFieldNumber = 3;
    private global::IsaSdk.ZyINS.Api.V1.WhitelabelPreferences prefs_;
    /// <summary>
    /// The whitelabel preferences payload to persist. Identity-preserving:
    /// the same bytes are returned by RestorePreferences.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::IsaSdk.ZyINS.Api.V1.WhitelabelPreferences Prefs {
      get { return prefs_; }
      set {
        prefs_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BackupPreferencesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BackupPreferencesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Email != other.Email) return false;
      if (Keycode != other.Keycode) return false;
      if (!object.Equals(Prefs, other.Prefs)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Keycode.Length != 0) hash ^= Keycode.GetHashCode();
      if (prefs_ != null) hash ^= Prefs.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (Keycode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Keycode);
      }
      if (prefs_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Prefs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (Keycode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Keycode);
      }
      if (prefs_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Prefs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Keycode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Keycode);
      }
      if (prefs_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Prefs);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BackupPreferencesRequest other) {
      if (other == null) {
        return;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Keycode.Length != 0) {
        Keycode = other.Keycode;
      }
      if (other.prefs_ != null) {
        if (prefs_ == null) {
          Prefs = new global::IsaSdk.ZyINS.Api.V1.WhitelabelPreferences();
        }
        Prefs.MergeFrom(other.Prefs);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
          case 18: {
            Keycode = input.ReadString();
            break;
          }
          case 26: {
            if (prefs_ == null) {
              Prefs = new global::IsaSdk.ZyINS.Api.V1.WhitelabelPreferences();
            }
            input.ReadMessage(Prefs);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
          case 18: {
            Keycode = input.ReadString();
            break;
          }
          case 26: {
            if (prefs_ == null) {
              Prefs = new global::IsaSdk.ZyINS.Api.V1.WhitelabelPreferences();
            }
            input.ReadMessage(Prefs);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// RestorePreferencesRequest is the query for GET /v2/preferences/restore.
  /// Both fields are required; both participate in the storage key.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RestorePreferencesRequest : pb::IMessage<RestorePreferencesRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RestorePreferencesRequest> _parser = new pb::MessageParser<RestorePreferencesRequest>(() => new RestorePreferencesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RestorePreferencesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IsaSdk.ZyINS.Api.V1.PreferencesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RestorePreferencesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RestorePreferencesRequest(RestorePreferencesRequest other) : this() {
      email_ = other.email_;
      keycode_ = other.keycode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RestorePreferencesRequest Clone() {
      return new RestorePreferencesRequest(this);
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 1;
    private string email_ = "";
    /// <summary>
    /// Account email used as part of the lookup key. Required.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "keycode" field.</summary>
    public const int KeycodeFieldNumber = 2;
    private string keycode_ = "";
    /// <summary>
    /// BPP keycode used as part of the lookup key. Required.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Keycode {
      get { return keycode_; }
      set {
        keycode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RestorePreferencesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RestorePreferencesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Email != other.Email) return false;
      if (Keycode != other.Keycode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Keycode.Length != 0) hash ^= Keycode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (Keycode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Keycode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (Keycode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Keycode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Keycode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Keycode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RestorePreferencesRequest other) {
      if (other == null) {
        return;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Keycode.Length != 0) {
        Keycode = other.Keycode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
          case 18: {
            Keycode = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
          case 18: {
            Keycode = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// PreferencesEnvelope is the canonical 200 body shape for both
  /// BackupPreferences and RestorePreferences. Both operations return the
  /// SAME shape — this is the round-trip contract enforced in tests.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PreferencesEnvelope : pb::IMessage<PreferencesEnvelope>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PreferencesEnvelope> _parser = new pb::MessageParser<PreferencesEnvelope>(() => new PreferencesEnvelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PreferencesEnvelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IsaSdk.ZyINS.Api.V1.PreferencesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PreferencesEnvelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PreferencesEnvelope(PreferencesEnvelope other) : this() {
      object_ = other.object_;
      livemode_ = other.livemode_;
      requestId_ = other.requestId_;
      prefs_ = other.prefs_ != null ? other.prefs_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PreferencesEnvelope Clone() {
      return new PreferencesEnvelope(this);
    }

    /// <summary>Field number for the "object" field.</summary>
    public const int ObjectFieldNumber = 1;
    private string object_ = "";
    /// <summary>
    /// Resource type discriminator. Wire value: `preferences`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Object {
      get { return object_; }
      set {
        object_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "livemode" field.</summary>
    public const int LivemodeFieldNumber = 2;
    private bool livemode_;
    /// <summary>
    /// True for live mode, false for test mode.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Livemode {
      get { return livemode_; }
      set {
        livemode_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 3;
    private string requestId_ = "";
    /// <summary>
    /// Unique request identifier.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prefs" field.</summary>
    public const int PrefsFieldNumber = 4;
    private global::IsaSdk.ZyINS.Api.V1.WhitelabelPreferences prefs_;
    /// <summary>
    /// The whitelabel preferences payload. Empty (zero-valued) when the
    /// account has never persisted preferences. Byte-identical between
    /// backup-write and the next restore-read.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::IsaSdk.ZyINS.Api.V1.WhitelabelPreferences Prefs {
      get { return prefs_; }
      set {
        prefs_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PreferencesEnvelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PreferencesEnvelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Object != other.Object) return false;
      if (Livemode != other.Livemode) return false;
      if (RequestId != other.RequestId) return false;
      if (!object.Equals(Prefs, other.Prefs)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Object.Length != 0) hash ^= Object.GetHashCode();
      if (Livemode != false) hash ^= Livemode.GetHashCode();
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (prefs_ != null) hash ^= Prefs.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Object.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Object);
      }
      if (Livemode != false) {
        output.WriteRawTag(16);
        output.WriteBool(Livemode);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RequestId);
      }
      if (prefs_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Prefs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Object.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Object);
      }
      if (Livemode != false) {
        output.WriteRawTag(16);
        output.WriteBool(Livemode);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RequestId);
      }
      if (prefs_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Prefs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Object.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Object);
      }
      if (Livemode != false) {
        size += 1 + 1;
      }
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (prefs_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Prefs);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PreferencesEnvelope other) {
      if (other == null) {
        return;
      }
      if (other.Object.Length != 0) {
        Object = other.Object;
      }
      if (other.Livemode != false) {
        Livemode = other.Livemode;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.prefs_ != null) {
        if (prefs_ == null) {
          Prefs = new global::IsaSdk.ZyINS.Api.V1.WhitelabelPreferences();
        }
        Prefs.MergeFrom(other.Prefs);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Object = input.ReadString();
            break;
          }
          case 16: {
            Livemode = input.ReadBool();
            break;
          }
          case 26: {
            RequestId = input.ReadString();
            break;
          }
          case 34: {
            if (prefs_ == null) {
              Prefs = new global::IsaSdk.ZyINS.Api.V1.WhitelabelPreferences();
            }
            input.ReadMessage(Prefs);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Object = input.ReadString();
            break;
          }
          case 16: {
            Livemode = input.ReadBool();
            break;
          }
          case 26: {
            RequestId = input.ReadString();
            break;
          }
          case 34: {
            if (prefs_ == null) {
              Prefs = new global::IsaSdk.ZyINS.Api.V1.WhitelabelPreferences();
            }
            input.ReadMessage(Prefs);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// WhitelabelPreferences is the server-typed shape of a customer's
  /// agent-portal preferences. Every field is optional from the
  /// customer's perspective; the server stores empty strings/arrays as
  /// "not set". Unknown fields on the wire are rejected.
  ///
  /// Adding a field is an additive change; removing or renaming a field
  /// is breaking and requires a new package version.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WhitelabelPreferences : pb::IMessage<WhitelabelPreferences>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WhitelabelPreferences> _parser = new pb::MessageParser<WhitelabelPreferences>(() => new WhitelabelPreferences());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WhitelabelPreferences> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IsaSdk.ZyINS.Api.V1.PreferencesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WhitelabelPreferences() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WhitelabelPreferences(WhitelabelPreferences other) : this() {
      navColor_ = other.navColor_;
      mainColor_ = other.mainColor_;
      headerTextColor_ = other.headerTextColor_;
      defaultSettings_ = other.defaultSettings_ != null ? other.defaultSettings_.Clone() : null;
      displayName_ = other.displayName_;
      contactEmail_ = other.contactEmail_;
      contactPhone_ = other.contactPhone_;
      logoUrl_ = other.logoUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WhitelabelPreferences Clone() {
      return new WhitelabelPreferences(this);
    }

    /// <summary>Field number for the "nav_color" field.</summary>
    public const int NavColorFieldNumber = 1;
    private string navColor_ = "";
    /// <summary>
    /// Hex color (e.g. `#1F2937`) for the agent-portal navigation chrome.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NavColor {
      get { return navColor_; }
      set {
        navColor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "main_color" field.</summary>
    public const int MainColorFieldNumber = 2;
    private string mainColor_ = "";
    /// <summary>
    /// Hex color for primary call-to-action buttons and accents.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MainColor {
      get { return mainColor_; }
      set {
        mainColor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "header_text_color" field.</summary>
    public const int HeaderTextColorFieldNumber = 3;
    private string headerTextColor_ = "";
    /// <summary>
    /// Hex color for header text rendered against `nav_color`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string HeaderTextColor {
      get { return headerTextColor_; }
      set {
        headerTextColor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "default_settings" field.</summary>
    public const int DefaultSettingsFieldNumber = 4;
    private global::IsaSdk.ZyINS.Api.V1.DefaultSettings defaultSettings_;
    /// <summary>
    /// Default values applied to new quote/case forms.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::IsaSdk.ZyINS.Api.V1.DefaultSettings DefaultSettings {
      get { return defaultSettings_; }
      set {
        defaultSettings_ = value;
      }
    }

    /// <summary>Field number for the "display_name" field.</summary>
    public const int DisplayNameFieldNumber = 5;
    private string displayName_ = "";
    /// <summary>
    /// Display name shown in the agent portal header. Optional.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DisplayName {
      get { return displayName_; }
      set {
        displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "contact_email" field.</summary>
    public const int ContactEmailFieldNumber = 6;
    private string contactEmail_ = "";
    /// <summary>
    /// Public contact email for the agency, surfaced in case emails.
    /// Optional.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ContactEmail {
      get { return contactEmail_; }
      set {
        contactEmail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "contact_phone" field.</summary>
    public const int ContactPhoneFieldNumber = 7;
    private string contactPhone_ = "";
    /// <summary>
    /// Public contact phone for the agency, surfaced in case emails.
    /// Optional.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ContactPhone {
      get { return contactPhone_; }
      set {
        contactPhone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "logo_url" field.</summary>
    public const int LogoUrlFieldNumber = 8;
    private string logoUrl_ = "";
    /// <summary>
    /// Logo image URL hosted on a customer-controlled origin. Optional.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LogoUrl {
      get { return logoUrl_; }
      set {
        logoUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WhitelabelPreferences);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WhitelabelPreferences other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NavColor != other.NavColor) return false;
      if (MainColor != other.MainColor) return false;
      if (HeaderTextColor != other.HeaderTextColor) return false;
      if (!object.Equals(DefaultSettings, other.DefaultSettings)) return false;
      if (DisplayName != other.DisplayName) return false;
      if (ContactEmail != other.ContactEmail) return false;
      if (ContactPhone != other.ContactPhone) return false;
      if (LogoUrl != other.LogoUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NavColor.Length != 0) hash ^= NavColor.GetHashCode();
      if (MainColor.Length != 0) hash ^= MainColor.GetHashCode();
      if (HeaderTextColor.Length != 0) hash ^= HeaderTextColor.GetHashCode();
      if (defaultSettings_ != null) hash ^= DefaultSettings.GetHashCode();
      if (DisplayName.Length != 0) hash ^= DisplayName.GetHashCode();
      if (ContactEmail.Length != 0) hash ^= ContactEmail.GetHashCode();
      if (ContactPhone.Length != 0) hash ^= ContactPhone.GetHashCode();
      if (LogoUrl.Length != 0) hash ^= LogoUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NavColor.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NavColor);
      }
      if (MainColor.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MainColor);
      }
      if (HeaderTextColor.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(HeaderTextColor);
      }
      if (defaultSettings_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(DefaultSettings);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DisplayName);
      }
      if (ContactEmail.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ContactEmail);
      }
      if (ContactPhone.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ContactPhone);
      }
      if (LogoUrl.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(LogoUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NavColor.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NavColor);
      }
      if (MainColor.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MainColor);
      }
      if (HeaderTextColor.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(HeaderTextColor);
      }
      if (defaultSettings_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(DefaultSettings);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DisplayName);
      }
      if (ContactEmail.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ContactEmail);
      }
      if (ContactPhone.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ContactPhone);
      }
      if (LogoUrl.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(LogoUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NavColor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NavColor);
      }
      if (MainColor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MainColor);
      }
      if (HeaderTextColor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HeaderTextColor);
      }
      if (defaultSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DefaultSettings);
      }
      if (DisplayName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
      }
      if (ContactEmail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContactEmail);
      }
      if (ContactPhone.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContactPhone);
      }
      if (LogoUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LogoUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WhitelabelPreferences other) {
      if (other == null) {
        return;
      }
      if (other.NavColor.Length != 0) {
        NavColor = other.NavColor;
      }
      if (other.MainColor.Length != 0) {
        MainColor = other.MainColor;
      }
      if (other.HeaderTextColor.Length != 0) {
        HeaderTextColor = other.HeaderTextColor;
      }
      if (other.defaultSettings_ != null) {
        if (defaultSettings_ == null) {
          DefaultSettings = new global::IsaSdk.ZyINS.Api.V1.DefaultSettings();
        }
        DefaultSettings.MergeFrom(other.DefaultSettings);
      }
      if (other.DisplayName.Length != 0) {
        DisplayName = other.DisplayName;
      }
      if (other.ContactEmail.Length != 0) {
        ContactEmail = other.ContactEmail;
      }
      if (other.ContactPhone.Length != 0) {
        ContactPhone = other.ContactPhone;
      }
      if (other.LogoUrl.Length != 0) {
        LogoUrl = other.LogoUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            NavColor = input.ReadString();
            break;
          }
          case 18: {
            MainColor = input.ReadString();
            break;
          }
          case 26: {
            HeaderTextColor = input.ReadString();
            break;
          }
          case 34: {
            if (defaultSettings_ == null) {
              DefaultSettings = new global::IsaSdk.ZyINS.Api.V1.DefaultSettings();
            }
            input.ReadMessage(DefaultSettings);
            break;
          }
          case 42: {
            DisplayName = input.ReadString();
            break;
          }
          case 50: {
            ContactEmail = input.ReadString();
            break;
          }
          case 58: {
            ContactPhone = input.ReadString();
            break;
          }
          case 66: {
            LogoUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            NavColor = input.ReadString();
            break;
          }
          case 18: {
            MainColor = input.ReadString();
            break;
          }
          case 26: {
            HeaderTextColor = input.ReadString();
            break;
          }
          case 34: {
            if (defaultSettings_ == null) {
              DefaultSettings = new global::IsaSdk.ZyINS.Api.V1.DefaultSettings();
            }
            input.ReadMessage(DefaultSettings);
            break;
          }
          case 42: {
            DisplayName = input.ReadString();
            break;
          }
          case 50: {
            ContactEmail = input.ReadString();
            break;
          }
          case 58: {
            ContactPhone = input.ReadString();
            break;
          }
          case 66: {
            LogoUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// DefaultSettings carries form defaults applied to new quotes and
  /// cases. Empty strings/zero values mean "no default; use the global
  /// fallback".
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DefaultSettings : pb::IMessage<DefaultSettings>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DefaultSettings> _parser = new pb::MessageParser<DefaultSettings>(() => new DefaultSettings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DefaultSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IsaSdk.ZyINS.Api.V1.PreferencesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DefaultSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DefaultSettings(DefaultSettings other) : this() {
      state_ = other.state_;
      productFamily_ = other.productFamily_;
      faceAmount_ = other.faceAmount_;
      monthlyBudget_ = other.monthlyBudget_;
      modeOfPayment_ = other.modeOfPayment_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DefaultSettings Clone() {
      return new DefaultSettings(this);
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 1;
    private string state_ = "";
    /// <summary>
    /// Default state code (USPS two-letter, uppercase).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string State {
      get { return state_; }
      set {
        state_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "product_family" field.</summary>
    public const int ProductFamilyFieldNumber = 2;
    private string productFamily_ = "";
    /// <summary>
    /// Default product family slug (e.g. `senior-life`).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProductFamily {
      get { return productFamily_; }
      set {
        productFamily_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "face_amount" field.</summary>
    public const int FaceAmountFieldNumber = 3;
    private int faceAmount_;
    /// <summary>
    /// Default coverage face amount in whole dollars. Zero means unset.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FaceAmount {
      get { return faceAmount_; }
      set {
        faceAmount_ = value;
      }
    }

    /// <summary>Field number for the "monthly_budget" field.</summary>
    public const int MonthlyBudgetFieldNumber = 4;
    private int monthlyBudget_;
    /// <summary>
    /// Default monthly budget in whole dollars. Zero means unset.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MonthlyBudget {
      get { return monthlyBudget_; }
      set {
        monthlyBudget_ = value;
      }
    }

    /// <summary>Field number for the "mode_of_payment" field.</summary>
    public const int ModeOfPaymentFieldNumber = 5;
    private string modeOfPayment_ = "";
    /// <summary>
    /// Default mode of payment (e.g. `monthly`, `annual`).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ModeOfPayment {
      get { return modeOfPayment_; }
      set {
        modeOfPayment_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DefaultSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DefaultSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (State != other.State) return false;
      if (ProductFamily != other.ProductFamily) return false;
      if (FaceAmount != other.FaceAmount) return false;
      if (MonthlyBudget != other.MonthlyBudget) return false;
      if (ModeOfPayment != other.ModeOfPayment) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (State.Length != 0) hash ^= State.GetHashCode();
      if (ProductFamily.Length != 0) hash ^= ProductFamily.GetHashCode();
      if (FaceAmount != 0) hash ^= FaceAmount.GetHashCode();
      if (MonthlyBudget != 0) hash ^= MonthlyBudget.GetHashCode();
      if (ModeOfPayment.Length != 0) hash ^= ModeOfPayment.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (State.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(State);
      }
      if (ProductFamily.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ProductFamily);
      }
      if (FaceAmount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FaceAmount);
      }
      if (MonthlyBudget != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(MonthlyBudget);
      }
      if (ModeOfPayment.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ModeOfPayment);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (State.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(State);
      }
      if (ProductFamily.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ProductFamily);
      }
      if (FaceAmount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FaceAmount);
      }
      if (MonthlyBudget != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(MonthlyBudget);
      }
      if (ModeOfPayment.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ModeOfPayment);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (State.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(State);
      }
      if (ProductFamily.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProductFamily);
      }
      if (FaceAmount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FaceAmount);
      }
      if (MonthlyBudget != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MonthlyBudget);
      }
      if (ModeOfPayment.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ModeOfPayment);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DefaultSettings other) {
      if (other == null) {
        return;
      }
      if (other.State.Length != 0) {
        State = other.State;
      }
      if (other.ProductFamily.Length != 0) {
        ProductFamily = other.ProductFamily;
      }
      if (other.FaceAmount != 0) {
        FaceAmount = other.FaceAmount;
      }
      if (other.MonthlyBudget != 0) {
        MonthlyBudget = other.MonthlyBudget;
      }
      if (other.ModeOfPayment.Length != 0) {
        ModeOfPayment = other.ModeOfPayment;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            State = input.ReadString();
            break;
          }
          case 18: {
            ProductFamily = input.ReadString();
            break;
          }
          case 24: {
            FaceAmount = input.ReadInt32();
            break;
          }
          case 32: {
            MonthlyBudget = input.ReadInt32();
            break;
          }
          case 42: {
            ModeOfPayment = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            State = input.ReadString();
            break;
          }
          case 18: {
            ProductFamily = input.ReadString();
            break;
          }
          case 24: {
            FaceAmount = input.ReadInt32();
            break;
          }
          case 32: {
            MonthlyBudget = input.ReadInt32();
            break;
          }
          case 42: {
            ModeOfPayment = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
