// branding.proto is a DESIGN-ONLY placeholder for the whitelabel
// branding contract.
//
// Status: DRAFT — not wired to any RPC, not exposed in the OpenAPI
// surface, not assigned a stable token namespace, not consumed by any
// SDK. This file exists so the design surface is visible in code review
// while the whitelabel contract is finalized.
//
// DO NOT:
//   - Add `google.api.http` annotations to messages here.
//   - Reference these messages from `cases.proto`, `email.proto`,
//     `preferences.proto`, or any other shipped proto.
//   - Generate OpenAPI schemas for this file.
//   - Generate SDK bindings for this file.
//
// TODO(whitelabel-contract): finalize the field set, allocate a stable
// proto field-number range, decide the persistence model (whether
// branding is a slice of preferences or a sibling resource), and add
// the service definition. Until then, treat this message as scratch.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file api/zyins/v1/branding.proto (package api.zyins.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/zyins/v1/branding.proto.
 */
export const file_api_zyins_v1_branding: GenFile = /*@__PURE__*/
  fileDesc("ChthcGkvenlpbnMvdjEvYnJhbmRpbmcucHJvdG8SDGFwaS56eWlucy52MSJNCghCcmFuZGluZxIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEhUKDXByaW1hcnlfY29sb3IYAyABKAkSEAoIbG9nb191cmwYBCABKAlCxwEKEGNvbS5hcGkuenlpbnMudjFCDUJyYW5kaW5nUHJvdG9QAVpKZ2l0aHViLmNvbS9Tb2Z0d2FyZS1BdXRvbWF0aW9uLUhvbGRpbmdzLUxMQy9zZGsvenlpbnMvYXBpL3p5aW5zL3YxO3p5aW5zdjGiAgNBWliqAhNJc2FTZGsuWnlJTlMuQXBpLlYxygIQU2FoXFp5SU5TXEFwaVxWMeICFVNhaFxaeUlOU1xBcGlcVjFcTWV0YeoCDkFwaTo6WnlpbnM6OlYxYgZwcm90bzM");

/**
 * Branding is the placeholder shape for the whitelabel branding
 * resource. The field set will change before this message ships;
 * callers MUST NOT depend on these field numbers.
 *
 * TODO(whitelabel-contract): replace this message with the finalized
 * shape.
 *
 * @generated from message api.zyins.v1.Branding
 */
export type Branding = Message<"api.zyins.v1.Branding"> & {
  /**
   * Placeholder identifier. Wire value semantics undecided.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Placeholder display name. May be removed.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Placeholder primary color. May be removed.
   *
   * @generated from field: string primary_color = 3;
   */
  primaryColor: string;

  /**
   * Placeholder logo URL. May be removed.
   *
   * @generated from field: string logo_url = 4;
   */
  logoUrl: string;
};

/**
 * Describes the message api.zyins.v1.Branding.
 * Use `create(BrandingSchema)` to create a new message.
 */
export const BrandingSchema: GenMessage<Branding> = /*@__PURE__*/
  messageDesc(file_api_zyins_v1_branding, 0);

