// cases.proto defines the account-scoped case persistence surface for the
// ZyINS Unified API. A "case" is an immutable, content-addressable
// snapshot of an underwriting evaluation (input + optional results +
// product list) that can be linked to from outside the API — the
// canonical agent-facing URL is `https://bestplanpro.com/?case=<hash>`.
//
// All routes are mounted under `zyins.isaapi.com/v1`. Every operation is
// account-scoped: the calling token determines `account_id`, every read
// filters by `account_id`, and there is no cross-account visibility at
// the query layer. Storage backs onto PostgreSQL (`store.CaseRepository`)
// with content-hash deduplication; large payloads spill to S3 with the
// row carrying an `s3_key` reference.
//
// Companion guides for integrators live in `api/guides/cases.md`. This
// file is the wire contract; the guides explain the dedup model, the
// readonly semantics, and the email helper.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file api/zyins/v1/cases.proto (package api.zyins.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { Value } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/zyins/v1/cases.proto.
 */
export const file_api_zyins_v1_cases: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGkvenlpbnMvdjEvY2FzZXMucHJvdG8SDGFwaS56eWlucy52MSJ1ChFDcmVhdGVDYXNlUmVxdWVzdBIlCgVpbnB1dBgBIAEoCzIWLmdvb2dsZS5wcm90b2J1Zi5WYWx1ZRInCgdyZXN1bHRzGAIgASgLMhYuZ29vZ2xlLnByb3RvYnVmLlZhbHVlEhAKCHByb2R1Y3RzGAMgAygJIh4KDkdldENhc2VSZXF1ZXN0EgwKBGhhc2gYASABKAkiMQoQTGlzdENhc2VzUmVxdWVzdBIOCgZjdXJzb3IYASABKAkSDQoFbGltaXQYAiABKAUimAEKEUxpc3RDYXNlc1Jlc3BvbnNlEg4KBm9iamVjdBgBIAEoCRIQCghsaXZlbW9kZRgCIAEoCBISCgpyZXF1ZXN0X2lkGAMgASgJEiYKBGRhdGEYBCADKAsyGC5hcGkuenlpbnMudjEuQ2FzZURldGFpbBIQCghoYXNfbW9yZRgFIAEoCBITCgtuZXh0X2N1cnNvchgGIAEoCSJLChBFbWFpbENhc2VSZXF1ZXN0EgwKBGhhc2gYASABKAkSCgoCdG8YAiABKAkSDwoHc3ViamVjdBgDIAEoCRIMCgRub3RlGAQgASgJIlkKEUVtYWlsQ2FzZVJlc3BvbnNlEg4KBm9iamVjdBgBIAEoCRIQCghsaXZlbW9kZRgCIAEoCBISCgpyZXF1ZXN0X2lkGAMgASgJEg4KBnN0YXR1cxgEIAEoCSLlAQoKQ2FzZURldGFpbBIOCgZvYmplY3QYASABKAkSEAoIbGl2ZW1vZGUYAiABKAgSEgoKcmVxdWVzdF9pZBgDIAEoCRIMCgRoYXNoGAQgASgJEgsKA3VybBgFIAEoCRIQCghyZWFkb25seRgGIAEoCBISCgpjcmVhdGVkX2F0GAcgASgJEiUKBWlucHV0GAggASgLMhYuZ29vZ2xlLnByb3RvYnVmLlZhbHVlEicKB3Jlc3VsdHMYCSABKAsyFi5nb29nbGUucHJvdG9idWYuVmFsdWUSEAoIcHJvZHVjdHMYCiADKAkymgMKDENhc2VzU2VydmljZRJcCgpDcmVhdGVDYXNlEh8uYXBpLnp5aW5zLnYxLkNyZWF0ZUNhc2VSZXF1ZXN0GhguYXBpLnp5aW5zLnYxLkNhc2VEZXRhaWwiE4LT5JMCDToBKiIIL3YxL2Nhc2USWgoHR2V0Q2FzZRIcLmFwaS56eWlucy52MS5HZXRDYXNlUmVxdWVzdBoYLmFwaS56eWlucy52MS5DYXNlRGV0YWlsIheC0+STAhESDy92MS9jYXNlL3toYXNofRJfCglMaXN0Q2FzZXMSHi5hcGkuenlpbnMudjEuTGlzdENhc2VzUmVxdWVzdBofLmFwaS56eWlucy52MS5MaXN0Q2FzZXNSZXNwb25zZSIRgtPkkwILEgkvdjEvY2FzZXMSbwoJRW1haWxDYXNlEh4uYXBpLnp5aW5zLnYxLkVtYWlsQ2FzZVJlcXVlc3QaHy5hcGkuenlpbnMudjEuRW1haWxDYXNlUmVzcG9uc2UiIYLT5JMCGzoBKiIWL3YxL2Nhc2VzL3toYXNofS9lbWFpbELEAQoQY29tLmFwaS56eWlucy52MUIKQ2FzZXNQcm90b1ABWkpnaXRodWIuY29tL1NvZnR3YXJlLUF1dG9tYXRpb24tSG9sZGluZ3MtTExDL3Nkay96eWlucy9hcGkvenlpbnMvdjE7enlpbnN2MaICA0FaWKoCE0lzYVNkay5aeUlOUy5BcGkuVjHKAhBTYWhcWnlJTlNcQXBpXFYx4gIVU2FoXFp5SU5TXEFwaVxWMVxNZXRh6gIOQXBpOjpaeWluczo6VjFiBnByb3RvMw", [file_google_api_annotations, file_google_protobuf_struct]);

/**
 * CreateCaseRequest is the body for POST /v1/case. The `input` field is
 * polymorphic: a JSON object is converted to XML server-side; a JSON
 * string is treated as raw XML for backward compatibility with legacy
 * integrations. New integrations should always send a structured object.
 *
 * @generated from message api.zyins.v1.CreateCaseRequest
 */
export type CreateCaseRequest = Message<"api.zyins.v1.CreateCaseRequest"> & {
  /**
   * The applicant inputs that produced this case. Either a structured
   * JSON object describing the proposed insured (preferred) or a raw
   * XML string for legacy callers. Required.
   *
   * @generated from field: google.protobuf.Value input = 1;
   */
  input?: Value | undefined;

  /**
   * The evaluation results to display alongside the input. When set,
   * the case is marked readonly: viewers see the cached results rather
   * than re-running the engine. Optional.
   *
   * @generated from field: google.protobuf.Value results = 2;
   */
  results?: Value | undefined;

  /**
   * The product slugs the case was evaluated against. Persisted as a
   * `|`-joined string internally; supplied as an array on the wire.
   * Optional.
   *
   * @generated from field: repeated string products = 3;
   */
  products: string[];
};

/**
 * Describes the message api.zyins.v1.CreateCaseRequest.
 * Use `create(CreateCaseRequestSchema)` to create a new message.
 */
export const CreateCaseRequestSchema: GenMessage<CreateCaseRequest> = /*@__PURE__*/
  messageDesc(file_api_zyins_v1_cases, 0);

/**
 * GetCaseRequest identifies a case by short hash.
 *
 * @generated from message api.zyins.v1.GetCaseRequest
 */
export type GetCaseRequest = Message<"api.zyins.v1.GetCaseRequest"> & {
  /**
   * 11-character alphanumeric short hash from CreateCase. Path parameter.
   *
   * @generated from field: string hash = 1;
   */
  hash: string;
};

/**
 * Describes the message api.zyins.v1.GetCaseRequest.
 * Use `create(GetCaseRequestSchema)` to create a new message.
 */
export const GetCaseRequestSchema: GenMessage<GetCaseRequest> = /*@__PURE__*/
  messageDesc(file_api_zyins_v1_cases, 1);

/**
 * ListCasesRequest is the cursor-paginated request body for
 * GET /v1/cases.
 *
 * @generated from message api.zyins.v1.ListCasesRequest
 */
export type ListCasesRequest = Message<"api.zyins.v1.ListCasesRequest"> & {
  /**
   * Opaque pagination cursor from a previous response's `next_cursor`.
   * Empty string requests the first page.
   *
   * @generated from field: string cursor = 1;
   */
  cursor: string;

  /**
   * Page size. Defaults to 25, max 100. Zero means default.
   *
   * @generated from field: int32 limit = 2;
   */
  limit: number;
};

/**
 * Describes the message api.zyins.v1.ListCasesRequest.
 * Use `create(ListCasesRequestSchema)` to create a new message.
 */
export const ListCasesRequestSchema: GenMessage<ListCasesRequest> = /*@__PURE__*/
  messageDesc(file_api_zyins_v1_cases, 2);

/**
 * ListCasesResponse is the 200 body from ListCases.
 *
 * @generated from message api.zyins.v1.ListCasesResponse
 */
export type ListCasesResponse = Message<"api.zyins.v1.ListCasesResponse"> & {
  /**
   * Resource type discriminator. Wire value: `list`.
   *
   * @generated from field: string object = 1;
   */
  object: string;

  /**
   * True for live mode, false for test mode.
   *
   * @generated from field: bool livemode = 2;
   */
  livemode: boolean;

  /**
   * Unique request identifier.
   *
   * @generated from field: string request_id = 3;
   */
  requestId: string;

  /**
   * The cases visible to the calling account, newest first.
   *
   * @generated from field: repeated api.zyins.v1.CaseDetail data = 4;
   */
  data: CaseDetail[];

  /**
   * True when more results exist past `next_cursor`.
   *
   * @generated from field: bool has_more = 5;
   */
  hasMore: boolean;

  /**
   * Cursor for the next page, or empty when `has_more` is false.
   *
   * @generated from field: string next_cursor = 6;
   */
  nextCursor: string;
};

/**
 * Describes the message api.zyins.v1.ListCasesResponse.
 * Use `create(ListCasesResponseSchema)` to create a new message.
 */
export const ListCasesResponseSchema: GenMessage<ListCasesResponse> = /*@__PURE__*/
  messageDesc(file_api_zyins_v1_cases, 3);

/**
 * EmailCaseRequest is the body for POST /v1/cases/{hash}/email.
 *
 * @generated from message api.zyins.v1.EmailCaseRequest
 */
export type EmailCaseRequest = Message<"api.zyins.v1.EmailCaseRequest"> & {
  /**
   * Short hash of the case to email. Path parameter.
   *
   * @generated from field: string hash = 1;
   */
  hash: string;

  /**
   * Recipient email address. Required; must be RFC 5322 valid.
   *
   * @generated from field: string to = 2;
   */
  to: string;

  /**
   * Subject line. Optional; falls back to a server-default subject when
   * empty.
   *
   * @generated from field: string subject = 3;
   */
  subject: string;

  /**
   * Caller-supplied prose appended above the case link in the email
   * body. Optional; markdown is not interpreted.
   *
   * @generated from field: string note = 4;
   */
  note: string;
};

/**
 * Describes the message api.zyins.v1.EmailCaseRequest.
 * Use `create(EmailCaseRequestSchema)` to create a new message.
 */
export const EmailCaseRequestSchema: GenMessage<EmailCaseRequest> = /*@__PURE__*/
  messageDesc(file_api_zyins_v1_cases, 4);

/**
 * EmailCaseResponse is the 202 body from EmailCase. The send is
 * asynchronous — the response confirms enqueue, not delivery.
 *
 * @generated from message api.zyins.v1.EmailCaseResponse
 */
export type EmailCaseResponse = Message<"api.zyins.v1.EmailCaseResponse"> & {
  /**
   * Resource type discriminator. Wire value: `email`.
   *
   * @generated from field: string object = 1;
   */
  object: string;

  /**
   * True for live mode, false for test mode.
   *
   * @generated from field: bool livemode = 2;
   */
  livemode: boolean;

  /**
   * Unique request identifier.
   *
   * @generated from field: string request_id = 3;
   */
  requestId: string;

  /**
   * Lifecycle state of the enqueued email. Wire value: `queued`.
   *
   * @generated from field: string status = 4;
   */
  status: string;
};

/**
 * Describes the message api.zyins.v1.EmailCaseResponse.
 * Use `create(EmailCaseResponseSchema)` to create a new message.
 */
export const EmailCaseResponseSchema: GenMessage<EmailCaseResponse> = /*@__PURE__*/
  messageDesc(file_api_zyins_v1_cases, 5);

/**
 * CaseDetail is the canonical case resource shape returned by every
 * case RPC. Field numbers 1–3 mirror the platform response envelope;
 * the resource fields begin at 4.
 *
 * @generated from message api.zyins.v1.CaseDetail
 */
export type CaseDetail = Message<"api.zyins.v1.CaseDetail"> & {
  /**
   * Resource type discriminator. Wire value: `case`.
   *
   * @generated from field: string object = 1;
   */
  object: string;

  /**
   * True for live mode, false for test mode.
   *
   * @generated from field: bool livemode = 2;
   */
  livemode: boolean;

  /**
   * Unique request identifier.
   *
   * @generated from field: string request_id = 3;
   */
  requestId: string;

  /**
   * 11-character alphanumeric short hash. Stable identifier for the
   * case across its lifetime.
   *
   * @generated from field: string hash = 4;
   */
  hash: string;

  /**
   * Canonical agent-facing URL: `https://bestplanpro.com/?case=<hash>`.
   * Provided as a convenience so callers do not reconstruct it.
   *
   * @generated from field: string url = 5;
   */
  url: string;

  /**
   * True when the case carries cached evaluation results that viewers
   * see verbatim rather than re-running the engine.
   *
   * @generated from field: bool readonly = 6;
   */
  readonly: boolean;

  /**
   * RFC 3339 creation timestamp.
   *
   * @generated from field: string created_at = 7;
   */
  createdAt: string;

  /**
   * The original applicant inputs, returned only by GetCase. Empty on
   * CreateCase and ListCases responses to keep payloads compact.
   *
   * @generated from field: google.protobuf.Value input = 8;
   */
  input?: Value | undefined;

  /**
   * The evaluation results stored with the case, returned only by
   * GetCase when the case is readonly. Empty otherwise.
   *
   * @generated from field: google.protobuf.Value results = 9;
   */
  results?: Value | undefined;

  /**
   * The product slugs the case was evaluated against. Returned by
   * GetCase; empty on CreateCase and ListCases responses.
   *
   * @generated from field: repeated string products = 10;
   */
  products: string[];
};

/**
 * Describes the message api.zyins.v1.CaseDetail.
 * Use `create(CaseDetailSchema)` to create a new message.
 */
export const CaseDetailSchema: GenMessage<CaseDetail> = /*@__PURE__*/
  messageDesc(file_api_zyins_v1_cases, 6);

/**
 * CasesService groups every case lifecycle operation exposed on
 * `zyins.isaapi.com`. RPCs map 1:1 to HTTP endpoints via the
 * `google.api.http` annotations below. Authentication is BearerAuth on
 * every RPC, scoped to the token's account; cross-account access is
 * rejected at the store layer with `not_found` (the same shape callers
 * see for hashes that do not exist — never `forbidden`, which would leak
 * existence).
 *
 * @generated from service api.zyins.v1.CasesService
 */
export const CasesService: GenService<{
  /**
   * CreateCase persists a case snapshot and returns its short hash.
   * Idempotent on the canonical content hash: identical inputs return
   * the existing hash without creating a duplicate row.
   *
   * @generated from rpc api.zyins.v1.CasesService.CreateCase
   */
  createCase: {
    methodKind: "unary";
    input: typeof CreateCaseRequestSchema;
    output: typeof CaseDetailSchema;
  },
  /**
   * GetCase returns a single case by short hash. Filters by the calling
   * account; cases owned by other accounts are reported as `not_found`.
   *
   * @generated from rpc api.zyins.v1.CasesService.GetCase
   */
  getCase: {
    methodKind: "unary";
    input: typeof GetCaseRequestSchema;
    output: typeof CaseDetailSchema;
  },
  /**
   * ListCases returns the calling account's cases in descending creation
   * order. Cursor-paginated per ADR-024.
   *
   * @generated from rpc api.zyins.v1.CasesService.ListCases
   */
  listCases: {
    methodKind: "unary";
    input: typeof ListCasesRequestSchema;
    output: typeof ListCasesResponseSchema;
  },
  /**
   * EmailCase sends a stored case to a recipient via the platform's
   * email transport. The body of the email is the rendered case link
   * plus an optional caller-supplied note. Idempotent on
   * `Idempotency-Key`.
   *
   * @generated from rpc api.zyins.v1.CasesService.EmailCase
   */
  emailCase: {
    methodKind: "unary";
    input: typeof EmailCaseRequestSchema;
    output: typeof EmailCaseResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_zyins_v1_cases, 0);

