// Package api.zyins.v1 contains the canonical protobuf definitions for the
// ZyINS Unified API (see /services/zyins, historically go/zyins). Under
// ADR-016 these protos are the source of truth; the OpenAPI YAML consumed
// by ReadMe is regenerated from them.
//
// common.proto holds the shared envelope and the zyins-specific
// cross-resource enumerations. Cross-service types (ProblemDetails,
// ErrorCode, Scope, the health probe contract) live in
// `api/isa/v1/common.proto` and `api/isa/v1/health.proto`; sibling protos
// should import those files directly when they reference shared types.

// @generated by protoc-gen-es v2.2.4 with parameter "target=ts"
// @generated from file api/zyins/v1/common.proto (package api.zyins.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Value } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/zyins/v1/common.proto.
 */
export const file_api_zyins_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChlhcGkvenlpbnMvdjEvY29tbW9uLnByb3RvEgxhcGkuenlpbnMudjEiZgoIRW52ZWxvcGUSDgoGb2JqZWN0GAEgASgJEhAKCGxpdmVtb2RlGAIgASgIEhIKCnJlcXVlc3RfaWQYAyABKAkSJAoEZGF0YRgEIAEoCzIWLmdvb2dsZS5wcm90b2J1Zi5WYWx1ZSpECgZHZW5kZXISFgoSR0VOREVSX1VOU1BFQ0lGSUVEEAASDwoLR0VOREVSX01BTEUQARIRCg1HRU5ERVJfRkVNQUxFEAIqkQEKC1Rva2VuU3RhdHVzEhwKGFRPS0VOX1NUQVRVU19VTlNQRUNJRklFRBAAEhcKE1RPS0VOX1NUQVRVU19BQ1RJVkUQARIYChRUT0tFTl9TVEFUVVNfUkVWT0tFRBACEhgKFFRPS0VOX1NUQVRVU19FWFBJUkVEEAMSFwoTVE9LRU5fU1RBVFVTX0JBTk5FRBAEKoMBCg1BY2NvdW50U3RhdHVzEh4KGkFDQ09VTlRfU1RBVFVTX1VOU1BFQ0lGSUVEEAASGQoVQUNDT1VOVF9TVEFUVVNfQUNUSVZFEAESHAoYQUNDT1VOVF9TVEFUVVNfU1VTUEVOREVEEAISGQoVQUNDT1VOVF9TVEFUVVNfQ0xPU0VEEAMqggEKDUxpY2Vuc2VTdGF0dXMSHgoaTElDRU5TRV9TVEFUVVNfVU5TUEVDSUZJRUQQABIYChRMSUNFTlNFX1NUQVRVU19WQUxJRBABEhoKFkxJQ0VOU0VfU1RBVFVTX0lOVkFMSUQQAhIbChdMSUNFTlNFX1NUQVRVU19JTkFDVElWRRADKqcBCgxQcm9kdWN0Q2xhc3MSHQoZUFJPRFVDVF9DTEFTU19VTlNQRUNJRklFRBAAEhUKEVBST0RVQ1RfQ0xBU1NfRkVYEAESFgoSUFJPRFVDVF9DTEFTU19URVJNEAISGAoUUFJPRFVDVF9DTEFTU19NRURTVVAQAxIZChVQUk9EVUNUX0NMQVNTX1BSRU5FRUQQBBIUChBQUk9EVUNUX0NMQVNTX1dMEAUqsQEKEERlYXRoQmVuZWZpdFJhbmsSIgoeREVBVEhfQkVORUZJVF9SQU5LX1VOU1BFQ0lGSUVEEAASIAocREVBVEhfQkVORUZJVF9SQU5LX0lNTUVESUFURRABEh0KGURFQVRIX0JFTkVGSVRfUkFOS19HUkFERUQQAhIaChZERUFUSF9CRU5FRklUX1JBTktfUk9QEAMSHAoYREVBVEhfQkVORUZJVF9SQU5LX09USEVSEAQqYwoJUXVvdGVUeXBlEhoKFlFVT1RFX1RZUEVfVU5TUEVDSUZJRUQQABIbChdRVU9URV9UWVBFX0ZBQ0VfQU1PVU5UUxABEh0KGVFVT1RFX1RZUEVfTU9OVEhMWV9CVURHRVQQAkLFAQoQY29tLmFwaS56eWlucy52MUILQ29tbW9uUHJvdG9QAVpKZ2l0aHViLmNvbS9Tb2Z0d2FyZS1BdXRvbWF0aW9uLUhvbGRpbmdzLUxMQy9zZGsvenlpbnMvYXBpL3p5aW5zL3YxO3p5aW5zdjGiAgNBWliqAhNJc2FTZGsuWnlJTlMuQXBpLlYxygIQU2FoXFp5SU5TXEFwaVxWMeICFVNhaFxaeUlOU1xBcGlcVjFcTWV0YeoCDkFwaTo6WnlpbnM6OlYxYgZwcm90bzM", [file_google_protobuf_struct]);

/**
 * Envelope is the standard response wrapper per the response-envelope
 * contract. Every success response carries `object`, `livemode`, and
 * `request_id`; resource-specific bodies live in a typed `data` field on
 * each response message (not this shared type — proto does not inherit).
 * This message exists for documentation of the contract; concrete
 * responses duplicate the three fields explicitly so each has a typed
 * `data` shape rather than a `google.protobuf.Any`.
 *
 * @generated from message api.zyins.v1.Envelope
 */
export type Envelope = Message<"api.zyins.v1.Envelope"> & {
  /**
   * Resource type discriminator. Concrete values depend on the endpoint
   * (e.g. "quote_result", "license", "token").
   *
   * @generated from field: string object = 1;
   */
  object: string;

  /**
   * True in production; false for test-mode responses.
   *
   * @generated from field: bool livemode = 2;
   */
  livemode: boolean;

  /**
   * Unique request identifier; echoed into all log lines for the request.
   *
   * @generated from field: string request_id = 3;
   */
  requestId: string;

  /**
   * Endpoint-specific payload. Concrete responses replace this with a
   * typed message; it appears here only to document the envelope shape.
   *
   * @generated from field: google.protobuf.Value data = 4;
   */
  data?: Value;
};

/**
 * Describes the message api.zyins.v1.Envelope.
 * Use `create(EnvelopeSchema)` to create a new message.
 */
export const EnvelopeSchema: GenMessage<Envelope> = /*@__PURE__*/
  messageDesc(file_api_zyins_v1_common, 0);

/**
 * Gender captures biological sex for underwriting. Canonical wire values
 * are lowercase full words (`male`, `female`) per ADR-012. The server
 * normalizes legacy inputs (`M`, `F`, `Male`) to canonical values in
 * responses.
 *
 * @generated from enum api.zyins.v1.Gender
 */
export enum Gender {
  /**
   * Default zero value. Never emitted by the server.
   *
   * @generated from enum value: GENDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Male biological sex for underwriting (wire value: `male`).
   *
   * @generated from enum value: GENDER_MALE = 1;
   */
  MALE = 1,

  /**
   * Female biological sex for underwriting (wire value: `female`).
   *
   * @generated from enum value: GENDER_FEMALE = 2;
   */
  FEMALE = 2,
}

/**
 * Describes the enum api.zyins.v1.Gender.
 */
export const GenderSchema: GenEnum<Gender> = /*@__PURE__*/
  enumDesc(file_api_zyins_v1_common, 0);

/**
 * TokenStatus is the API token lifecycle state per ADR-012.
 *
 * @generated from enum api.zyins.v1.TokenStatus
 */
export enum TokenStatus {
  /**
   * Default zero value. Never emitted by the server.
   *
   * @generated from enum value: TOKEN_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Token is usable (wire: `active`).
   *
   * @generated from enum value: TOKEN_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * Token was intentionally terminated (wire: `revoked`). Permanent.
   *
   * @generated from enum value: TOKEN_STATUS_REVOKED = 2;
   */
  REVOKED = 2,

  /**
   * Token aged out of its validity window (wire: `expired`). Permanent.
   *
   * @generated from enum value: TOKEN_STATUS_EXPIRED = 3;
   */
  EXPIRED = 3,

  /**
   * Token was permanently banned by an administrator (wire: `banned`).
   * Unlike revoked, a banned token can never be reinstated.
   *
   * @generated from enum value: TOKEN_STATUS_BANNED = 4;
   */
  BANNED = 4,
}

/**
 * Describes the enum api.zyins.v1.TokenStatus.
 */
export const TokenStatusSchema: GenEnum<TokenStatus> = /*@__PURE__*/
  enumDesc(file_api_zyins_v1_common, 1);

/**
 * AccountStatus is the account lifecycle state per ADR-012.
 *
 * @generated from enum api.zyins.v1.AccountStatus
 */
export enum AccountStatus {
  /**
   * Default zero value. Never emitted by the server.
   *
   * @generated from enum value: ACCOUNT_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Account is in normal operation (wire: `active`).
   *
   * @generated from enum value: ACCOUNT_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * Reversible admin hold (wire: `suspended`).
   *
   * @generated from enum value: ACCOUNT_STATUS_SUSPENDED = 2;
   */
  SUSPENDED = 2,

  /**
   * Permanent admin closure; archival only (wire: `closed`).
   *
   * @generated from enum value: ACCOUNT_STATUS_CLOSED = 3;
   */
  CLOSED = 3,
}

/**
 * Describes the enum api.zyins.v1.AccountStatus.
 */
export const AccountStatusSchema: GenEnum<AccountStatus> = /*@__PURE__*/
  enumDesc(file_api_zyins_v1_common, 2);

/**
 * LicenseStatus is the license validation state.
 *
 * @generated from enum api.zyins.v1.LicenseStatus
 */
export enum LicenseStatus {
  /**
   * Default zero value. Never emitted by the server.
   *
   * @generated from enum value: LICENSE_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * License is authenticated and currently usable (wire: `valid`).
   *
   * @generated from enum value: LICENSE_STATUS_VALID = 1;
   */
  VALID = 1,

  /**
   * Credentials do not match a known license (wire: `invalid`).
   *
   * @generated from enum value: LICENSE_STATUS_INVALID = 2;
   */
  INVALID = 2,

  /**
   * License exists but is not currently usable (wire: `inactive`).
   *
   * @generated from enum value: LICENSE_STATUS_INACTIVE = 3;
   */
  INACTIVE = 3,
}

/**
 * Describes the enum api.zyins.v1.LicenseStatus.
 */
export const LicenseStatusSchema: GenEnum<LicenseStatus> = /*@__PURE__*/
  enumDesc(file_api_zyins_v1_common, 3);

/**
 * ProductClass is the insurance product family classification.
 *
 * @generated from enum api.zyins.v1.ProductClass
 */
export enum ProductClass {
  /**
   * Default zero value. Never emitted by the server.
   *
   * @generated from enum value: PRODUCT_CLASS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Final expense (wire: `fex`).
   *
   * @generated from enum value: PRODUCT_CLASS_FEX = 1;
   */
  FEX = 1,

  /**
   * Term life (wire: `term`).
   *
   * @generated from enum value: PRODUCT_CLASS_TERM = 2;
   */
  TERM = 2,

  /**
   * Medicare supplement (wire: `medsup`).
   *
   * @generated from enum value: PRODUCT_CLASS_MEDSUP = 3;
   */
  MEDSUP = 3,

  /**
   * Pre-need funeral (wire: `preneed`).
   *
   * @generated from enum value: PRODUCT_CLASS_PRENEED = 4;
   */
  PRENEED = 4,

  /**
   * Whole life (wire: `wl`).
   *
   * @generated from enum value: PRODUCT_CLASS_WL = 5;
   */
  WL = 5,
}

/**
 * Describes the enum api.zyins.v1.ProductClass.
 */
export const ProductClassSchema: GenEnum<ProductClass> = /*@__PURE__*/
  enumDesc(file_api_zyins_v1_common, 4);

/**
 * DeathBenefitRank is the underwriting rank category.
 *
 * @generated from enum api.zyins.v1.DeathBenefitRank
 */
export enum DeathBenefitRank {
  /**
   * Default zero value. Never emitted by the server.
   *
   * @generated from enum value: DEATH_BENEFIT_RANK_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Policy takes effect immediately (wire: `immediate`).
   *
   * @generated from enum value: DEATH_BENEFIT_RANK_IMMEDIATE = 1;
   */
  IMMEDIATE = 1,

  /**
   * Waiting period applies (wire: `graded`).
   *
   * @generated from enum value: DEATH_BENEFIT_RANK_GRADED = 2;
   */
  GRADED = 2,

  /**
   * Return of premium (wire: `rop`).
   *
   * @generated from enum value: DEATH_BENEFIT_RANK_ROP = 3;
   */
  ROP = 3,

  /**
   * Remaining classifications (wire: `other`).
   *
   * @generated from enum value: DEATH_BENEFIT_RANK_OTHER = 4;
   */
  OTHER = 4,
}

/**
 * Describes the enum api.zyins.v1.DeathBenefitRank.
 */
export const DeathBenefitRankSchema: GenEnum<DeathBenefitRank> = /*@__PURE__*/
  enumDesc(file_api_zyins_v1_common, 5);

/**
 * QuoteType is the quote computation mode.
 *
 * @generated from enum api.zyins.v1.QuoteType
 */
export enum QuoteType {
  /**
   * Default zero value. Never emitted by the server.
   *
   * @generated from enum value: QUOTE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Compute premiums for given face-value amounts (wire: `face_amounts`).
   *
   * @generated from enum value: QUOTE_TYPE_FACE_AMOUNTS = 1;
   */
  FACE_AMOUNTS = 1,

  /**
   * Compute coverage achievable for a given monthly budget (wire: `monthly_budget`).
   *
   * @generated from enum value: QUOTE_TYPE_MONTHLY_BUDGET = 2;
   */
  MONTHLY_BUDGET = 2,
}

/**
 * Describes the enum api.zyins.v1.QuoteType.
 */
export const QuoteTypeSchema: GenEnum<QuoteType> = /*@__PURE__*/
  enumDesc(file_api_zyins_v1_common, 6);

