// email.proto defines the account-scoped transactional email enqueue
// surface for the ZyINS Unified API. Mounted at
// `zyins.isaapi.com/v1/email/enqueue`.
//
// The send path is asynchronous: the handler validates and persists the
// payload to `email_queue`, and a worker drains the queue through the
// configured transport (Postmark for credentials/transactional, Resend
// for rapidsign signer notifications). The response confirms enqueue,
// not delivery.
//
// Per-account isolation: every row carries the calling account; cross-
// account queue inspection is not exposed.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file api/zyins/v1/email.proto (package api.zyins.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { Value } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/zyins/v1/email.proto.
 */
export const file_api_zyins_v1_email: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGkvenlpbnMvdjEvZW1haWwucHJvdG8SDGFwaS56eWlucy52MSLHAQoTRW5xdWV1ZUVtYWlsUmVxdWVzdBIKCgJ0bxgBIAEoCRIPCgdzdWJqZWN0GAIgASgJEgwKBGJvZHkYAyABKAkSEAoIdGVtcGxhdGUYBCABKAkSLQoNdGVtcGxhdGVfZGF0YRgFIAEoCzIWLmdvb2dsZS5wcm90b2J1Zi5WYWx1ZRIQCghyZXBseV90bxgGIAEoCRIyCgthdHRhY2htZW50cxgHIAMoCzIdLmFwaS56eWlucy52MS5FbWFpbEF0dGFjaG1lbnQiNAoPRW1haWxBdHRhY2htZW50EhAKCGZpbGVuYW1lGAEgASgJEg8KB2NvbnRlbnQYAiABKAkiXAoURW5xdWV1ZUVtYWlsUmVzcG9uc2USDgoGb2JqZWN0GAEgASgJEhAKCGxpdmVtb2RlGAIgASgIEhIKCnJlcXVlc3RfaWQYAyABKAkSDgoGc3RhdHVzGAQgASgJMoMBCgxFbWFpbFNlcnZpY2UScwoMRW5xdWV1ZUVtYWlsEiEuYXBpLnp5aW5zLnYxLkVucXVldWVFbWFpbFJlcXVlc3QaIi5hcGkuenlpbnMudjEuRW5xdWV1ZUVtYWlsUmVzcG9uc2UiHILT5JMCFjoBKiIRL3YxL2VtYWlsL2VucXVldWVCxAEKEGNvbS5hcGkuenlpbnMudjFCCkVtYWlsUHJvdG9QAVpKZ2l0aHViLmNvbS9Tb2Z0d2FyZS1BdXRvbWF0aW9uLUhvbGRpbmdzLUxMQy9zZGsvenlpbnMvYXBpL3p5aW5zL3YxO3p5aW5zdjGiAgNBWliqAhNJc2FTZGsuWnlJTlMuQXBpLlYxygIQU2FoXFp5SU5TXEFwaVxWMeICFVNhaFxaeUlOU1xBcGlcVjFcTWV0YeoCDkFwaTo6WnlpbnM6OlYxYgZwcm90bzM", [file_google_api_annotations, file_google_protobuf_struct]);

/**
 * EnqueueEmailRequest is the body for POST /v1/email/enqueue.
 *
 * The server constructs the canonical `From` header from a verified
 * brand domain — callers cannot set it. `template`/`template_data` are
 * reserved for future server-rendered templates; current callers
 * supply the rendered HTML in `body`.
 *
 * @generated from message api.zyins.v1.EnqueueEmailRequest
 */
export type EnqueueEmailRequest = Message<"api.zyins.v1.EnqueueEmailRequest"> & {
  /**
   * Recipient email address. Required; RFC 5322 valid.
   *
   * @generated from field: string to = 1;
   */
  to: string;

  /**
   * Subject line. Required; non-empty after trim.
   *
   * @generated from field: string subject = 2;
   */
  subject: string;

  /**
   * Rendered HTML email body. Required. The transport sends as
   * `text/html`; clients that need a plaintext alternative should
   * include it server-side once template support ships.
   *
   * @generated from field: string body = 3;
   */
  body: string;

  /**
   * Server-rendered template identifier. Reserved for future use;
   * ignored by current handlers. Optional.
   *
   * @generated from field: string template = 4;
   */
  template: string;

  /**
   * Substitution data for the template. Reserved for future use;
   * ignored by current handlers. Optional.
   *
   * @generated from field: google.protobuf.Value template_data = 5;
   */
  templateData?: Value | undefined;

  /**
   * Address to set as `Reply-To`. Optional; falls back to the
   * configured no-reply when empty.
   *
   * @generated from field: string reply_to = 6;
   */
  replyTo: string;

  /**
   * Attachments to include on the message. Total decoded size is
   * capped per the platform's transport limit; oversize attachments
   * are rejected at enqueue time. Optional.
   *
   * @generated from field: repeated api.zyins.v1.EmailAttachment attachments = 7;
   */
  attachments: EmailAttachment[];
};

/**
 * Describes the message api.zyins.v1.EnqueueEmailRequest.
 * Use `create(EnqueueEmailRequestSchema)` to create a new message.
 */
export const EnqueueEmailRequestSchema: GenMessage<EnqueueEmailRequest> = /*@__PURE__*/
  messageDesc(file_api_zyins_v1_email, 0);

/**
 * EmailAttachment is a single base64-encoded file to include with the
 * outbound email. The transport infers content-type from the filename
 * extension; explicit MIME types are not accepted from clients.
 *
 * @generated from message api.zyins.v1.EmailAttachment
 */
export type EmailAttachment = Message<"api.zyins.v1.EmailAttachment"> & {
  /**
   * Display filename. Must not contain path separators, null bytes,
   * CR/LF, or a leading dot. Required.
   *
   * @generated from field: string filename = 1;
   */
  filename: string;

  /**
   * Base64-encoded file bytes. Required. Decoded size must fit within
   * the per-attachment ceiling enforced at enqueue time.
   *
   * @generated from field: string content = 2;
   */
  content: string;
};

/**
 * Describes the message api.zyins.v1.EmailAttachment.
 * Use `create(EmailAttachmentSchema)` to create a new message.
 */
export const EmailAttachmentSchema: GenMessage<EmailAttachment> = /*@__PURE__*/
  messageDesc(file_api_zyins_v1_email, 1);

/**
 * EnqueueEmailResponse is the 202 body from EnqueueEmail.
 *
 * @generated from message api.zyins.v1.EnqueueEmailResponse
 */
export type EnqueueEmailResponse = Message<"api.zyins.v1.EnqueueEmailResponse"> & {
  /**
   * Resource type discriminator. Wire value: `email`.
   *
   * @generated from field: string object = 1;
   */
  object: string;

  /**
   * True for live mode, false for test mode.
   *
   * @generated from field: bool livemode = 2;
   */
  livemode: boolean;

  /**
   * Unique request identifier.
   *
   * @generated from field: string request_id = 3;
   */
  requestId: string;

  /**
   * Lifecycle state of the enqueued email. Wire value: `queued`.
   *
   * @generated from field: string status = 4;
   */
  status: string;
};

/**
 * Describes the message api.zyins.v1.EnqueueEmailResponse.
 * Use `create(EnqueueEmailResponseSchema)` to create a new message.
 */
export const EnqueueEmailResponseSchema: GenMessage<EnqueueEmailResponse> = /*@__PURE__*/
  messageDesc(file_api_zyins_v1_email, 2);

/**
 * EmailService groups the enqueue surface for transactional email.
 * Authentication is BearerAuth; every operation is account-scoped.
 *
 * @generated from service api.zyins.v1.EmailService
 */
export const EmailService: GenService<{
  /**
   * EnqueueEmail validates an outbound email and persists it to the
   * queue table. Returns 202 with the queued envelope on success.
   *
   * @generated from rpc api.zyins.v1.EmailService.EnqueueEmail
   */
  enqueueEmail: {
    methodKind: "unary";
    input: typeof EnqueueEmailRequestSchema;
    output: typeof EnqueueEmailResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_zyins_v1_email, 0);

