<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/isa/v1/common.proto

namespace Sah\Isa\Api\V1;

use UnexpectedValueException;

/**
 * ErrorCode enumerates the stable error codes consumers may switch on.
 * Values are lowercase snake_case at the wire level. Additions are
 * non-breaking; renames are forbidden.
 * This is the union of every error code previously defined per service.
 * Values 0-8 matched both legacy catalogs. From 9 onward the numeric
 * assignments follow the former ZyINS layout (including LICENSE_LOCKED at
 * 9). Legacy RapidSign emitted RATE_LIMIT_EXCEEDED as 9 and
 * NOT_IMPLEMENTED as 10; those semantics now wire as 10 and 15
 * respectively. Pre-1.0 consolidation: treat any cross-service numeric
 * error code migration as an explicit consumer update, not a silent
 * rename. New services must add missing codes here rather than locally.
 *
 * Protobuf type <code>api.isa.v1.ErrorCode</code>
 */
class ErrorCode
{
    /**
     * Default zero value. Never emitted by the server; indicates a proto
     * deserialization defect on the client side.
     *
     * Generated from protobuf enum <code>ERROR_CODE_UNSPECIFIED = 0;</code>
     */
    const ERROR_CODE_UNSPECIFIED = 0;
    /**
     * Authentication required or credentials invalid.
     *
     * Generated from protobuf enum <code>ERROR_CODE_UNAUTHORIZED = 1;</code>
     */
    const ERROR_CODE_UNAUTHORIZED = 1;
    /**
     * Bearer token or license has expired. Client should refresh.
     *
     * Generated from protobuf enum <code>ERROR_CODE_TOKEN_EXPIRED = 2;</code>
     */
    const ERROR_CODE_TOKEN_EXPIRED = 2;
    /**
     * Bearer token or license signature does not validate.
     *
     * Generated from protobuf enum <code>ERROR_CODE_INVALID_TOKEN = 3;</code>
     */
    const ERROR_CODE_INVALID_TOKEN = 3;
    /**
     * Authenticated but lacking scope for this operation.
     *
     * Generated from protobuf enum <code>ERROR_CODE_FORBIDDEN = 4;</code>
     */
    const ERROR_CODE_FORBIDDEN = 4;
    /**
     * Resource does not exist or is not visible to the caller.
     *
     * Generated from protobuf enum <code>ERROR_CODE_NOT_FOUND = 5;</code>
     */
    const ERROR_CODE_NOT_FOUND = 5;
    /**
     * HTTP method not allowed on this path.
     *
     * Generated from protobuf enum <code>ERROR_CODE_METHOD_NOT_ALLOWED = 6;</code>
     */
    const ERROR_CODE_METHOD_NOT_ALLOWED = 6;
    /**
     * State conflict (e.g. already activated, already revoked,
     * document already signed).
     *
     * Generated from protobuf enum <code>ERROR_CODE_CONFLICT = 7;</code>
     */
    const ERROR_CODE_CONFLICT = 7;
    /**
     * Request body failed schema or domain validation. `param` is set.
     *
     * Generated from protobuf enum <code>ERROR_CODE_VALIDATION_ERROR = 8;</code>
     */
    const ERROR_CODE_VALIDATION_ERROR = 8;
    /**
     * License is locked (too many device registrations or admin action).
     *
     * Generated from protobuf enum <code>ERROR_CODE_LICENSE_LOCKED = 9;</code>
     */
    const ERROR_CODE_LICENSE_LOCKED = 9;
    /**
     * Rate limit exceeded. `Retry-After` header is set.
     *
     * Generated from protobuf enum <code>ERROR_CODE_RATE_LIMIT_EXCEEDED = 10;</code>
     */
    const ERROR_CODE_RATE_LIMIT_EXCEEDED = 10;
    /**
     * Unhandled server fault. Request ID identifies the log entry.
     *
     * Generated from protobuf enum <code>ERROR_CODE_INTERNAL_ERROR = 11;</code>
     */
    const ERROR_CODE_INTERNAL_ERROR = 11;
    /**
     * Upstream dependency returned an unusable response.
     *
     * Generated from protobuf enum <code>ERROR_CODE_BAD_GATEWAY = 12;</code>
     */
    const ERROR_CODE_BAD_GATEWAY = 12;
    /**
     * Upstream dependency did not respond within the budget.
     *
     * Generated from protobuf enum <code>ERROR_CODE_GATEWAY_TIMEOUT = 13;</code>
     */
    const ERROR_CODE_GATEWAY_TIMEOUT = 13;
    /**
     * Service is intentionally unavailable (draining, maintenance).
     *
     * Generated from protobuf enum <code>ERROR_CODE_SERVICE_UNAVAILABLE = 14;</code>
     */
    const ERROR_CODE_SERVICE_UNAVAILABLE = 14;
    /**
     * Capability not yet implemented (e.g. PDF renderer not configured).
     *
     * Generated from protobuf enum <code>ERROR_CODE_NOT_IMPLEMENTED = 15;</code>
     */
    const ERROR_CODE_NOT_IMPLEMENTED = 15;

    private static $valueToName = [
        self::ERROR_CODE_UNSPECIFIED => 'ERROR_CODE_UNSPECIFIED',
        self::ERROR_CODE_UNAUTHORIZED => 'ERROR_CODE_UNAUTHORIZED',
        self::ERROR_CODE_TOKEN_EXPIRED => 'ERROR_CODE_TOKEN_EXPIRED',
        self::ERROR_CODE_INVALID_TOKEN => 'ERROR_CODE_INVALID_TOKEN',
        self::ERROR_CODE_FORBIDDEN => 'ERROR_CODE_FORBIDDEN',
        self::ERROR_CODE_NOT_FOUND => 'ERROR_CODE_NOT_FOUND',
        self::ERROR_CODE_METHOD_NOT_ALLOWED => 'ERROR_CODE_METHOD_NOT_ALLOWED',
        self::ERROR_CODE_CONFLICT => 'ERROR_CODE_CONFLICT',
        self::ERROR_CODE_VALIDATION_ERROR => 'ERROR_CODE_VALIDATION_ERROR',
        self::ERROR_CODE_LICENSE_LOCKED => 'ERROR_CODE_LICENSE_LOCKED',
        self::ERROR_CODE_RATE_LIMIT_EXCEEDED => 'ERROR_CODE_RATE_LIMIT_EXCEEDED',
        self::ERROR_CODE_INTERNAL_ERROR => 'ERROR_CODE_INTERNAL_ERROR',
        self::ERROR_CODE_BAD_GATEWAY => 'ERROR_CODE_BAD_GATEWAY',
        self::ERROR_CODE_GATEWAY_TIMEOUT => 'ERROR_CODE_GATEWAY_TIMEOUT',
        self::ERROR_CODE_SERVICE_UNAVAILABLE => 'ERROR_CODE_SERVICE_UNAVAILABLE',
        self::ERROR_CODE_NOT_IMPLEMENTED => 'ERROR_CODE_NOT_IMPLEMENTED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

