<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/isa/v1/health.proto

namespace Sah\Isa\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * GetHealthRequest is the empty request body for GET /health.
 *
 * Generated from protobuf message <code>api.isa.v1.GetHealthRequest</code>
 */
class GetHealthRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Sah\Isa\Api\V1\Meta\Health::initOnce();
        parent::__construct($data);
    }

}

