<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/isa/v1/health.proto

namespace Sah\Isa\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * HealthResponse reports liveness (in-process state only). Emitted with
 * HTTP 200; a failing probe returns ProblemDetails on HTTP 503 instead.
 *
 * Generated from protobuf message <code>api.isa.v1.HealthResponse</code>
 */
class HealthResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Overall liveness status. On HTTP 200 this is always `SERVING`.
     *
     * Generated from protobuf field <code>.api.isa.v1.ServingStatus status = 1 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Semantic version of the running binary (e.g. `1.42.0`). Matches
     * the git tag when deployed from a release; empty for local builds.
     *
     * Generated from protobuf field <code>string version = 2 [json_name = "version"];</code>
     */
    protected $version = '';
    /**
     * Full git commit SHA the binary was built from. Echoed into logs
     * and used by support to correlate behaviour with a revision.
     *
     * Generated from protobuf field <code>string build_sha = 3 [json_name = "buildSha"];</code>
     */
    protected $build_sha = '';
    /**
     * Wall-clock time at which the process started accepting requests.
     * Paired with the current time to compute uptime client-side.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 4 [json_name = "startedAt"];</code>
     */
    protected $started_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *           Overall liveness status. On HTTP 200 this is always `SERVING`.
     *     @type string $version
     *           Semantic version of the running binary (e.g. `1.42.0`). Matches
     *           the git tag when deployed from a release; empty for local builds.
     *     @type string $build_sha
     *           Full git commit SHA the binary was built from. Echoed into logs
     *           and used by support to correlate behaviour with a revision.
     *     @type \Google\Protobuf\Timestamp $started_at
     *           Wall-clock time at which the process started accepting requests.
     *           Paired with the current time to compute uptime client-side.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\Isa\Api\V1\Meta\Health::initOnce();
        parent::__construct($data);
    }

    /**
     * Overall liveness status. On HTTP 200 this is always `SERVING`.
     *
     * Generated from protobuf field <code>.api.isa.v1.ServingStatus status = 1 [json_name = "status"];</code>
     * @return int one of the values in {@see \Sah\Isa\Api\V1\ServingStatus}
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Overall liveness status. On HTTP 200 this is always `SERVING`.
     *
     * Generated from protobuf field <code>.api.isa.v1.ServingStatus status = 1 [json_name = "status"];</code>
     * @param int $var one of the values in {@see \Sah\Isa\Api\V1\ServingStatus}
     * @return $this
     */
    public function setStatus(int $var)
    {
        GPBUtil::checkEnum($var, \Sah\Isa\Api\V1\ServingStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Semantic version of the running binary (e.g. `1.42.0`). Matches
     * the git tag when deployed from a release; empty for local builds.
     *
     * Generated from protobuf field <code>string version = 2 [json_name = "version"];</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Semantic version of the running binary (e.g. `1.42.0`). Matches
     * the git tag when deployed from a release; empty for local builds.
     *
     * Generated from protobuf field <code>string version = 2 [json_name = "version"];</code>
     * @param string $var
     * @return $this
     */
    public function setVersion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->version = $var;

        return $this;
    }

    /**
     * Full git commit SHA the binary was built from. Echoed into logs
     * and used by support to correlate behaviour with a revision.
     *
     * Generated from protobuf field <code>string build_sha = 3 [json_name = "buildSha"];</code>
     * @return string
     */
    public function getBuildSha()
    {
        return $this->build_sha;
    }

    /**
     * Full git commit SHA the binary was built from. Echoed into logs
     * and used by support to correlate behaviour with a revision.
     *
     * Generated from protobuf field <code>string build_sha = 3 [json_name = "buildSha"];</code>
     * @param string $var
     * @return $this
     */
    public function setBuildSha(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->build_sha = $var;

        return $this;
    }

    /**
     * Wall-clock time at which the process started accepting requests.
     * Paired with the current time to compute uptime client-side.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 4 [json_name = "startedAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartedAt()
    {
        return $this->started_at;
    }

    public function hasStartedAt()
    {
        return isset($this->started_at);
    }

    public function clearStartedAt()
    {
        unset($this->started_at);
    }

    /**
     * Wall-clock time at which the process started accepting requests.
     * Paired with the current time to compute uptime client-side.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 4 [json_name = "startedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartedAt(\Google\Protobuf\Timestamp|null $var)
    {
        $this->started_at = $var;

        return $this;
    }

}

