<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/isa/v1/common.proto

namespace Sah\Isa\Api\V1;

use UnexpectedValueException;

/**
 * Scope enumerates the bearer-token scopes recognized across the ISA
 * platform. Enum member names gained a `RAPIDSIGN_` prefix so additional
 * services can add scopes without colliding; wire integers for the four
 * RapidSign scopes are unchanged from the legacy `SCOPE_DOCUMENTS_*`
 * assignments. Generated symbol names therefore change — migrate callers
 * when regenerating SDKs.
 *
 * Protobuf type <code>api.isa.v1.Scope</code>
 */
class Scope
{
    /**
     * Default zero value. Never emitted.
     *
     * Generated from protobuf enum <code>SCOPE_UNSPECIFIED = 0;</code>
     */
    const SCOPE_UNSPECIFIED = 0;
    /**
     * `rapidsign:documents:write` — create new documents.
     *
     * Generated from protobuf enum <code>SCOPE_RAPIDSIGN_DOCUMENTS_WRITE = 1;</code>
     */
    const SCOPE_RAPIDSIGN_DOCUMENTS_WRITE = 1;
    /**
     * `rapidsign:documents:read` — fetch signature state and signed PDFs.
     *
     * Generated from protobuf enum <code>SCOPE_RAPIDSIGN_DOCUMENTS_READ = 2;</code>
     */
    const SCOPE_RAPIDSIGN_DOCUMENTS_READ = 2;
    /**
     * `rapidsign:documents:sign` — submit signatures.
     *
     * Generated from protobuf enum <code>SCOPE_RAPIDSIGN_DOCUMENTS_SIGN = 3;</code>
     */
    const SCOPE_RAPIDSIGN_DOCUMENTS_SIGN = 3;
    /**
     * `rapidsign:documents:notify` — send signer notification emails.
     *
     * Generated from protobuf enum <code>SCOPE_RAPIDSIGN_DOCUMENTS_NOTIFY = 4;</code>
     */
    const SCOPE_RAPIDSIGN_DOCUMENTS_NOTIFY = 4;

    private static $valueToName = [
        self::SCOPE_UNSPECIFIED => 'SCOPE_UNSPECIFIED',
        self::SCOPE_RAPIDSIGN_DOCUMENTS_WRITE => 'SCOPE_RAPIDSIGN_DOCUMENTS_WRITE',
        self::SCOPE_RAPIDSIGN_DOCUMENTS_READ => 'SCOPE_RAPIDSIGN_DOCUMENTS_READ',
        self::SCOPE_RAPIDSIGN_DOCUMENTS_SIGN => 'SCOPE_RAPIDSIGN_DOCUMENTS_SIGN',
        self::SCOPE_RAPIDSIGN_DOCUMENTS_NOTIFY => 'SCOPE_RAPIDSIGN_DOCUMENTS_NOTIFY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

