<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/isa/v1/health.proto

namespace Sah\Isa\Api\V1\LivenessResponse;

use UnexpectedValueException;

/**
 * Status enumerates the probe outcomes. Exists inside the message so
 * the wire type is unambiguously scoped to the liveness contract.
 *
 * Protobuf type <code>api.isa.v1.LivenessResponse.Status</code>
 */
class Status
{
    /**
     * Default zero value. Never emitted.
     *
     * Generated from protobuf enum <code>STATUS_UNSPECIFIED = 0;</code>
     */
    const STATUS_UNSPECIFIED = 0;
    /**
     * Process is alive (liveness) or ready to serve traffic (readiness).
     *
     * Generated from protobuf enum <code>STATUS_OK = 1;</code>
     */
    const STATUS_OK = 1;

    private static $valueToName = [
        self::STATUS_UNSPECIFIED => 'STATUS_UNSPECIFIED',
        self::STATUS_OK => 'STATUS_OK',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

