// Public-surface contract guard for the C# SDK.
//
// This file is checked by ``dotnet build`` (with -warnaserror in CI per
// .github/workflows/sdk-csharp.yml). It exists purely as a guard:
// each ``Func<>`` typed reference, each ``typeof()`` probe, and each
// instance-method group conversion asserts that a specific public
// symbol exists with the locked signature. The build fails the
// moment a guarded export is renamed, removed, or has its signature
// drifted.
//
// This complements two pre-existing layers of drift detection:
//
//   1. packages/csharp/PUBLIC_API.txt — snapshot of every public
//      symbol. Captures ANY shape change; regenerated by
//      ``scripts/sdk-public-api.sh regenerate`` and diff-gated by CI
//      (.github/workflows/sdk-public-api.yml). The primary surface
//      guard.
//   2. The mirrored TypeScript contract at
//      packages/ts/src/__contract__.ts (PR #366), which originally
//      introduced this pattern.
//
// This file is the strongest tier: it makes the contract a build
// dependency. A rename never reaches main without Contract.cs
// re-pointing or the build failing.

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

// Alias the top-level ``Isa`` entry type. The name must not be a single
// namespace-root token (e.g. ``IsaSdk``): the generated wire stubs live under
// the ``IsaSdk.*`` root namespace (csharp_namespace in
// shared/schemas/buf.gen.sdk.yaml), and in the mirror publish layout those
// stubs compile alongside this file. A ``using IsaSdk = ...`` alias would then
// collide with that namespace root (CS0576). ``IsaRoot`` cannot collide.
using IsaRoot = global::Isa.Sdk.Isa;
using Isa.Sdk.Account;
using Isa.Sdk.Core;
using Isa.Sdk.Proxy;
using Isa.Sdk.Webhooks;
using Isa.Sdk.Zyins;
using Isa.Sdk.Zyins.Cases;
using Isa.Sdk.Zyins.Options;
using Isa.Sdk.Zyins.Reference;

// Account vs Zyins disambiguation — the cases-shape types exist on
// both namespaces (mirrors of the same wire shape); pin both.
using AccountCases = global::Isa.Sdk.Account.AccountCases;
using ZyinsCases = global::Isa.Sdk.Zyins.CasesSubClient;
using ZyinsCaseCreateRequest = global::Isa.Sdk.Zyins.CaseCreateRequest;
using ZyinsCaseCreateResult = global::Isa.Sdk.Zyins.CaseCreateResult;
using ZyinsEmailEnqueueRequest = global::Isa.Sdk.Zyins.EmailEnqueueRequest;
using ZyinsEmailEnqueueResult = global::Isa.Sdk.Zyins.EmailEnqueueResult;

namespace Isa.Sdk.Internal;

/// <summary>
/// Compile-time pins for the public surface. Static-only; never
/// instantiated, never invoked. Each delegate cast and typeof probe
/// fails the build if the canonical name or signature drifts.
/// </summary>
internal static class Contract
{
    // =====================================================================
    // Tier 1 — Top-level Isa constructor + namespace factories.
    // =====================================================================
    //
    // A rename, signature drift, or removal of any of these fails
    // ``dotnet build`` immediately. The factories are the entry points
    // every integrator uses on first reference.

    private static readonly Func<string?, IsaRoot> _withBearerSingle = IsaRoot.WithBearer;
    private static readonly Func<string, string, IsaRoot> _withKeycode = IsaRoot.WithKeycode;
    private static readonly Func<FormOptions, IsaRoot> _forForm = IsaRoot.ForForm;
    private static readonly Func<IsaRoot> _fromEnv = IsaRoot.FromEnv;

    // ``Authenticate`` exists with overloads; pinning the declaring
    // type ensures the symbol stays reachable. The full overload set
    // is captured by PUBLIC_API.txt.
    private static readonly Type _isaType = typeof(IsaRoot);

    // Namespace accessors on the Isa instance. Pinning via instance
    // property type catches rename and type drift on the field.
    private static ZyInsClient PinZyins(IsaRoot isa) => isa.Zyins;
    private static AccountNamespace PinAccount(IsaRoot isa) => isa.Account;
    private static ProxyNamespace PinProxy(IsaRoot isa) => isa.Proxy;
    private static WebhooksNamespace PinWebhooks(IsaRoot isa) => isa.Webhooks;

    // =====================================================================
    // Tier 1 — Per-surface API-version map.
    // =====================================================================
    //
    // BundledApiVersions exposes the locked-spec per-surface pin map.
    // A type-shape change (e.g. value type drift from IsaApiVersion to
    // string) breaks this line.

    private static readonly IReadOnlyDictionary<string, IsaApiVersion> _bundled =
        BundledApiVersions.Map;

    // =====================================================================
    // Tier 1 — ICaseStorage contract.
    // =====================================================================
    //
    // Every adapter plugged into LicenseOptions / BearerOptions /
    // SessionOptions implements ICaseStorage. The PutResult /
    // CaseRecord round-trip is the wire shape.

    private static readonly Type _caseStorageIface = typeof(ICaseStorage);
    private static readonly Type _caseRecord = typeof(CaseRecord);
    private static readonly Type _putResult = typeof(PutResult);
    private static readonly Type _zeroKnowledgeCaseStorage = typeof(ZeroKnowledgeCaseStorage);

    // =====================================================================
    // Tier 1 — Reference matcher surface.
    // =====================================================================
    //
    // Per locked-spec docs/sdk-syntax-proposal.md §reference: the
    // matcher surface is reachable as
    // ``isa.Zyins.Medications.MatchAsync(text)`` /
    // ``isa.Zyins.Conditions.MatchAsync(text)`` /
    // ``isa.Zyins.Concepts.MatchAsync(text)``. Pin the namespace
    // accessor types — a rename here is the locked-spec break.

    private static MedicationsNamespace PinMedications(ZyInsClient c) => c.Medications;
    private static ConditionsNamespace PinConditions(ZyInsClient c) => c.Conditions;
    private static ConceptsNamespace PinConcepts(ZyInsClient c) => c.Concepts;
    private static ZyinsCases PinCases(ZyInsClient c) => c.Cases;

    // Sort enum members — the documented sort vocabulary on matcher
    // results.
    private const Sort _sortMostCommonFirst = Sort.MostCommonFirst;
    private const Sort _sortAlphabetical = Sort.Alphabetical;

    // =====================================================================
    // Tier 1 — Cases facade methods.
    // =====================================================================
    //
    // Share / Email forward to the legacy sub-client and remain
    // reachable through the canonical names. Save / Recall are the
    // locked top-level verbs (PR #347). Renames here break consumer
    // code; pin via instance-method group conversion to a typed
    // delegate.

    private static Func<ZyinsCaseCreateRequest, CancellationToken, Task<ZyinsCaseCreateResult>>?
        PinCasesShare(ZyinsCases c) => c.ShareAsync;
    private static Func<ZyinsEmailEnqueueRequest, CancellationToken, Task<ZyinsEmailEnqueueResult>>?
        PinCasesEmail(ZyinsCases c) => c.EmailAsync;

    // Locked top-level verbs (PR #347 zero-knowledge envelope).
    private static readonly Type _saveAsyncDeclared = typeof(ZyinsCases);
    private static readonly Type _recallAsyncDeclared = typeof(ZyinsCases);

    // AccountCases — the flat-method shape on isa.account.cases
    // (CreateAsync / GetAsync / ListAsync / EmailAsync). Rename or
    // signature drift breaks the typeof probe.
    private static readonly Type _accountCases = typeof(AccountCases);

    // =====================================================================
    // Tier 1 — Error hierarchy.
    // =====================================================================
    //
    // Renames break ``catch`` clauses in user code. Each documented
    // subclass MUST remain catchable under its canonical name.

    private static readonly Type _isaException = typeof(IsaException);
    private static readonly Type _isaAuthException = typeof(IsaAuthException);
    private static readonly Type _isaLicenseException = typeof(IsaLicenseException);
    private static readonly Type _isaValidationException = typeof(IsaValidationException);
    private static readonly Type _isaRateLimitException = typeof(IsaRateLimitException);
    private static readonly Type _isaConfigException = typeof(IsaConfigException);
    private static readonly Type _isaIdempotencyConflictException =
        typeof(IsaIdempotencyConflictException);

    // =====================================================================
    // Tier 1 — Webhooks namespace.
    // =====================================================================
    //
    // WebhooksNamespace is the placeholder for cross-product webhook
    // helpers; the type's existence is the locked-spec contract today.

    private static readonly Type _webhooksNamespace = typeof(WebhooksNamespace);

    // =====================================================================
    // Tier 1 — Reference adapter surface (rc.1 §2 cutover).
    // =====================================================================
    //
    // Three adapter interfaces — autocorrector, match algorithm, autocomplete
    // algorithm — plus the static factory namespace
    // Isa.Autocorrector.Create(typoMap) and the domain-bound
    // isa.Zyins.Autocorrector / Matcher / AutocompleteAlgorithm properties.

    private static readonly Type _iAutocorrector = typeof(IAutocorrector);
    private static readonly Type _iMatchAlgorithm = typeof(IMatchAlgorithm);
    private static readonly Type _iAutocompleteAlgorithm = typeof(IAutocompleteAlgorithm);
    private static readonly Type _defaultAutocorrector = typeof(DefaultAutocorrector);
    private static readonly Type _defaultMatchAlgorithm = typeof(DefaultMatchAlgorithm);
    private static readonly Type _defaultAutocompleteAlgorithm = typeof(DefaultAutocompleteAlgorithm);
    private static readonly Type _suggestion = typeof(Suggestion);
    private static readonly Type _matchedSpan = typeof(MatchedSpan);
    private static readonly Type _autocorrectOptions = typeof(AutocorrectOptions);
    private static readonly Type _autocompleteOptions = typeof(AutocompleteOptions);

    // Top-level factory: Isa.Autocorrector.Create(typoMap).
    private static readonly Func<IReadOnlyDictionary<string, string>, string?, Action<AutocorrectorAppliedEvent>?, IAutocorrector>
        _autocorrectorCreate = global::Isa.Sdk.Isa.Autocorrector.Create;

    // Domain-bound accessors on isa.Zyins.
    private static IAutocorrector PinAutocorrector(ZyInsClient c) => c.Autocorrector;
    private static IMatchAlgorithm PinMatcher(ZyInsClient c) => c.Matcher;
    private static IAutocompleteAlgorithm PinAutocompleteAlgorithm(ZyInsClient c) => c.AutocompleteAlgorithm;

    // IsaBuilder fluent injection — locked SDK syntax.
    private static readonly Func<IsaBuilder> _isaBuilder = global::Isa.Sdk.Isa.Builder;

    // =====================================================================
    // Tier 1 — Inline-row v3 datasets (rc.1 §1 cutover).
    // =====================================================================

    private static readonly Type _conditionRow = typeof(ConditionRow);
    private static readonly Type _medicationRow = typeof(MedicationRow);
    private static readonly Type _nicotineOptionRow = typeof(NicotineOptionRow);
    private static readonly Type _spellingCorrectionRow = typeof(SpellingCorrectionRow);
    private static readonly Type _inlineMedicationRef = typeof(InlineMedicationRef);
    private static readonly Type _inlineConditionRef = typeof(InlineConditionRef);
    private static readonly Type _datasetBundleV3 = typeof(DatasetBundleV3);
}
