/**
 * Public surface contract — compile-time assertions.
 *
 * This file is checked by `tsc --noEmit` (it lives under `src/**`, included
 * by `tsconfig.json`) and exists purely as a guard. It compiles to nothing
 * at runtime (no value exports). Each `type _<Name>` alias asserts that a
 * specific named export from the public barrel exists with the expected
 * shape; tsc fails the build the moment a guarded export is renamed,
 * removed, or mistyped.
 *
 * This complements two pre-existing layers of drift detection:
 *
 *   1. `packages/ts/PUBLIC_API.txt` — snapshot of every dist `.d.ts` line.
 *      Captures ANY shape change to ANY exported symbol; regenerated by
 *      `scripts/sdk-public-api.sh regenerate` and diff-gated by CI
 *      (`.github/workflows/sdk-public-api.yml`). Picks up additions
 *      automatically. The primary surface guard.
 *
 *   2. `packages/ts/tests/conformance/locked-surface.test.ts` — vitest
 *      type-level assertions citing the locked-spec section per check.
 *      Documents WHY each symbol is locked. (Note: vitest's
 *      `expectTypeOf` is loose by default — it documents intent but does
 *      not enforce until `typecheck.enabled: true` lands; this file is
 *      the tsc-strict tier.)
 *
 * This file's contribution is the strongest tier: assertions that tsc
 * actually fails on. The motivation is the closed-PR #359 class of bug
 * where a facade method snuck in under a SUFFIXED name (e.g. `shareV3`
 * instead of `share`). The snapshot caught the new line, but a diff that
 * only ADDS exports is easy to wave through; a tsc-enforced positive
 * assertion on the canonical name makes that mistake compile-fail at the
 * same instant.
 *
 * Adding to this contract: list a name only after the locked-spec calls
 * for it. The `@ts-expect-error` markers on future symbols flip from
 * "directive expected an error and got one" (green) to "directive
 * expected an error and got none" (red) the moment the symbol is
 * implemented — forcing whoever lands the implementation to remove the
 * marker and replace it with a real assertion, locking the shipped
 * signature.
 */

import type * as sdk from './index';

// =========================================================================
// Tier 1 — symbols that exist today and MUST remain.
// =========================================================================

// The root error class. Every existing typed subclass extends from here.
type _IsaError = typeof sdk.IsaError;
type _IsaApiError = typeof sdk.IsaApiError;
type _IsaConfigError = typeof sdk.IsaConfigError;
type _IsaTimeoutError = typeof sdk.IsaTimeoutError;
type _IsaCaseExpiredError = typeof sdk.IsaCaseExpiredError;
type _IsaIdempotencyConflictError = typeof sdk.IsaIdempotencyConflictError;
type _IsaNotActivatedError = typeof sdk.IsaNotActivatedError;

// Top-level constructor + namespace facades.
type _Isa = typeof sdk.Isa;
type _ZyInsNamespace = typeof sdk.ZyInsNamespace;
type _RapidSignNamespace = typeof sdk.RapidSignNamespace;
type _ProxyNamespace = typeof sdk.ProxyNamespace;
type _AccountNamespace = typeof sdk.AccountNamespace;

// Cases facades — the spec's "Section 3 Flow 5" surface.
//
// `AccountCases.{create,open,list,email}` are the existing flat-method
// shape on `isa.account.cases`. A rename or signature drift on any of
// these triggers tsc.
type _AccountCases = typeof sdk.AccountCases;
type _AccountCases_create = InstanceType<typeof sdk.AccountCases>['create'];
type _AccountCases_open = InstanceType<typeof sdk.AccountCases>['open'];
type _AccountCases_list = InstanceType<typeof sdk.AccountCases>['list'];
type _AccountCases_email = InstanceType<typeof sdk.AccountCases>['email'];

// Zero-knowledge case crypto envelope (PR #347).
type _encryptCase = typeof sdk.encryptCase;
type _decryptCase = typeof sdk.decryptCase;
type _IsaCaseDecryptError = typeof sdk.IsaCaseDecryptError;

// Value types / domain primitives.
type _Height = typeof sdk.Height;
type _Weight = typeof sdk.Weight;
type _Sex = typeof sdk.Sex;
type _Coverage = typeof sdk.Coverage;

// `IsaApiVersion` is the version-pinning type. Today it is a flat string
// alias; the locked-spec §2.7 calls for it to be replaced (or
// supplemented) by `BundledApiVersions` as a per-surface map — see Tier 2.
type _IsaApiVersion = sdk.IsaApiVersion;

// =========================================================================
// Tier 2 — locked-spec names not yet implemented.
// =========================================================================
//
// Each `@ts-expect-error` below documents a name the locked spec calls for
// but the SDK has not yet shipped. Today the marker is green (the symbol is
// missing, tsc errors on the reference, the directive consumes the error).
// The instant the symbol lands in `src/index.ts`, the directive's expected
// error disappears and tsc flips to red with "Unused '@ts-expect-error'
// directive." That's the signal to:
//
//   1. Delete the @ts-expect-error line.
//   2. Replace it with a real `type _<Name> = ...` assertion (matching
//      Tier 1 style) so the shipped signature is locked from that point
//      forward.
//
// This is the forward-looking guard against the #359 class of bug: a
// future PR cannot land an implementation under a suffixed name (e.g.
// `saveV2`) without the contract review catching the missing canonical.

// `BundledApiVersions` — locked-spec §2.7 (per-surface map of bundled
// versions; see PR #360 docs lock).
type _BundledApiVersions = typeof sdk.BundledApiVersions;

// `CaseStorage` — locked-spec adapter interface (see PR #361 docs lock
// for `ZeroKnowledgeCaseStorage` as the default implementation).
type _CaseStorage = sdk.CaseStorage;

// `isa.zyins.cases.share` — locked-spec §3 Flow 5 canonical zyins
// method. The method exists on the `CasesFacade` class today, but the
// `Isa['zyins']` type does not yet surface a typed `cases` accessor
// directly via the public barrel; once the locked-spec facade exposes
// `Isa.zyins.cases` as a typed property, this assertion locks the
// signature.
// @ts-expect-error not yet surfaced on the top-level typed facade.
type _ZyInsCases_share = ReturnType<typeof sdk.Isa.withBearer>['zyins']['cases']['share'];

// `isa.zyins.cases.save` — locked-spec §3 Flow 5 future method.
// @ts-expect-error not yet implemented — replace with a real assertion when it lands.
type _ZyInsCases_save = ReturnType<typeof sdk.Isa.withBearer>['zyins']['cases']['save'];

// `isa.zyins.cases.recall` — locked-spec §3 Flow 5 future method.
// @ts-expect-error not yet implemented — replace with a real assertion when it lands.
type _ZyInsCases_recall = ReturnType<typeof sdk.Isa.withBearer>['zyins']['cases']['recall'];

// `isa.zyins.cases.delete` — locked-spec §3 Flow 5 future method.
// `delete` is a reserved word; bracket-access is the canonical form.
// @ts-expect-error not yet implemented — replace with a real assertion when it lands.
type _ZyInsCases_delete = ReturnType<typeof sdk.Isa.withBearer>['zyins']['cases']['delete'];
