<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/common.proto

namespace Sah\ZyINS\Api\V1;

use UnexpectedValueException;

/**
 * AccountStatus is the account lifecycle state per ADR-012.
 *
 * Protobuf type <code>api.zyins.v1.AccountStatus</code>
 */
class AccountStatus
{
    /**
     * Default zero value. Never emitted by the server.
     *
     * Generated from protobuf enum <code>ACCOUNT_STATUS_UNSPECIFIED = 0;</code>
     */
    const ACCOUNT_STATUS_UNSPECIFIED = 0;
    /**
     * Account is in normal operation (wire: `active`).
     *
     * Generated from protobuf enum <code>ACCOUNT_STATUS_ACTIVE = 1;</code>
     */
    const ACCOUNT_STATUS_ACTIVE = 1;
    /**
     * Reversible admin hold (wire: `suspended`).
     *
     * Generated from protobuf enum <code>ACCOUNT_STATUS_SUSPENDED = 2;</code>
     */
    const ACCOUNT_STATUS_SUSPENDED = 2;
    /**
     * Permanent admin closure; archival only (wire: `closed`).
     *
     * Generated from protobuf enum <code>ACCOUNT_STATUS_CLOSED = 3;</code>
     */
    const ACCOUNT_STATUS_CLOSED = 3;

    private static $valueToName = [
        self::ACCOUNT_STATUS_UNSPECIFIED => 'ACCOUNT_STATUS_UNSPECIFIED',
        self::ACCOUNT_STATUS_ACTIVE => 'ACCOUNT_STATUS_ACTIVE',
        self::ACCOUNT_STATUS_SUSPENDED => 'ACCOUNT_STATUS_SUSPENDED',
        self::ACCOUNT_STATUS_CLOSED => 'ACCOUNT_STATUS_CLOSED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

