<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/tokens.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * BanTokenRequest permanently bans a token and records the reason.
 *
 * Generated from protobuf message <code>api.zyins.v1.BanTokenRequest</code>
 */
class BanTokenRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Token identifier (path parameter).
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Operator-supplied reason captured in the audit log.
     *
     * Generated from protobuf field <code>string reason = 2 [json_name = "reason"];</code>
     */
    protected $reason = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Token identifier (path parameter).
     *     @type string $reason
     *           Operator-supplied reason captured in the audit log.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Tokens::initOnce();
        parent::__construct($data);
    }

    /**
     * Token identifier (path parameter).
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Token identifier (path parameter).
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Operator-supplied reason captured in the audit log.
     *
     * Generated from protobuf field <code>string reason = 2 [json_name = "reason"];</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Operator-supplied reason captured in the audit log.
     *
     * Generated from protobuf field <code>string reason = 2 [json_name = "reason"];</code>
     * @param string $var
     * @return $this
     */
    public function setReason(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->reason = $var;

        return $this;
    }

}

