<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/accounts.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * CreatePlanRequest is the body for POST /v1/plans.
 *
 * Generated from protobuf message <code>api.zyins.v1.CreatePlanRequest</code>
 */
class CreatePlanRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Externally assigned plan identifier. Must be unique.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Human-readable plan name (e.g. "Starter", "Pro", "Enterprise").
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Long-form description shown on billing pages.
     *
     * Generated from protobuf field <code>string description = 3 [json_name = "description"];</code>
     */
    protected $description = '';
    /**
     * Pricing tier classification.
     *
     * Generated from protobuf field <code>.api.zyins.v1.PlanTier tier = 4 [json_name = "tier"];</code>
     */
    protected $tier = 0;
    /**
     * Per-plan usage limits. Optional; omitted means unlimited.
     *
     * Generated from protobuf field <code>.api.zyins.v1.PlanLimits limits = 5 [json_name = "limits"];</code>
     */
    protected $limits = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Externally assigned plan identifier. Must be unique.
     *     @type string $name
     *           Human-readable plan name (e.g. "Starter", "Pro", "Enterprise").
     *     @type string $description
     *           Long-form description shown on billing pages.
     *     @type int $tier
     *           Pricing tier classification.
     *     @type \Sah\ZyINS\Api\V1\PlanLimits $limits
     *           Per-plan usage limits. Optional; omitted means unlimited.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Accounts::initOnce();
        parent::__construct($data);
    }

    /**
     * Externally assigned plan identifier. Must be unique.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Externally assigned plan identifier. Must be unique.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Human-readable plan name (e.g. "Starter", "Pro", "Enterprise").
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Human-readable plan name (e.g. "Starter", "Pro", "Enterprise").
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Long-form description shown on billing pages.
     *
     * Generated from protobuf field <code>string description = 3 [json_name = "description"];</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Long-form description shown on billing pages.
     *
     * Generated from protobuf field <code>string description = 3 [json_name = "description"];</code>
     * @param string $var
     * @return $this
     */
    public function setDescription(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->description = $var;

        return $this;
    }

    /**
     * Pricing tier classification.
     *
     * Generated from protobuf field <code>.api.zyins.v1.PlanTier tier = 4 [json_name = "tier"];</code>
     * @return int one of the values in {@see \Sah\ZyINS\Api\V1\PlanTier}
     */
    public function getTier()
    {
        return $this->tier;
    }

    /**
     * Pricing tier classification.
     *
     * Generated from protobuf field <code>.api.zyins.v1.PlanTier tier = 4 [json_name = "tier"];</code>
     * @param int $var one of the values in {@see \Sah\ZyINS\Api\V1\PlanTier}
     * @return $this
     */
    public function setTier(int $var)
    {
        GPBUtil::checkEnum($var, \Sah\ZyINS\Api\V1\PlanTier::class);
        $this->tier = $var;

        return $this;
    }

    /**
     * Per-plan usage limits. Optional; omitted means unlimited.
     *
     * Generated from protobuf field <code>.api.zyins.v1.PlanLimits limits = 5 [json_name = "limits"];</code>
     * @return \Sah\ZyINS\Api\V1\PlanLimits|null
     */
    public function getLimits()
    {
        return $this->limits;
    }

    public function hasLimits()
    {
        return isset($this->limits);
    }

    public function clearLimits()
    {
        unset($this->limits);
    }

    /**
     * Per-plan usage limits. Optional; omitted means unlimited.
     *
     * Generated from protobuf field <code>.api.zyins.v1.PlanLimits limits = 5 [json_name = "limits"];</code>
     * @param \Sah\ZyINS\Api\V1\PlanLimits $var
     * @return $this
     */
    public function setLimits(\Sah\ZyINS\Api\V1\PlanLimits|null $var)
    {
        $this->limits = $var;

        return $this;
    }

}

