<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/tokens.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * CreateTokenRequest is the body for POST /v1/tokens.
 *
 * Generated from protobuf message <code>api.zyins.v1.CreateTokenRequest</code>
 */
class CreateTokenRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Human-readable label for the token (e.g. "Production API key").
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Permission scopes granted to this token (e.g. ["prequalify",
     * "datasets"]).
     *
     * Generated from protobuf field <code>repeated string scopes = 2 [json_name = "scopes"];</code>
     */
    private $scopes;
    /**
     * Number of days until the token expires. Zero or absent means the
     * token does not expire on a fixed schedule.
     *
     * Generated from protobuf field <code>int32 expires_in_days = 3 [json_name = "expiresInDays"];</code>
     */
    protected $expires_in_days = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Human-readable label for the token (e.g. "Production API key").
     *     @type string[] $scopes
     *           Permission scopes granted to this token (e.g. ["prequalify",
     *           "datasets"]).
     *     @type int $expires_in_days
     *           Number of days until the token expires. Zero or absent means the
     *           token does not expire on a fixed schedule.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Tokens::initOnce();
        parent::__construct($data);
    }

    /**
     * Human-readable label for the token (e.g. "Production API key").
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Human-readable label for the token (e.g. "Production API key").
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Permission scopes granted to this token (e.g. ["prequalify",
     * "datasets"]).
     *
     * Generated from protobuf field <code>repeated string scopes = 2 [json_name = "scopes"];</code>
     * @return RepeatedField<string>
     */
    public function getScopes()
    {
        return $this->scopes;
    }

    /**
     * Permission scopes granted to this token (e.g. ["prequalify",
     * "datasets"]).
     *
     * Generated from protobuf field <code>repeated string scopes = 2 [json_name = "scopes"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setScopes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->scopes = $arr;

        return $this;
    }

    /**
     * Number of days until the token expires. Zero or absent means the
     * token does not expire on a fixed schedule.
     *
     * Generated from protobuf field <code>int32 expires_in_days = 3 [json_name = "expiresInDays"];</code>
     * @return int
     */
    public function getExpiresInDays()
    {
        return $this->expires_in_days;
    }

    /**
     * Number of days until the token expires. Zero or absent means the
     * token does not expire on a fixed schedule.
     *
     * Generated from protobuf field <code>int32 expires_in_days = 3 [json_name = "expiresInDays"];</code>
     * @param int $var
     * @return $this
     */
    public function setExpiresInDays(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->expires_in_days = $var;

        return $this;
    }

}

