<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/common.proto

namespace Sah\ZyINS\Api\V1;

use UnexpectedValueException;

/**
 * DeathBenefitRank is the underwriting rank category.
 *
 * Protobuf type <code>api.zyins.v1.DeathBenefitRank</code>
 */
class DeathBenefitRank
{
    /**
     * Default zero value. Never emitted by the server.
     *
     * Generated from protobuf enum <code>DEATH_BENEFIT_RANK_UNSPECIFIED = 0;</code>
     */
    const DEATH_BENEFIT_RANK_UNSPECIFIED = 0;
    /**
     * Policy takes effect immediately (wire: `immediate`).
     *
     * Generated from protobuf enum <code>DEATH_BENEFIT_RANK_IMMEDIATE = 1;</code>
     */
    const DEATH_BENEFIT_RANK_IMMEDIATE = 1;
    /**
     * Waiting period applies (wire: `graded`).
     *
     * Generated from protobuf enum <code>DEATH_BENEFIT_RANK_GRADED = 2;</code>
     */
    const DEATH_BENEFIT_RANK_GRADED = 2;
    /**
     * Return of premium (wire: `rop`).
     *
     * Generated from protobuf enum <code>DEATH_BENEFIT_RANK_ROP = 3;</code>
     */
    const DEATH_BENEFIT_RANK_ROP = 3;
    /**
     * Remaining classifications (wire: `other`).
     *
     * Generated from protobuf enum <code>DEATH_BENEFIT_RANK_OTHER = 4;</code>
     */
    const DEATH_BENEFIT_RANK_OTHER = 4;

    private static $valueToName = [
        self::DEATH_BENEFIT_RANK_UNSPECIFIED => 'DEATH_BENEFIT_RANK_UNSPECIFIED',
        self::DEATH_BENEFIT_RANK_IMMEDIATE => 'DEATH_BENEFIT_RANK_IMMEDIATE',
        self::DEATH_BENEFIT_RANK_GRADED => 'DEATH_BENEFIT_RANK_GRADED',
        self::DEATH_BENEFIT_RANK_ROP => 'DEATH_BENEFIT_RANK_ROP',
        self::DEATH_BENEFIT_RANK_OTHER => 'DEATH_BENEFIT_RANK_OTHER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

