<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/cases.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * EmailCaseRequest is the body for POST /v1/cases/{hash}/email.
 *
 * Generated from protobuf message <code>api.zyins.v1.EmailCaseRequest</code>
 */
class EmailCaseRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Short hash of the case to email. Path parameter.
     *
     * Generated from protobuf field <code>string hash = 1 [json_name = "hash"];</code>
     */
    protected $hash = '';
    /**
     * Recipient email address. Required; must be RFC 5322 valid.
     *
     * Generated from protobuf field <code>string to = 2 [json_name = "to"];</code>
     */
    protected $to = '';
    /**
     * Subject line. Optional; falls back to a server-default subject when
     * empty.
     *
     * Generated from protobuf field <code>string subject = 3 [json_name = "subject"];</code>
     */
    protected $subject = '';
    /**
     * Caller-supplied prose appended above the case link in the email
     * body. Optional; markdown is not interpreted.
     *
     * Generated from protobuf field <code>string note = 4 [json_name = "note"];</code>
     */
    protected $note = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hash
     *           Short hash of the case to email. Path parameter.
     *     @type string $to
     *           Recipient email address. Required; must be RFC 5322 valid.
     *     @type string $subject
     *           Subject line. Optional; falls back to a server-default subject when
     *           empty.
     *     @type string $note
     *           Caller-supplied prose appended above the case link in the email
     *           body. Optional; markdown is not interpreted.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Cases::initOnce();
        parent::__construct($data);
    }

    /**
     * Short hash of the case to email. Path parameter.
     *
     * Generated from protobuf field <code>string hash = 1 [json_name = "hash"];</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Short hash of the case to email. Path parameter.
     *
     * Generated from protobuf field <code>string hash = 1 [json_name = "hash"];</code>
     * @param string $var
     * @return $this
     */
    public function setHash(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->hash = $var;

        return $this;
    }

    /**
     * Recipient email address. Required; must be RFC 5322 valid.
     *
     * Generated from protobuf field <code>string to = 2 [json_name = "to"];</code>
     * @return string
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * Recipient email address. Required; must be RFC 5322 valid.
     *
     * Generated from protobuf field <code>string to = 2 [json_name = "to"];</code>
     * @param string $var
     * @return $this
     */
    public function setTo(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->to = $var;

        return $this;
    }

    /**
     * Subject line. Optional; falls back to a server-default subject when
     * empty.
     *
     * Generated from protobuf field <code>string subject = 3 [json_name = "subject"];</code>
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Subject line. Optional; falls back to a server-default subject when
     * empty.
     *
     * Generated from protobuf field <code>string subject = 3 [json_name = "subject"];</code>
     * @param string $var
     * @return $this
     */
    public function setSubject(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->subject = $var;

        return $this;
    }

    /**
     * Caller-supplied prose appended above the case link in the email
     * body. Optional; markdown is not interpreted.
     *
     * Generated from protobuf field <code>string note = 4 [json_name = "note"];</code>
     * @return string
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * Caller-supplied prose appended above the case link in the email
     * body. Optional; markdown is not interpreted.
     *
     * Generated from protobuf field <code>string note = 4 [json_name = "note"];</code>
     * @param string $var
     * @return $this
     */
    public function setNote(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->note = $var;

        return $this;
    }

}

