<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/cases.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * EmailCaseResponse is the 202 body from EmailCase. The send is
 * asynchronous — the response confirms enqueue, not delivery.
 *
 * Generated from protobuf message <code>api.zyins.v1.EmailCaseResponse</code>
 */
class EmailCaseResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource type discriminator. Wire value: `email`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     */
    protected $object = '';
    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     */
    protected $livemode = false;
    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     */
    protected $request_id = '';
    /**
     * Lifecycle state of the enqueued email. Wire value: `queued`.
     *
     * Generated from protobuf field <code>string status = 4 [json_name = "status"];</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $object
     *           Resource type discriminator. Wire value: `email`.
     *     @type bool $livemode
     *           True for live mode, false for test mode.
     *     @type string $request_id
     *           Unique request identifier.
     *     @type string $status
     *           Lifecycle state of the enqueued email. Wire value: `queued`.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Cases::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource type discriminator. Wire value: `email`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @return string
     */
    public function getObject()
    {
        return $this->object;
    }

    /**
     * Resource type discriminator. Wire value: `email`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @param string $var
     * @return $this
     */
    public function setObject(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->object = $var;

        return $this;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @return bool
     */
    public function getLivemode()
    {
        return $this->livemode;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLivemode(bool $var)
    {
        $this->livemode = $var;

        return $this;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Lifecycle state of the enqueued email. Wire value: `queued`.
     *
     * Generated from protobuf field <code>string status = 4 [json_name = "status"];</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Lifecycle state of the enqueued email. Wire value: `queued`.
     *
     * Generated from protobuf field <code>string status = 4 [json_name = "status"];</code>
     * @param string $var
     * @return $this
     */
    public function setStatus(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->status = $var;

        return $this;
    }

}

