<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/common.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Envelope is the standard response wrapper per the response-envelope
 * contract. Every success response carries `object`, `livemode`, and
 * `request_id`; resource-specific bodies live in a typed `data` field on
 * each response message (not this shared type — proto does not inherit).
 * This message exists for documentation of the contract; concrete
 * responses duplicate the three fields explicitly so each has a typed
 * `data` shape rather than a `google.protobuf.Any`.
 *
 * Generated from protobuf message <code>api.zyins.v1.Envelope</code>
 */
class Envelope extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource type discriminator. Concrete values depend on the endpoint
     * (e.g. "quote_result", "license", "token").
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     */
    protected $object = '';
    /**
     * True in production; false for test-mode responses.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     */
    protected $livemode = false;
    /**
     * Unique request identifier; echoed into all log lines for the request.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     */
    protected $request_id = '';
    /**
     * Endpoint-specific payload. Concrete responses replace this with a
     * typed message; it appears here only to document the envelope shape.
     *
     * Generated from protobuf field <code>.google.protobuf.Value data = 4 [json_name = "data"];</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $object
     *           Resource type discriminator. Concrete values depend on the endpoint
     *           (e.g. "quote_result", "license", "token").
     *     @type bool $livemode
     *           True in production; false for test-mode responses.
     *     @type string $request_id
     *           Unique request identifier; echoed into all log lines for the request.
     *     @type \Google\Protobuf\Value $data
     *           Endpoint-specific payload. Concrete responses replace this with a
     *           typed message; it appears here only to document the envelope shape.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource type discriminator. Concrete values depend on the endpoint
     * (e.g. "quote_result", "license", "token").
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @return string
     */
    public function getObject()
    {
        return $this->object;
    }

    /**
     * Resource type discriminator. Concrete values depend on the endpoint
     * (e.g. "quote_result", "license", "token").
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @param string $var
     * @return $this
     */
    public function setObject(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->object = $var;

        return $this;
    }

    /**
     * True in production; false for test-mode responses.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @return bool
     */
    public function getLivemode()
    {
        return $this->livemode;
    }

    /**
     * True in production; false for test-mode responses.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLivemode(bool $var)
    {
        $this->livemode = $var;

        return $this;
    }

    /**
     * Unique request identifier; echoed into all log lines for the request.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Unique request identifier; echoed into all log lines for the request.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Endpoint-specific payload. Concrete responses replace this with a
     * typed message; it appears here only to document the envelope shape.
     *
     * Generated from protobuf field <code>.google.protobuf.Value data = 4 [json_name = "data"];</code>
     * @return \Google\Protobuf\Value|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Endpoint-specific payload. Concrete responses replace this with a
     * typed message; it appears here only to document the envelope shape.
     *
     * Generated from protobuf field <code>.google.protobuf.Value data = 4 [json_name = "data"];</code>
     * @param \Google\Protobuf\Value $var
     * @return $this
     */
    public function setData(\Google\Protobuf\Value|null $var)
    {
        $this->data = $var;

        return $this;
    }

}

