<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/licenses.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * LicenseKeyResponse is the 200 body from GetKey.
 *
 * Generated from protobuf message <code>api.zyins.v1.LicenseKeyResponse</code>
 */
class LicenseKeyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource type discriminator. Wire value: `license_key`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     */
    protected $object = '';
    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     */
    protected $livemode = false;
    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     */
    protected $request_id = '';
    /**
     * The license key for the order.
     *
     * Generated from protobuf field <code>string license_key = 4 [json_name = "licenseKey"];</code>
     */
    protected $license_key = '';
    /**
     * Associated BPP keycode (XXX-XXX-XXX).
     *
     * Generated from protobuf field <code>string keycode = 5 [json_name = "keycode"];</code>
     */
    protected $keycode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $object
     *           Resource type discriminator. Wire value: `license_key`.
     *     @type bool $livemode
     *           True for live mode, false for test mode.
     *     @type string $request_id
     *           Unique request identifier.
     *     @type string $license_key
     *           The license key for the order.
     *     @type string $keycode
     *           Associated BPP keycode (XXX-XXX-XXX).
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Licenses::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource type discriminator. Wire value: `license_key`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @return string
     */
    public function getObject()
    {
        return $this->object;
    }

    /**
     * Resource type discriminator. Wire value: `license_key`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @param string $var
     * @return $this
     */
    public function setObject(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->object = $var;

        return $this;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @return bool
     */
    public function getLivemode()
    {
        return $this->livemode;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLivemode(bool $var)
    {
        $this->livemode = $var;

        return $this;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->request_id = $var;

        return $this;
    }

    /**
     * The license key for the order.
     *
     * Generated from protobuf field <code>string license_key = 4 [json_name = "licenseKey"];</code>
     * @return string
     */
    public function getLicenseKey()
    {
        return $this->license_key;
    }

    /**
     * The license key for the order.
     *
     * Generated from protobuf field <code>string license_key = 4 [json_name = "licenseKey"];</code>
     * @param string $var
     * @return $this
     */
    public function setLicenseKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->license_key = $var;

        return $this;
    }

    /**
     * Associated BPP keycode (XXX-XXX-XXX).
     *
     * Generated from protobuf field <code>string keycode = 5 [json_name = "keycode"];</code>
     * @return string
     */
    public function getKeycode()
    {
        return $this->keycode;
    }

    /**
     * Associated BPP keycode (XXX-XXX-XXX).
     *
     * Generated from protobuf field <code>string keycode = 5 [json_name = "keycode"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeycode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->keycode = $var;

        return $this;
    }

}

