<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/licenses.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * LicenseQuantityResponse is the 200 body from UpdateQuantity.
 *
 * Generated from protobuf message <code>api.zyins.v1.LicenseQuantityResponse</code>
 */
class LicenseQuantityResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Always `updated` on success.
     *
     * Generated from protobuf field <code>string status = 1 [json_name = "status"];</code>
     */
    protected $status = '';
    /**
     * Newly set maximum concurrent activations.
     *
     * Generated from protobuf field <code>int32 max_activations = 2 [json_name = "maxActivations"];</code>
     */
    protected $max_activations = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $status
     *           Always `updated` on success.
     *     @type int $max_activations
     *           Newly set maximum concurrent activations.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Licenses::initOnce();
        parent::__construct($data);
    }

    /**
     * Always `updated` on success.
     *
     * Generated from protobuf field <code>string status = 1 [json_name = "status"];</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Always `updated` on success.
     *
     * Generated from protobuf field <code>string status = 1 [json_name = "status"];</code>
     * @param string $var
     * @return $this
     */
    public function setStatus(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->status = $var;

        return $this;
    }

    /**
     * Newly set maximum concurrent activations.
     *
     * Generated from protobuf field <code>int32 max_activations = 2 [json_name = "maxActivations"];</code>
     * @return int
     */
    public function getMaxActivations()
    {
        return $this->max_activations;
    }

    /**
     * Newly set maximum concurrent activations.
     *
     * Generated from protobuf field <code>int32 max_activations = 2 [json_name = "maxActivations"];</code>
     * @param int $var
     * @return $this
     */
    public function setMaxActivations(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->max_activations = $var;

        return $this;
    }

}

