<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/licenses.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * LicenseCredentialsRequest is the common body for legacy license
 * operations. Either `keycode` (raw, SHA-512 hashed before storage) or
 * `order_hash` (pre-hashed) identifies the order; `email` scopes it.
 * Fields not applicable to a given operation are ignored server-side.
 *
 * Generated from protobuf message <code>api.zyins.v1.LicenseCredentialsRequest</code>
 */
class LicenseCredentialsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * License order keycode in XXX-XXX-XXX format.
     *
     * Generated from protobuf field <code>string keycode = 1 [json_name = "keycode"];</code>
     */
    protected $keycode = '';
    /**
     * Pre-hashed order identifier (used as-is if provided).
     *
     * Generated from protobuf field <code>string order_hash = 2 [json_name = "orderHash"];</code>
     */
    protected $order_hash = '';
    /**
     * Email address associated with the license.
     *
     * Generated from protobuf field <code>string email = 3 [json_name = "email"];</code>
     */
    protected $email = '';
    /**
     * Device fingerprint for anti-piracy tracking.
     *
     * Generated from protobuf field <code>string device_id = 4 [json_name = "deviceId"];</code>
     */
    protected $device_id = '';
    /**
     * License key (used for validation).
     *
     * Generated from protobuf field <code>string license = 5 [json_name = "license"];</code>
     */
    protected $license = '';
    /**
     * Domain for confinement-based email rewrite.
     *
     * Generated from protobuf field <code>string domain = 6 [json_name = "domain"];</code>
     */
    protected $domain = '';
    /**
     * Maximum concurrent activations (signup only, defaults to 1).
     *
     * Generated from protobuf field <code>int32 max_activations = 7 [json_name = "maxActivations"];</code>
     */
    protected $max_activations = 0;
    /**
     * Enterprise user email to link (signup only).
     *
     * Generated from protobuf field <code>string enterprise_user = 8 [json_name = "enterpriseUser"];</code>
     */
    protected $enterprise_user = '';
    /**
     * License quantity (signup only).
     *
     * Generated from protobuf field <code>int32 quantity = 9 [json_name = "quantity"];</code>
     */
    protected $quantity = 0;
    /**
     * Admin authorization code (reserved for future use).
     *
     * Generated from protobuf field <code>string authcode = 10 [json_name = "authcode"];</code>
     */
    protected $authcode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $keycode
     *           License order keycode in XXX-XXX-XXX format.
     *     @type string $order_hash
     *           Pre-hashed order identifier (used as-is if provided).
     *     @type string $email
     *           Email address associated with the license.
     *     @type string $device_id
     *           Device fingerprint for anti-piracy tracking.
     *     @type string $license
     *           License key (used for validation).
     *     @type string $domain
     *           Domain for confinement-based email rewrite.
     *     @type int $max_activations
     *           Maximum concurrent activations (signup only, defaults to 1).
     *     @type string $enterprise_user
     *           Enterprise user email to link (signup only).
     *     @type int $quantity
     *           License quantity (signup only).
     *     @type string $authcode
     *           Admin authorization code (reserved for future use).
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Licenses::initOnce();
        parent::__construct($data);
    }

    /**
     * License order keycode in XXX-XXX-XXX format.
     *
     * Generated from protobuf field <code>string keycode = 1 [json_name = "keycode"];</code>
     * @return string
     */
    public function getKeycode()
    {
        return $this->keycode;
    }

    /**
     * License order keycode in XXX-XXX-XXX format.
     *
     * Generated from protobuf field <code>string keycode = 1 [json_name = "keycode"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeycode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->keycode = $var;

        return $this;
    }

    /**
     * Pre-hashed order identifier (used as-is if provided).
     *
     * Generated from protobuf field <code>string order_hash = 2 [json_name = "orderHash"];</code>
     * @return string
     */
    public function getOrderHash()
    {
        return $this->order_hash;
    }

    /**
     * Pre-hashed order identifier (used as-is if provided).
     *
     * Generated from protobuf field <code>string order_hash = 2 [json_name = "orderHash"];</code>
     * @param string $var
     * @return $this
     */
    public function setOrderHash(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->order_hash = $var;

        return $this;
    }

    /**
     * Email address associated with the license.
     *
     * Generated from protobuf field <code>string email = 3 [json_name = "email"];</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Email address associated with the license.
     *
     * Generated from protobuf field <code>string email = 3 [json_name = "email"];</code>
     * @param string $var
     * @return $this
     */
    public function setEmail(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->email = $var;

        return $this;
    }

    /**
     * Device fingerprint for anti-piracy tracking.
     *
     * Generated from protobuf field <code>string device_id = 4 [json_name = "deviceId"];</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Device fingerprint for anti-piracy tracking.
     *
     * Generated from protobuf field <code>string device_id = 4 [json_name = "deviceId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->device_id = $var;

        return $this;
    }

    /**
     * License key (used for validation).
     *
     * Generated from protobuf field <code>string license = 5 [json_name = "license"];</code>
     * @return string
     */
    public function getLicense()
    {
        return $this->license;
    }

    /**
     * License key (used for validation).
     *
     * Generated from protobuf field <code>string license = 5 [json_name = "license"];</code>
     * @param string $var
     * @return $this
     */
    public function setLicense(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->license = $var;

        return $this;
    }

    /**
     * Domain for confinement-based email rewrite.
     *
     * Generated from protobuf field <code>string domain = 6 [json_name = "domain"];</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * Domain for confinement-based email rewrite.
     *
     * Generated from protobuf field <code>string domain = 6 [json_name = "domain"];</code>
     * @param string $var
     * @return $this
     */
    public function setDomain(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->domain = $var;

        return $this;
    }

    /**
     * Maximum concurrent activations (signup only, defaults to 1).
     *
     * Generated from protobuf field <code>int32 max_activations = 7 [json_name = "maxActivations"];</code>
     * @return int
     */
    public function getMaxActivations()
    {
        return $this->max_activations;
    }

    /**
     * Maximum concurrent activations (signup only, defaults to 1).
     *
     * Generated from protobuf field <code>int32 max_activations = 7 [json_name = "maxActivations"];</code>
     * @param int $var
     * @return $this
     */
    public function setMaxActivations(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->max_activations = $var;

        return $this;
    }

    /**
     * Enterprise user email to link (signup only).
     *
     * Generated from protobuf field <code>string enterprise_user = 8 [json_name = "enterpriseUser"];</code>
     * @return string
     */
    public function getEnterpriseUser()
    {
        return $this->enterprise_user;
    }

    /**
     * Enterprise user email to link (signup only).
     *
     * Generated from protobuf field <code>string enterprise_user = 8 [json_name = "enterpriseUser"];</code>
     * @param string $var
     * @return $this
     */
    public function setEnterpriseUser(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->enterprise_user = $var;

        return $this;
    }

    /**
     * License quantity (signup only).
     *
     * Generated from protobuf field <code>int32 quantity = 9 [json_name = "quantity"];</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * License quantity (signup only).
     *
     * Generated from protobuf field <code>int32 quantity = 9 [json_name = "quantity"];</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Admin authorization code (reserved for future use).
     *
     * Generated from protobuf field <code>string authcode = 10 [json_name = "authcode"];</code>
     * @return string
     */
    public function getAuthcode()
    {
        return $this->authcode;
    }

    /**
     * Admin authorization code (reserved for future use).
     *
     * Generated from protobuf field <code>string authcode = 10 [json_name = "authcode"];</code>
     * @param string $var
     * @return $this
     */
    public function setAuthcode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->authcode = $var;

        return $this;
    }

}

