<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/tokens.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ListTokensResponse mirrors the shipped `TokenListResponse` shape.
 *
 * Generated from protobuf message <code>api.zyins.v1.ListTokensResponse</code>
 */
class ListTokensResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource type discriminator. Wire value: `list`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     */
    protected $object = '';
    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     */
    protected $livemode = false;
    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     */
    protected $request_id = '';
    /**
     * The tokens owned by the authenticated account, redacted.
     *
     * Generated from protobuf field <code>repeated .api.zyins.v1.TokenDetail data = 4 [json_name = "data"];</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $object
     *           Resource type discriminator. Wire value: `list`.
     *     @type bool $livemode
     *           True for live mode, false for test mode.
     *     @type string $request_id
     *           Unique request identifier.
     *     @type \Sah\ZyINS\Api\V1\TokenDetail[] $data
     *           The tokens owned by the authenticated account, redacted.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Tokens::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource type discriminator. Wire value: `list`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @return string
     */
    public function getObject()
    {
        return $this->object;
    }

    /**
     * Resource type discriminator. Wire value: `list`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @param string $var
     * @return $this
     */
    public function setObject(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->object = $var;

        return $this;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @return bool
     */
    public function getLivemode()
    {
        return $this->livemode;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLivemode(bool $var)
    {
        $this->livemode = $var;

        return $this;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->request_id = $var;

        return $this;
    }

    /**
     * The tokens owned by the authenticated account, redacted.
     *
     * Generated from protobuf field <code>repeated .api.zyins.v1.TokenDetail data = 4 [json_name = "data"];</code>
     * @return RepeatedField<\Sah\ZyINS\Api\V1\TokenDetail>
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * The tokens owned by the authenticated account, redacted.
     *
     * Generated from protobuf field <code>repeated .api.zyins.v1.TokenDetail data = 4 [json_name = "data"];</code>
     * @param \Sah\ZyINS\Api\V1\TokenDetail[] $var
     * @return $this
     */
    public function setData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sah\ZyINS\Api\V1\TokenDetail::class);
        $this->data = $arr;

        return $this;
    }

}

