<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/accounts.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ListAccountsRequest is the empty request body for GET /v1/accounts.
 *
 * Generated from protobuf message <code>api.zyins.v1.ListAccountsRequest</code>
 */
class ListAccountsRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Accounts::initOnce();
        parent::__construct($data);
    }

}

