<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/preferences.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * PreferencesEnvelope is the canonical 200 body shape for both
 * BackupPreferences and RestorePreferences. Both operations return the
 * SAME shape — this is the round-trip contract enforced in tests.
 *
 * Generated from protobuf message <code>api.zyins.v1.PreferencesEnvelope</code>
 */
class PreferencesEnvelope extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource type discriminator. Wire value: `preferences`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     */
    protected $object = '';
    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     */
    protected $livemode = false;
    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     */
    protected $request_id = '';
    /**
     * The whitelabel preferences payload. Empty (zero-valued) when the
     * account has never persisted preferences. Byte-identical between
     * backup-write and the next restore-read.
     *
     * Generated from protobuf field <code>.api.zyins.v1.WhitelabelPreferences prefs = 4 [json_name = "prefs"];</code>
     */
    protected $prefs = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $object
     *           Resource type discriminator. Wire value: `preferences`.
     *     @type bool $livemode
     *           True for live mode, false for test mode.
     *     @type string $request_id
     *           Unique request identifier.
     *     @type \Sah\ZyINS\Api\V1\WhitelabelPreferences $prefs
     *           The whitelabel preferences payload. Empty (zero-valued) when the
     *           account has never persisted preferences. Byte-identical between
     *           backup-write and the next restore-read.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Preferences::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource type discriminator. Wire value: `preferences`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @return string
     */
    public function getObject()
    {
        return $this->object;
    }

    /**
     * Resource type discriminator. Wire value: `preferences`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @param string $var
     * @return $this
     */
    public function setObject(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->object = $var;

        return $this;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @return bool
     */
    public function getLivemode()
    {
        return $this->livemode;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLivemode(bool $var)
    {
        $this->livemode = $var;

        return $this;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->request_id = $var;

        return $this;
    }

    /**
     * The whitelabel preferences payload. Empty (zero-valued) when the
     * account has never persisted preferences. Byte-identical between
     * backup-write and the next restore-read.
     *
     * Generated from protobuf field <code>.api.zyins.v1.WhitelabelPreferences prefs = 4 [json_name = "prefs"];</code>
     * @return \Sah\ZyINS\Api\V1\WhitelabelPreferences|null
     */
    public function getPrefs()
    {
        return $this->prefs;
    }

    public function hasPrefs()
    {
        return isset($this->prefs);
    }

    public function clearPrefs()
    {
        unset($this->prefs);
    }

    /**
     * The whitelabel preferences payload. Empty (zero-valued) when the
     * account has never persisted preferences. Byte-identical between
     * backup-write and the next restore-read.
     *
     * Generated from protobuf field <code>.api.zyins.v1.WhitelabelPreferences prefs = 4 [json_name = "prefs"];</code>
     * @param \Sah\ZyINS\Api\V1\WhitelabelPreferences $var
     * @return $this
     */
    public function setPrefs(\Sah\ZyINS\Api\V1\WhitelabelPreferences|null $var)
    {
        $this->prefs = $var;

        return $this;
    }

}

