<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/licenses.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * PublicDeactivateResponse is the 200 body from PublicDeactivate.
 *
 * Generated from protobuf message <code>api.zyins.v1.PublicDeactivateResponse</code>
 */
class PublicDeactivateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Always `deactivated` on success.
     *
     * Generated from protobuf field <code>string status = 1 [json_name = "status"];</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $status
     *           Always `deactivated` on success.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Licenses::initOnce();
        parent::__construct($data);
    }

    /**
     * Always `deactivated` on success.
     *
     * Generated from protobuf field <code>string status = 1 [json_name = "status"];</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Always `deactivated` on success.
     *
     * Generated from protobuf field <code>string status = 1 [json_name = "status"];</code>
     * @param string $var
     * @return $this
     */
    public function setStatus(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->status = $var;

        return $this;
    }

}

