<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/zyins/v1/licenses.proto

namespace Sah\ZyINS\Api\V1;

if (false) {
    /**
     * This class is deprecated. Use Sah\ZyINS\Api\V1\PublicActivateResponse\Auth\Headers instead.
     * @deprecated
     */
    class PublicActivateResponse_Auth_Headers {}
}
class_exists(PublicActivateResponse\Auth\Headers::class);
@trigger_error('Sah\ZyINS\Api\V1\PublicActivateResponse_Auth_Headers is deprecated and will be removed in the next major release. Use Sah\ZyINS\Api\V1\PublicActivateResponse\Auth\Headers instead', E_USER_DEPRECATED);

