<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/licenses.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * PublicActivateResponse is the 200 body from PublicActivate. The
 * nested `auth` object carries a pre-built Authorization header so
 * client code does not need to re-implement the base64 scheme.
 *
 * Generated from protobuf message <code>api.zyins.v1.PublicActivateResponse</code>
 */
class PublicActivateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource type discriminator. Wire value: `license_activation`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     */
    protected $object = '';
    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     */
    protected $livemode = false;
    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     */
    protected $request_id = '';
    /**
     * Always `active` on success.
     *
     * Generated from protobuf field <code>string status = 4 [json_name = "status"];</code>
     */
    protected $status = '';
    /**
     * Device activations remaining after this call.
     *
     * Generated from protobuf field <code>int32 remaining_activations = 5 [json_name = "remainingActivations"];</code>
     */
    protected $remaining_activations = 0;
    /**
     * Pre-built credentials for subsequent authenticated requests.
     *
     * Generated from protobuf field <code>.api.zyins.v1.PublicActivateResponse.Auth auth = 6 [json_name = "auth"];</code>
     */
    protected $auth = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $object
     *           Resource type discriminator. Wire value: `license_activation`.
     *     @type bool $livemode
     *           True for live mode, false for test mode.
     *     @type string $request_id
     *           Unique request identifier.
     *     @type string $status
     *           Always `active` on success.
     *     @type int $remaining_activations
     *           Device activations remaining after this call.
     *     @type \Sah\ZyINS\Api\V1\PublicActivateResponse\Auth $auth
     *           Pre-built credentials for subsequent authenticated requests.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Licenses::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource type discriminator. Wire value: `license_activation`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @return string
     */
    public function getObject()
    {
        return $this->object;
    }

    /**
     * Resource type discriminator. Wire value: `license_activation`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @param string $var
     * @return $this
     */
    public function setObject(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->object = $var;

        return $this;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @return bool
     */
    public function getLivemode()
    {
        return $this->livemode;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLivemode(bool $var)
    {
        $this->livemode = $var;

        return $this;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Always `active` on success.
     *
     * Generated from protobuf field <code>string status = 4 [json_name = "status"];</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Always `active` on success.
     *
     * Generated from protobuf field <code>string status = 4 [json_name = "status"];</code>
     * @param string $var
     * @return $this
     */
    public function setStatus(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->status = $var;

        return $this;
    }

    /**
     * Device activations remaining after this call.
     *
     * Generated from protobuf field <code>int32 remaining_activations = 5 [json_name = "remainingActivations"];</code>
     * @return int
     */
    public function getRemainingActivations()
    {
        return $this->remaining_activations;
    }

    /**
     * Device activations remaining after this call.
     *
     * Generated from protobuf field <code>int32 remaining_activations = 5 [json_name = "remainingActivations"];</code>
     * @param int $var
     * @return $this
     */
    public function setRemainingActivations(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->remaining_activations = $var;

        return $this;
    }

    /**
     * Pre-built credentials for subsequent authenticated requests.
     *
     * Generated from protobuf field <code>.api.zyins.v1.PublicActivateResponse.Auth auth = 6 [json_name = "auth"];</code>
     * @return \Sah\ZyINS\Api\V1\PublicActivateResponse\Auth|null
     */
    public function getAuth()
    {
        return $this->auth;
    }

    public function hasAuth()
    {
        return isset($this->auth);
    }

    public function clearAuth()
    {
        unset($this->auth);
    }

    /**
     * Pre-built credentials for subsequent authenticated requests.
     *
     * Generated from protobuf field <code>.api.zyins.v1.PublicActivateResponse.Auth auth = 6 [json_name = "auth"];</code>
     * @param \Sah\ZyINS\Api\V1\PublicActivateResponse\Auth $var
     * @return $this
     */
    public function setAuth(\Sah\ZyINS\Api\V1\PublicActivateResponse\Auth|null $var)
    {
        $this->auth = $var;

        return $this;
    }

}

