<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/preferences.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * RestorePreferencesRequest is the query for GET /v2/preferences/restore.
 * Both fields are required; both participate in the storage key.
 *
 * Generated from protobuf message <code>api.zyins.v1.RestorePreferencesRequest</code>
 */
class RestorePreferencesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Account email used as part of the lookup key. Required.
     *
     * Generated from protobuf field <code>string email = 1 [json_name = "email"];</code>
     */
    protected $email = '';
    /**
     * BPP keycode used as part of the lookup key. Required.
     *
     * Generated from protobuf field <code>string keycode = 2 [json_name = "keycode"];</code>
     */
    protected $keycode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $email
     *           Account email used as part of the lookup key. Required.
     *     @type string $keycode
     *           BPP keycode used as part of the lookup key. Required.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Preferences::initOnce();
        parent::__construct($data);
    }

    /**
     * Account email used as part of the lookup key. Required.
     *
     * Generated from protobuf field <code>string email = 1 [json_name = "email"];</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Account email used as part of the lookup key. Required.
     *
     * Generated from protobuf field <code>string email = 1 [json_name = "email"];</code>
     * @param string $var
     * @return $this
     */
    public function setEmail(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->email = $var;

        return $this;
    }

    /**
     * BPP keycode used as part of the lookup key. Required.
     *
     * Generated from protobuf field <code>string keycode = 2 [json_name = "keycode"];</code>
     * @return string
     */
    public function getKeycode()
    {
        return $this->keycode;
    }

    /**
     * BPP keycode used as part of the lookup key. Required.
     *
     * Generated from protobuf field <code>string keycode = 2 [json_name = "keycode"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeycode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->keycode = $var;

        return $this;
    }

}

