<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/tokens.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * RotateTokenRequest targets an existing token; the server issues a new
 * token with the same scopes and schedules the old one for revocation
 * after a grace window.
 *
 * Generated from protobuf message <code>api.zyins.v1.RotateTokenRequest</code>
 */
class RotateTokenRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Identifier of the token to rotate. May be supplied as the
     * path parameter on `/v1/tokens/{token_id}/rotate` or in the
     * request body on the legacy `/v1/tokens/rotate` binding.
     *
     * Generated from protobuf field <code>string token_id = 1 [json_name = "tokenId"];</code>
     */
    protected $token_id = '';
    /**
     * Expiry for the replacement token in days. Zero or absent keeps the
     * original expiry policy.
     *
     * Generated from protobuf field <code>int32 expires_in_days = 2 [json_name = "expiresInDays"];</code>
     */
    protected $expires_in_days = 0;
    /**
     * Seconds the old token remains active after rotation before the
     * sweeper revokes it. Absent applies the default 2,592,000 (30
     * days). Range 0 to 7,776,000 (90 days). Explicit 0 revokes the old
     * token immediately; the new token still ships in the response.
     * Task #117 + #118: handler stamps `revokes_at = now() +
     * grace_period_seconds`; the sweeper Lambda flips status to
     * `revoked` when the deadline elapses.
     *
     * Generated from protobuf field <code>optional int32 grace_period_seconds = 3 [json_name = "gracePeriodSeconds"];</code>
     */
    protected $grace_period_seconds = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token_id
     *           Identifier of the token to rotate. May be supplied as the
     *           path parameter on `/v1/tokens/{token_id}/rotate` or in the
     *           request body on the legacy `/v1/tokens/rotate` binding.
     *     @type int $expires_in_days
     *           Expiry for the replacement token in days. Zero or absent keeps the
     *           original expiry policy.
     *     @type int $grace_period_seconds
     *           Seconds the old token remains active after rotation before the
     *           sweeper revokes it. Absent applies the default 2,592,000 (30
     *           days). Range 0 to 7,776,000 (90 days). Explicit 0 revokes the old
     *           token immediately; the new token still ships in the response.
     *           Task #117 + #118: handler stamps `revokes_at = now() +
     *           grace_period_seconds`; the sweeper Lambda flips status to
     *           `revoked` when the deadline elapses.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Tokens::initOnce();
        parent::__construct($data);
    }

    /**
     * Identifier of the token to rotate. May be supplied as the
     * path parameter on `/v1/tokens/{token_id}/rotate` or in the
     * request body on the legacy `/v1/tokens/rotate` binding.
     *
     * Generated from protobuf field <code>string token_id = 1 [json_name = "tokenId"];</code>
     * @return string
     */
    public function getTokenId()
    {
        return $this->token_id;
    }

    /**
     * Identifier of the token to rotate. May be supplied as the
     * path parameter on `/v1/tokens/{token_id}/rotate` or in the
     * request body on the legacy `/v1/tokens/rotate` binding.
     *
     * Generated from protobuf field <code>string token_id = 1 [json_name = "tokenId"];</code>
     * @param string $var
     * @return $this
     */
    public function setTokenId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->token_id = $var;

        return $this;
    }

    /**
     * Expiry for the replacement token in days. Zero or absent keeps the
     * original expiry policy.
     *
     * Generated from protobuf field <code>int32 expires_in_days = 2 [json_name = "expiresInDays"];</code>
     * @return int
     */
    public function getExpiresInDays()
    {
        return $this->expires_in_days;
    }

    /**
     * Expiry for the replacement token in days. Zero or absent keeps the
     * original expiry policy.
     *
     * Generated from protobuf field <code>int32 expires_in_days = 2 [json_name = "expiresInDays"];</code>
     * @param int $var
     * @return $this
     */
    public function setExpiresInDays(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->expires_in_days = $var;

        return $this;
    }

    /**
     * Seconds the old token remains active after rotation before the
     * sweeper revokes it. Absent applies the default 2,592,000 (30
     * days). Range 0 to 7,776,000 (90 days). Explicit 0 revokes the old
     * token immediately; the new token still ships in the response.
     * Task #117 + #118: handler stamps `revokes_at = now() +
     * grace_period_seconds`; the sweeper Lambda flips status to
     * `revoked` when the deadline elapses.
     *
     * Generated from protobuf field <code>optional int32 grace_period_seconds = 3 [json_name = "gracePeriodSeconds"];</code>
     * @return int
     */
    public function getGracePeriodSeconds()
    {
        return isset($this->grace_period_seconds) ? $this->grace_period_seconds : 0;
    }

    public function hasGracePeriodSeconds()
    {
        return isset($this->grace_period_seconds);
    }

    public function clearGracePeriodSeconds()
    {
        unset($this->grace_period_seconds);
    }

    /**
     * Seconds the old token remains active after rotation before the
     * sweeper revokes it. Absent applies the default 2,592,000 (30
     * days). Range 0 to 7,776,000 (90 days). Explicit 0 revokes the old
     * token immediately; the new token still ships in the response.
     * Task #117 + #118: handler stamps `revokes_at = now() +
     * grace_period_seconds`; the sweeper Lambda flips status to
     * `revoked` when the deadline elapses.
     *
     * Generated from protobuf field <code>optional int32 grace_period_seconds = 3 [json_name = "gracePeriodSeconds"];</code>
     * @param int $var
     * @return $this
     */
    public function setGracePeriodSeconds(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->grace_period_seconds = $var;

        return $this;
    }

}

