<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/accounts.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * SetPlanRateRequest is the body for PUT /v1/plans/{plan_id}/rates/{metric}.
 * The server upserts by (plan_id, metric): if a rate for the metric
 * already exists it is replaced; otherwise a new rate is inserted.
 *
 * Generated from protobuf message <code>api.zyins.v1.SetPlanRateRequest</code>
 */
class SetPlanRateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Plan identifier (path parameter).
     *
     * Generated from protobuf field <code>string plan_id = 1 [json_name = "planId"];</code>
     */
    protected $plan_id = '';
    /**
     * Metric identifier (path parameter). Conventionally the endpoint name
     * being priced, e.g. `prequalify`, `quote`, or `datasets.fetch`.
     *
     * Generated from protobuf field <code>string metric = 2 [json_name = "metric"];</code>
     */
    protected $metric = '';
    /**
     * Cost per unit of the metric, in the minor unit of `currency`
     * (e.g. cents for USD). A decimal string to preserve sub-cent precision.
     *
     * Generated from protobuf field <code>string amount = 3 [json_name = "amount"];</code>
     */
    protected $amount = '';
    /**
     * ISO 4217 currency code for `amount` (e.g. `USD`).
     *
     * Generated from protobuf field <code>string currency = 4 [json_name = "currency"];</code>
     */
    protected $currency = '';
    /**
     * RFC 3339 timestamp at which the rate takes effect. Empty string
     * means "immediately on upsert".
     *
     * Generated from protobuf field <code>string effective_at = 5 [json_name = "effectiveAt"];</code>
     */
    protected $effective_at = '';
    /**
     * Requests included at no additional charge before `amount` applies.
     * Zero means every request is billed at `amount`.
     *
     * Generated from protobuf field <code>int32 included_free = 6 [json_name = "includedFree"];</code>
     */
    protected $included_free = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $plan_id
     *           Plan identifier (path parameter).
     *     @type string $metric
     *           Metric identifier (path parameter). Conventionally the endpoint name
     *           being priced, e.g. `prequalify`, `quote`, or `datasets.fetch`.
     *     @type string $amount
     *           Cost per unit of the metric, in the minor unit of `currency`
     *           (e.g. cents for USD). A decimal string to preserve sub-cent precision.
     *     @type string $currency
     *           ISO 4217 currency code for `amount` (e.g. `USD`).
     *     @type string $effective_at
     *           RFC 3339 timestamp at which the rate takes effect. Empty string
     *           means "immediately on upsert".
     *     @type int $included_free
     *           Requests included at no additional charge before `amount` applies.
     *           Zero means every request is billed at `amount`.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Accounts::initOnce();
        parent::__construct($data);
    }

    /**
     * Plan identifier (path parameter).
     *
     * Generated from protobuf field <code>string plan_id = 1 [json_name = "planId"];</code>
     * @return string
     */
    public function getPlanId()
    {
        return $this->plan_id;
    }

    /**
     * Plan identifier (path parameter).
     *
     * Generated from protobuf field <code>string plan_id = 1 [json_name = "planId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPlanId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->plan_id = $var;

        return $this;
    }

    /**
     * Metric identifier (path parameter). Conventionally the endpoint name
     * being priced, e.g. `prequalify`, `quote`, or `datasets.fetch`.
     *
     * Generated from protobuf field <code>string metric = 2 [json_name = "metric"];</code>
     * @return string
     */
    public function getMetric()
    {
        return $this->metric;
    }

    /**
     * Metric identifier (path parameter). Conventionally the endpoint name
     * being priced, e.g. `prequalify`, `quote`, or `datasets.fetch`.
     *
     * Generated from protobuf field <code>string metric = 2 [json_name = "metric"];</code>
     * @param string $var
     * @return $this
     */
    public function setMetric(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->metric = $var;

        return $this;
    }

    /**
     * Cost per unit of the metric, in the minor unit of `currency`
     * (e.g. cents for USD). A decimal string to preserve sub-cent precision.
     *
     * Generated from protobuf field <code>string amount = 3 [json_name = "amount"];</code>
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Cost per unit of the metric, in the minor unit of `currency`
     * (e.g. cents for USD). A decimal string to preserve sub-cent precision.
     *
     * Generated from protobuf field <code>string amount = 3 [json_name = "amount"];</code>
     * @param string $var
     * @return $this
     */
    public function setAmount(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->amount = $var;

        return $this;
    }

    /**
     * ISO 4217 currency code for `amount` (e.g. `USD`).
     *
     * Generated from protobuf field <code>string currency = 4 [json_name = "currency"];</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * ISO 4217 currency code for `amount` (e.g. `USD`).
     *
     * Generated from protobuf field <code>string currency = 4 [json_name = "currency"];</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->currency = $var;

        return $this;
    }

    /**
     * RFC 3339 timestamp at which the rate takes effect. Empty string
     * means "immediately on upsert".
     *
     * Generated from protobuf field <code>string effective_at = 5 [json_name = "effectiveAt"];</code>
     * @return string
     */
    public function getEffectiveAt()
    {
        return $this->effective_at;
    }

    /**
     * RFC 3339 timestamp at which the rate takes effect. Empty string
     * means "immediately on upsert".
     *
     * Generated from protobuf field <code>string effective_at = 5 [json_name = "effectiveAt"];</code>
     * @param string $var
     * @return $this
     */
    public function setEffectiveAt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->effective_at = $var;

        return $this;
    }

    /**
     * Requests included at no additional charge before `amount` applies.
     * Zero means every request is billed at `amount`.
     *
     * Generated from protobuf field <code>int32 included_free = 6 [json_name = "includedFree"];</code>
     * @return int
     */
    public function getIncludedFree()
    {
        return $this->included_free;
    }

    /**
     * Requests included at no additional charge before `amount` applies.
     * Zero means every request is billed at `amount`.
     *
     * Generated from protobuf field <code>int32 included_free = 6 [json_name = "includedFree"];</code>
     * @param int $var
     * @return $this
     */
    public function setIncludedFree(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->included_free = $var;

        return $this;
    }

}

