<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/accounts.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * SetPlanRateResponse is the 200 body from SetPlanRate.
 *
 * Generated from protobuf message <code>api.zyins.v1.SetPlanRateResponse</code>
 */
class SetPlanRateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource type discriminator. Wire value: `plan_rate`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     */
    protected $object = '';
    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     */
    protected $livemode = false;
    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     */
    protected $request_id = '';
    /**
     * Plan identifier the rate belongs to.
     *
     * Generated from protobuf field <code>string plan_id = 4 [json_name = "planId"];</code>
     */
    protected $plan_id = '';
    /**
     * Metric identifier (e.g. `prequalify`, `quote`).
     *
     * Generated from protobuf field <code>string metric = 5 [json_name = "metric"];</code>
     */
    protected $metric = '';
    /**
     * Cost per unit of the metric, in the minor unit of `currency`. A
     * decimal string to preserve sub-cent precision.
     *
     * Generated from protobuf field <code>string amount = 6 [json_name = "amount"];</code>
     */
    protected $amount = '';
    /**
     * ISO 4217 currency code for `amount`.
     *
     * Generated from protobuf field <code>string currency = 7 [json_name = "currency"];</code>
     */
    protected $currency = '';
    /**
     * RFC 3339 timestamp at which the rate took effect.
     *
     * Generated from protobuf field <code>string effective_at = 8 [json_name = "effectiveAt"];</code>
     */
    protected $effective_at = '';
    /**
     * Requests included at no additional charge before `amount` applies.
     *
     * Generated from protobuf field <code>int32 included_free = 9 [json_name = "includedFree"];</code>
     */
    protected $included_free = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $object
     *           Resource type discriminator. Wire value: `plan_rate`.
     *     @type bool $livemode
     *           True for live mode, false for test mode.
     *     @type string $request_id
     *           Unique request identifier.
     *     @type string $plan_id
     *           Plan identifier the rate belongs to.
     *     @type string $metric
     *           Metric identifier (e.g. `prequalify`, `quote`).
     *     @type string $amount
     *           Cost per unit of the metric, in the minor unit of `currency`. A
     *           decimal string to preserve sub-cent precision.
     *     @type string $currency
     *           ISO 4217 currency code for `amount`.
     *     @type string $effective_at
     *           RFC 3339 timestamp at which the rate took effect.
     *     @type int $included_free
     *           Requests included at no additional charge before `amount` applies.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Accounts::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource type discriminator. Wire value: `plan_rate`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @return string
     */
    public function getObject()
    {
        return $this->object;
    }

    /**
     * Resource type discriminator. Wire value: `plan_rate`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @param string $var
     * @return $this
     */
    public function setObject(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->object = $var;

        return $this;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @return bool
     */
    public function getLivemode()
    {
        return $this->livemode;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLivemode(bool $var)
    {
        $this->livemode = $var;

        return $this;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Plan identifier the rate belongs to.
     *
     * Generated from protobuf field <code>string plan_id = 4 [json_name = "planId"];</code>
     * @return string
     */
    public function getPlanId()
    {
        return $this->plan_id;
    }

    /**
     * Plan identifier the rate belongs to.
     *
     * Generated from protobuf field <code>string plan_id = 4 [json_name = "planId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPlanId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->plan_id = $var;

        return $this;
    }

    /**
     * Metric identifier (e.g. `prequalify`, `quote`).
     *
     * Generated from protobuf field <code>string metric = 5 [json_name = "metric"];</code>
     * @return string
     */
    public function getMetric()
    {
        return $this->metric;
    }

    /**
     * Metric identifier (e.g. `prequalify`, `quote`).
     *
     * Generated from protobuf field <code>string metric = 5 [json_name = "metric"];</code>
     * @param string $var
     * @return $this
     */
    public function setMetric(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->metric = $var;

        return $this;
    }

    /**
     * Cost per unit of the metric, in the minor unit of `currency`. A
     * decimal string to preserve sub-cent precision.
     *
     * Generated from protobuf field <code>string amount = 6 [json_name = "amount"];</code>
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Cost per unit of the metric, in the minor unit of `currency`. A
     * decimal string to preserve sub-cent precision.
     *
     * Generated from protobuf field <code>string amount = 6 [json_name = "amount"];</code>
     * @param string $var
     * @return $this
     */
    public function setAmount(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->amount = $var;

        return $this;
    }

    /**
     * ISO 4217 currency code for `amount`.
     *
     * Generated from protobuf field <code>string currency = 7 [json_name = "currency"];</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * ISO 4217 currency code for `amount`.
     *
     * Generated from protobuf field <code>string currency = 7 [json_name = "currency"];</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->currency = $var;

        return $this;
    }

    /**
     * RFC 3339 timestamp at which the rate took effect.
     *
     * Generated from protobuf field <code>string effective_at = 8 [json_name = "effectiveAt"];</code>
     * @return string
     */
    public function getEffectiveAt()
    {
        return $this->effective_at;
    }

    /**
     * RFC 3339 timestamp at which the rate took effect.
     *
     * Generated from protobuf field <code>string effective_at = 8 [json_name = "effectiveAt"];</code>
     * @param string $var
     * @return $this
     */
    public function setEffectiveAt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->effective_at = $var;

        return $this;
    }

    /**
     * Requests included at no additional charge before `amount` applies.
     *
     * Generated from protobuf field <code>int32 included_free = 9 [json_name = "includedFree"];</code>
     * @return int
     */
    public function getIncludedFree()
    {
        return $this->included_free;
    }

    /**
     * Requests included at no additional charge before `amount` applies.
     *
     * Generated from protobuf field <code>int32 included_free = 9 [json_name = "includedFree"];</code>
     * @param int $var
     * @return $this
     */
    public function setIncludedFree(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->included_free = $var;

        return $this;
    }

}

