<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/tokens.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * TokenDetail is the canonical token resource shape returned by every
 * read and lifecycle-transition endpoint (except Create and Rotate,
 * which additionally return the plaintext token value).
 *
 * Generated from protobuf message <code>api.zyins.v1.TokenDetail</code>
 */
class TokenDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource type discriminator. Wire value: `token`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     */
    protected $object = '';
    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     */
    protected $livemode = false;
    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     */
    protected $request_id = '';
    /**
     * Token identifier (e.g. `tok_abc123def456`).
     *
     * Generated from protobuf field <code>string id = 4 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Human-readable label.
     *
     * Generated from protobuf field <code>string name = 5 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Last four characters of the token.
     *
     * Generated from protobuf field <code>string hint = 6 [json_name = "hint"];</code>
     */
    protected $hint = '';
    /**
     * Permission scopes granted to this token.
     *
     * Generated from protobuf field <code>repeated string scopes = 7 [json_name = "scopes"];</code>
     */
    private $scopes;
    /**
     * Current lifecycle state.
     *
     * Generated from protobuf field <code>.api.zyins.v1.TokenStatus status = 8 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Reason recorded when the token was revoked or banned. Empty
     * otherwise.
     *
     * Generated from protobuf field <code>string revoked_reason = 9 [json_name = "revokedReason"];</code>
     */
    protected $revoked_reason = '';
    /**
     * RFC 3339 creation timestamp.
     *
     * Generated from protobuf field <code>string created_at = 10 [json_name = "createdAt"];</code>
     */
    protected $created_at = '';
    /**
     * RFC 3339 expiry timestamp. Empty string means the token does not
     * expire.
     *
     * Generated from protobuf field <code>string expires_at = 11 [json_name = "expiresAt"];</code>
     */
    protected $expires_at = '';
    /**
     * RFC 3339 revocation timestamp. Empty string if the token has never
     * been revoked.
     *
     * Generated from protobuf field <code>string revoked_at = 12 [json_name = "revokedAt"];</code>
     */
    protected $revoked_at = '';
    /**
     * RFC 3339 timestamp of the most recent authenticated request made
     * with this token. Empty string if the token has never been used.
     *
     * Generated from protobuf field <code>string last_used_at = 13 [json_name = "lastUsedAt"];</code>
     */
    protected $last_used_at = '';
    /**
     * RFC 3339 timestamp at which the sweeper will revoke this token.
     * Set when the token has been replaced via Rotate but its grace
     * window has not yet elapsed. Empty string when no rotation is
     * pending. Task #117 + #118.
     *
     * Generated from protobuf field <code>string revokes_at = 14 [json_name = "revokesAt"];</code>
     */
    protected $revokes_at = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $object
     *           Resource type discriminator. Wire value: `token`.
     *     @type bool $livemode
     *           True for live mode, false for test mode.
     *     @type string $request_id
     *           Unique request identifier.
     *     @type string $id
     *           Token identifier (e.g. `tok_abc123def456`).
     *     @type string $name
     *           Human-readable label.
     *     @type string $hint
     *           Last four characters of the token.
     *     @type string[] $scopes
     *           Permission scopes granted to this token.
     *     @type int $status
     *           Current lifecycle state.
     *     @type string $revoked_reason
     *           Reason recorded when the token was revoked or banned. Empty
     *           otherwise.
     *     @type string $created_at
     *           RFC 3339 creation timestamp.
     *     @type string $expires_at
     *           RFC 3339 expiry timestamp. Empty string means the token does not
     *           expire.
     *     @type string $revoked_at
     *           RFC 3339 revocation timestamp. Empty string if the token has never
     *           been revoked.
     *     @type string $last_used_at
     *           RFC 3339 timestamp of the most recent authenticated request made
     *           with this token. Empty string if the token has never been used.
     *     @type string $revokes_at
     *           RFC 3339 timestamp at which the sweeper will revoke this token.
     *           Set when the token has been replaced via Rotate but its grace
     *           window has not yet elapsed. Empty string when no rotation is
     *           pending. Task #117 + #118.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Tokens::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource type discriminator. Wire value: `token`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @return string
     */
    public function getObject()
    {
        return $this->object;
    }

    /**
     * Resource type discriminator. Wire value: `token`.
     *
     * Generated from protobuf field <code>string object = 1 [json_name = "object"];</code>
     * @param string $var
     * @return $this
     */
    public function setObject(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->object = $var;

        return $this;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @return bool
     */
    public function getLivemode()
    {
        return $this->livemode;
    }

    /**
     * True for live mode, false for test mode.
     *
     * Generated from protobuf field <code>bool livemode = 2 [json_name = "livemode"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLivemode(bool $var)
    {
        $this->livemode = $var;

        return $this;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Unique request identifier.
     *
     * Generated from protobuf field <code>string request_id = 3 [json_name = "requestId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Token identifier (e.g. `tok_abc123def456`).
     *
     * Generated from protobuf field <code>string id = 4 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Token identifier (e.g. `tok_abc123def456`).
     *
     * Generated from protobuf field <code>string id = 4 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Human-readable label.
     *
     * Generated from protobuf field <code>string name = 5 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Human-readable label.
     *
     * Generated from protobuf field <code>string name = 5 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Last four characters of the token.
     *
     * Generated from protobuf field <code>string hint = 6 [json_name = "hint"];</code>
     * @return string
     */
    public function getHint()
    {
        return $this->hint;
    }

    /**
     * Last four characters of the token.
     *
     * Generated from protobuf field <code>string hint = 6 [json_name = "hint"];</code>
     * @param string $var
     * @return $this
     */
    public function setHint(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->hint = $var;

        return $this;
    }

    /**
     * Permission scopes granted to this token.
     *
     * Generated from protobuf field <code>repeated string scopes = 7 [json_name = "scopes"];</code>
     * @return RepeatedField<string>
     */
    public function getScopes()
    {
        return $this->scopes;
    }

    /**
     * Permission scopes granted to this token.
     *
     * Generated from protobuf field <code>repeated string scopes = 7 [json_name = "scopes"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setScopes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->scopes = $arr;

        return $this;
    }

    /**
     * Current lifecycle state.
     *
     * Generated from protobuf field <code>.api.zyins.v1.TokenStatus status = 8 [json_name = "status"];</code>
     * @return int one of the values in {@see \Sah\ZyINS\Api\V1\TokenStatus}
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Current lifecycle state.
     *
     * Generated from protobuf field <code>.api.zyins.v1.TokenStatus status = 8 [json_name = "status"];</code>
     * @param int $var one of the values in {@see \Sah\ZyINS\Api\V1\TokenStatus}
     * @return $this
     */
    public function setStatus(int $var)
    {
        GPBUtil::checkEnum($var, \Sah\ZyINS\Api\V1\TokenStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Reason recorded when the token was revoked or banned. Empty
     * otherwise.
     *
     * Generated from protobuf field <code>string revoked_reason = 9 [json_name = "revokedReason"];</code>
     * @return string
     */
    public function getRevokedReason()
    {
        return $this->revoked_reason;
    }

    /**
     * Reason recorded when the token was revoked or banned. Empty
     * otherwise.
     *
     * Generated from protobuf field <code>string revoked_reason = 9 [json_name = "revokedReason"];</code>
     * @param string $var
     * @return $this
     */
    public function setRevokedReason(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->revoked_reason = $var;

        return $this;
    }

    /**
     * RFC 3339 creation timestamp.
     *
     * Generated from protobuf field <code>string created_at = 10 [json_name = "createdAt"];</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * RFC 3339 creation timestamp.
     *
     * Generated from protobuf field <code>string created_at = 10 [json_name = "createdAt"];</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->created_at = $var;

        return $this;
    }

    /**
     * RFC 3339 expiry timestamp. Empty string means the token does not
     * expire.
     *
     * Generated from protobuf field <code>string expires_at = 11 [json_name = "expiresAt"];</code>
     * @return string
     */
    public function getExpiresAt()
    {
        return $this->expires_at;
    }

    /**
     * RFC 3339 expiry timestamp. Empty string means the token does not
     * expire.
     *
     * Generated from protobuf field <code>string expires_at = 11 [json_name = "expiresAt"];</code>
     * @param string $var
     * @return $this
     */
    public function setExpiresAt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->expires_at = $var;

        return $this;
    }

    /**
     * RFC 3339 revocation timestamp. Empty string if the token has never
     * been revoked.
     *
     * Generated from protobuf field <code>string revoked_at = 12 [json_name = "revokedAt"];</code>
     * @return string
     */
    public function getRevokedAt()
    {
        return $this->revoked_at;
    }

    /**
     * RFC 3339 revocation timestamp. Empty string if the token has never
     * been revoked.
     *
     * Generated from protobuf field <code>string revoked_at = 12 [json_name = "revokedAt"];</code>
     * @param string $var
     * @return $this
     */
    public function setRevokedAt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->revoked_at = $var;

        return $this;
    }

    /**
     * RFC 3339 timestamp of the most recent authenticated request made
     * with this token. Empty string if the token has never been used.
     *
     * Generated from protobuf field <code>string last_used_at = 13 [json_name = "lastUsedAt"];</code>
     * @return string
     */
    public function getLastUsedAt()
    {
        return $this->last_used_at;
    }

    /**
     * RFC 3339 timestamp of the most recent authenticated request made
     * with this token. Empty string if the token has never been used.
     *
     * Generated from protobuf field <code>string last_used_at = 13 [json_name = "lastUsedAt"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastUsedAt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->last_used_at = $var;

        return $this;
    }

    /**
     * RFC 3339 timestamp at which the sweeper will revoke this token.
     * Set when the token has been replaced via Rotate but its grace
     * window has not yet elapsed. Empty string when no rotation is
     * pending. Task #117 + #118.
     *
     * Generated from protobuf field <code>string revokes_at = 14 [json_name = "revokesAt"];</code>
     * @return string
     */
    public function getRevokesAt()
    {
        return $this->revokes_at;
    }

    /**
     * RFC 3339 timestamp at which the sweeper will revoke this token.
     * Set when the token has been replaced via Rotate but its grace
     * window has not yet elapsed. Empty string when no rotation is
     * pending. Task #117 + #118.
     *
     * Generated from protobuf field <code>string revokes_at = 14 [json_name = "revokesAt"];</code>
     * @param string $var
     * @return $this
     */
    public function setRevokesAt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->revokes_at = $var;

        return $this;
    }

}

