<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/preferences.proto

namespace Sah\ZyINS\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * WhitelabelPreferences is the server-typed shape of a customer's
 * agent-portal preferences. Every field is optional from the
 * customer's perspective; the server stores empty strings/arrays as
 * "not set". Unknown fields on the wire are rejected.
 * Adding a field is an additive change; removing or renaming a field
 * is breaking and requires a new package version.
 *
 * Generated from protobuf message <code>api.zyins.v1.WhitelabelPreferences</code>
 */
class WhitelabelPreferences extends \Google\Protobuf\Internal\Message
{
    /**
     * Hex color (e.g. `#1F2937`) for the agent-portal navigation chrome.
     *
     * Generated from protobuf field <code>string nav_color = 1 [json_name = "navColor"];</code>
     */
    protected $nav_color = '';
    /**
     * Hex color for primary call-to-action buttons and accents.
     *
     * Generated from protobuf field <code>string main_color = 2 [json_name = "mainColor"];</code>
     */
    protected $main_color = '';
    /**
     * Hex color for header text rendered against `nav_color`.
     *
     * Generated from protobuf field <code>string header_text_color = 3 [json_name = "headerTextColor"];</code>
     */
    protected $header_text_color = '';
    /**
     * Default values applied to new quote/case forms.
     *
     * Generated from protobuf field <code>.api.zyins.v1.DefaultSettings default_settings = 4 [json_name = "defaultSettings"];</code>
     */
    protected $default_settings = null;
    /**
     * Display name shown in the agent portal header. Optional.
     *
     * Generated from protobuf field <code>string display_name = 5 [json_name = "displayName"];</code>
     */
    protected $display_name = '';
    /**
     * Public contact email for the agency, surfaced in case emails.
     * Optional.
     *
     * Generated from protobuf field <code>string contact_email = 6 [json_name = "contactEmail"];</code>
     */
    protected $contact_email = '';
    /**
     * Public contact phone for the agency, surfaced in case emails.
     * Optional.
     *
     * Generated from protobuf field <code>string contact_phone = 7 [json_name = "contactPhone"];</code>
     */
    protected $contact_phone = '';
    /**
     * Logo image URL hosted on a customer-controlled origin. Optional.
     *
     * Generated from protobuf field <code>string logo_url = 8 [json_name = "logoUrl"];</code>
     */
    protected $logo_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $nav_color
     *           Hex color (e.g. `#1F2937`) for the agent-portal navigation chrome.
     *     @type string $main_color
     *           Hex color for primary call-to-action buttons and accents.
     *     @type string $header_text_color
     *           Hex color for header text rendered against `nav_color`.
     *     @type \Sah\ZyINS\Api\V1\DefaultSettings $default_settings
     *           Default values applied to new quote/case forms.
     *     @type string $display_name
     *           Display name shown in the agent portal header. Optional.
     *     @type string $contact_email
     *           Public contact email for the agency, surfaced in case emails.
     *           Optional.
     *     @type string $contact_phone
     *           Public contact phone for the agency, surfaced in case emails.
     *           Optional.
     *     @type string $logo_url
     *           Logo image URL hosted on a customer-controlled origin. Optional.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Preferences::initOnce();
        parent::__construct($data);
    }

    /**
     * Hex color (e.g. `#1F2937`) for the agent-portal navigation chrome.
     *
     * Generated from protobuf field <code>string nav_color = 1 [json_name = "navColor"];</code>
     * @return string
     */
    public function getNavColor()
    {
        return $this->nav_color;
    }

    /**
     * Hex color (e.g. `#1F2937`) for the agent-portal navigation chrome.
     *
     * Generated from protobuf field <code>string nav_color = 1 [json_name = "navColor"];</code>
     * @param string $var
     * @return $this
     */
    public function setNavColor(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->nav_color = $var;

        return $this;
    }

    /**
     * Hex color for primary call-to-action buttons and accents.
     *
     * Generated from protobuf field <code>string main_color = 2 [json_name = "mainColor"];</code>
     * @return string
     */
    public function getMainColor()
    {
        return $this->main_color;
    }

    /**
     * Hex color for primary call-to-action buttons and accents.
     *
     * Generated from protobuf field <code>string main_color = 2 [json_name = "mainColor"];</code>
     * @param string $var
     * @return $this
     */
    public function setMainColor(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->main_color = $var;

        return $this;
    }

    /**
     * Hex color for header text rendered against `nav_color`.
     *
     * Generated from protobuf field <code>string header_text_color = 3 [json_name = "headerTextColor"];</code>
     * @return string
     */
    public function getHeaderTextColor()
    {
        return $this->header_text_color;
    }

    /**
     * Hex color for header text rendered against `nav_color`.
     *
     * Generated from protobuf field <code>string header_text_color = 3 [json_name = "headerTextColor"];</code>
     * @param string $var
     * @return $this
     */
    public function setHeaderTextColor(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->header_text_color = $var;

        return $this;
    }

    /**
     * Default values applied to new quote/case forms.
     *
     * Generated from protobuf field <code>.api.zyins.v1.DefaultSettings default_settings = 4 [json_name = "defaultSettings"];</code>
     * @return \Sah\ZyINS\Api\V1\DefaultSettings|null
     */
    public function getDefaultSettings()
    {
        return $this->default_settings;
    }

    public function hasDefaultSettings()
    {
        return isset($this->default_settings);
    }

    public function clearDefaultSettings()
    {
        unset($this->default_settings);
    }

    /**
     * Default values applied to new quote/case forms.
     *
     * Generated from protobuf field <code>.api.zyins.v1.DefaultSettings default_settings = 4 [json_name = "defaultSettings"];</code>
     * @param \Sah\ZyINS\Api\V1\DefaultSettings $var
     * @return $this
     */
    public function setDefaultSettings(\Sah\ZyINS\Api\V1\DefaultSettings|null $var)
    {
        $this->default_settings = $var;

        return $this;
    }

    /**
     * Display name shown in the agent portal header. Optional.
     *
     * Generated from protobuf field <code>string display_name = 5 [json_name = "displayName"];</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Display name shown in the agent portal header. Optional.
     *
     * Generated from protobuf field <code>string display_name = 5 [json_name = "displayName"];</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->display_name = $var;

        return $this;
    }

    /**
     * Public contact email for the agency, surfaced in case emails.
     * Optional.
     *
     * Generated from protobuf field <code>string contact_email = 6 [json_name = "contactEmail"];</code>
     * @return string
     */
    public function getContactEmail()
    {
        return $this->contact_email;
    }

    /**
     * Public contact email for the agency, surfaced in case emails.
     * Optional.
     *
     * Generated from protobuf field <code>string contact_email = 6 [json_name = "contactEmail"];</code>
     * @param string $var
     * @return $this
     */
    public function setContactEmail(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->contact_email = $var;

        return $this;
    }

    /**
     * Public contact phone for the agency, surfaced in case emails.
     * Optional.
     *
     * Generated from protobuf field <code>string contact_phone = 7 [json_name = "contactPhone"];</code>
     * @return string
     */
    public function getContactPhone()
    {
        return $this->contact_phone;
    }

    /**
     * Public contact phone for the agency, surfaced in case emails.
     * Optional.
     *
     * Generated from protobuf field <code>string contact_phone = 7 [json_name = "contactPhone"];</code>
     * @param string $var
     * @return $this
     */
    public function setContactPhone(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->contact_phone = $var;

        return $this;
    }

    /**
     * Logo image URL hosted on a customer-controlled origin. Optional.
     *
     * Generated from protobuf field <code>string logo_url = 8 [json_name = "logoUrl"];</code>
     * @return string
     */
    public function getLogoUrl()
    {
        return $this->logo_url;
    }

    /**
     * Logo image URL hosted on a customer-controlled origin. Optional.
     *
     * Generated from protobuf field <code>string logo_url = 8 [json_name = "logoUrl"];</code>
     * @param string $var
     * @return $this
     */
    public function setLogoUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->logo_url = $var;

        return $this;
    }

}

