// Package api.isa.v1 holds the shared protobuf definitions reused across
// every ISA platform API surface (ZyINS, RapidSign, Proxy, future
// services). Per the SDK-consolidation plan, types that previously lived
// in `api.zyins.v1` and `api.rapidsign.v1` as duplicates have moved
// here so a single source of truth describes the platform-wide error
// model, OAuth-style scopes, and the shared health/readiness contract
// (see health.proto in this package).
//
// common.proto holds the RFC 7807 error model (ProblemDetails + ErrorCode)
// and the bearer-token Scope enumeration shared across products. The
// per-product JSON response Envelope type remains in each service's
// `common.proto` (e.g. api.zyins.v1.Envelope). Per-product enumerations
// (ProductClass, AccountStatus, LicenseStatus, ...) also stay in the
// owning service because they describe domain state, not platform
// contracts.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file api/isa/v1/common.proto (package api.isa.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/isa/v1/common.proto.
 */
export const file_api_isa_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChdhcGkvaXNhL3YxL2NvbW1vbi5wcm90bxIKYXBpLmlzYS52MSK4AQoOUHJvYmxlbURldGFpbHMSDAoEdHlwZRgBIAEoCRINCgV0aXRsZRgCIAEoCRIOCgZzdGF0dXMYAyABKAUSIwoEY29kZRgEIAEoDjIVLmFwaS5pc2EudjEuRXJyb3JDb2RlEg4KBmRldGFpbBgFIAEoCRIQCghpbnN0YW5jZRgGIAEoCRISCgpyZXF1ZXN0X2lkGAcgASgJEg0KBXBhcmFtGAggASgJEg8KB2RvY191cmwYCSABKAkq8wMKCUVycm9yQ29kZRIaChZFUlJPUl9DT0RFX1VOU1BFQ0lGSUVEEAASGwoXRVJST1JfQ09ERV9VTkFVVEhPUklaRUQQARIcChhFUlJPUl9DT0RFX1RPS0VOX0VYUElSRUQQAhIcChhFUlJPUl9DT0RFX0lOVkFMSURfVE9LRU4QAxIYChRFUlJPUl9DT0RFX0ZPUkJJRERFThAEEhgKFEVSUk9SX0NPREVfTk9UX0ZPVU5EEAUSIQodRVJST1JfQ09ERV9NRVRIT0RfTk9UX0FMTE9XRUQQBhIXChNFUlJPUl9DT0RFX0NPTkZMSUNUEAcSHwobRVJST1JfQ09ERV9WQUxJREFUSU9OX0VSUk9SEAgSHQoZRVJST1JfQ09ERV9MSUNFTlNFX0xPQ0tFRBAJEiIKHkVSUk9SX0NPREVfUkFURV9MSU1JVF9FWENFRURFRBAKEh0KGUVSUk9SX0NPREVfSU5URVJOQUxfRVJST1IQCxIaChZFUlJPUl9DT0RFX0JBRF9HQVRFV0FZEAwSHgoaRVJST1JfQ09ERV9HQVRFV0FZX1RJTUVPVVQQDRIiCh5FUlJPUl9DT0RFX1NFUlZJQ0VfVU5BVkFJTEFCTEUQDhIeChpFUlJPUl9DT0RFX05PVF9JTVBMRU1FTlRFRBAPKrEBCgVTY29wZRIVChFTQ09QRV9VTlNQRUNJRklFRBAAEiMKH1NDT1BFX1JBUElEU0lHTl9ET0NVTUVOVFNfV1JJVEUQARIiCh5TQ09QRV9SQVBJRFNJR05fRE9DVU1FTlRTX1JFQUQQAhIiCh5TQ09QRV9SQVBJRFNJR05fRE9DVU1FTlRTX1NJR04QAxIkCiBTQ09QRV9SQVBJRFNJR05fRE9DVU1FTlRTX05PVElGWRAEQrcBCg5jb20uYXBpLmlzYS52MUILQ29tbW9uUHJvdG9QAVpFZ2l0aHViLmNvbS9Tb2Z0d2FyZS1BdXRvbWF0aW9uLUhvbGRpbmdzLUxMQy9zZGsvY29yZS9hcGkvaXNhL3YxO2lzYXYxogIDQUlYqgISSXNhU2RrLkNvcmUuQXBpLlYxygIOU2FoXElzYVxBcGlcVjHiAhNTYWhcSXNhXEFwaVxWMVxNZXRh6gIMQXBpOjpJc2E6OlYxYgZwcm90bzM");

/**
 * ProblemDetails is the RFC 7807 error body extended with three
 * machine-readable fields per ADR-012. Programmatic consumers MUST
 * switch on `code`; `type` is preserved for RFC compliance but is not
 * the match surface.
 *
 * @generated from message api.isa.v1.ProblemDetails
 */
export type ProblemDetails = Message<"api.isa.v1.ProblemDetails"> & {
  /**
   * A URI reference that identifies the problem type per RFC 7807.
   * Stable across API versions but not the primary match key — use
   * `code` instead.
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * Short human-readable summary. May change without notice.
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * HTTP status code.
   *
   * @generated from field: int32 status = 3;
   */
  status: number;

  /**
   * Stable machine-readable error code. Never renamed once shipped;
   * deprecated codes are dual-written for 6 months alongside
   * replacements.
   *
   * @generated from field: api.isa.v1.ErrorCode code = 4;
   */
  code: ErrorCode;

  /**
   * Human-readable explanation specific to this occurrence.
   *
   * @generated from field: string detail = 5;
   */
  detail: string;

  /**
   * Request path that generated this error.
   *
   * @generated from field: string instance = 6;
   */
  instance: string;

  /**
   * Unique request identifier for support and debugging.
   *
   * @generated from field: string request_id = 7;
   */
  requestId: string;

  /**
   * JSON-pointer-style path to the field that failed validation.
   * Omitted entirely for non-validation errors.
   *
   * @generated from field: string param = 8;
   */
  param: string;

  /**
   * Link to the docs page explaining this error and its remediation.
   *
   * @generated from field: string doc_url = 9;
   */
  docUrl: string;
};

/**
 * Describes the message api.isa.v1.ProblemDetails.
 * Use `create(ProblemDetailsSchema)` to create a new message.
 */
export const ProblemDetailsSchema: GenMessage<ProblemDetails> = /*@__PURE__*/
  messageDesc(file_api_isa_v1_common, 0);

/**
 * ErrorCode enumerates the stable error codes consumers may switch on.
 * Values are lowercase snake_case at the wire level. Additions are
 * non-breaking; renames are forbidden.
 *
 * This is the union of every error code previously defined per service.
 * Values 0-8 matched both legacy catalogs. From 9 onward the numeric
 * assignments follow the former ZyINS layout (including LICENSE_LOCKED at
 * 9). Legacy RapidSign emitted RATE_LIMIT_EXCEEDED as 9 and
 * NOT_IMPLEMENTED as 10; those semantics now wire as 10 and 15
 * respectively. Pre-1.0 consolidation: treat any cross-service numeric
 * error code migration as an explicit consumer update, not a silent
 * rename. New services must add missing codes here rather than locally.
 *
 * @generated from enum api.isa.v1.ErrorCode
 */
export enum ErrorCode {
  /**
   * Default zero value. Never emitted by the server; indicates a proto
   * deserialization defect on the client side.
   *
   * @generated from enum value: ERROR_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Authentication required or credentials invalid.
   *
   * @generated from enum value: ERROR_CODE_UNAUTHORIZED = 1;
   */
  UNAUTHORIZED = 1,

  /**
   * Bearer token or license has expired. Client should refresh.
   *
   * @generated from enum value: ERROR_CODE_TOKEN_EXPIRED = 2;
   */
  TOKEN_EXPIRED = 2,

  /**
   * Bearer token or license signature does not validate.
   *
   * @generated from enum value: ERROR_CODE_INVALID_TOKEN = 3;
   */
  INVALID_TOKEN = 3,

  /**
   * Authenticated but lacking scope for this operation.
   *
   * @generated from enum value: ERROR_CODE_FORBIDDEN = 4;
   */
  FORBIDDEN = 4,

  /**
   * Resource does not exist or is not visible to the caller.
   *
   * @generated from enum value: ERROR_CODE_NOT_FOUND = 5;
   */
  NOT_FOUND = 5,

  /**
   * HTTP method not allowed on this path.
   *
   * @generated from enum value: ERROR_CODE_METHOD_NOT_ALLOWED = 6;
   */
  METHOD_NOT_ALLOWED = 6,

  /**
   * State conflict (e.g. already activated, already revoked,
   * document already signed).
   *
   * @generated from enum value: ERROR_CODE_CONFLICT = 7;
   */
  CONFLICT = 7,

  /**
   * Request body failed schema or domain validation. `param` is set.
   *
   * @generated from enum value: ERROR_CODE_VALIDATION_ERROR = 8;
   */
  VALIDATION_ERROR = 8,

  /**
   * License is locked (too many device registrations or admin action).
   *
   * @generated from enum value: ERROR_CODE_LICENSE_LOCKED = 9;
   */
  LICENSE_LOCKED = 9,

  /**
   * Rate limit exceeded. `Retry-After` header is set.
   *
   * @generated from enum value: ERROR_CODE_RATE_LIMIT_EXCEEDED = 10;
   */
  RATE_LIMIT_EXCEEDED = 10,

  /**
   * Unhandled server fault. Request ID identifies the log entry.
   *
   * @generated from enum value: ERROR_CODE_INTERNAL_ERROR = 11;
   */
  INTERNAL_ERROR = 11,

  /**
   * Upstream dependency returned an unusable response.
   *
   * @generated from enum value: ERROR_CODE_BAD_GATEWAY = 12;
   */
  BAD_GATEWAY = 12,

  /**
   * Upstream dependency did not respond within the budget.
   *
   * @generated from enum value: ERROR_CODE_GATEWAY_TIMEOUT = 13;
   */
  GATEWAY_TIMEOUT = 13,

  /**
   * Service is intentionally unavailable (draining, maintenance).
   *
   * @generated from enum value: ERROR_CODE_SERVICE_UNAVAILABLE = 14;
   */
  SERVICE_UNAVAILABLE = 14,

  /**
   * Capability not yet implemented (e.g. PDF renderer not configured).
   *
   * @generated from enum value: ERROR_CODE_NOT_IMPLEMENTED = 15;
   */
  NOT_IMPLEMENTED = 15,
}

/**
 * Describes the enum api.isa.v1.ErrorCode.
 */
export const ErrorCodeSchema: GenEnum<ErrorCode> = /*@__PURE__*/
  enumDesc(file_api_isa_v1_common, 0);

/**
 * Scope enumerates the bearer-token scopes recognized across the ISA
 * platform. Enum member names gained a `RAPIDSIGN_` prefix so additional
 * services can add scopes without colliding; wire integers for the four
 * RapidSign scopes are unchanged from the legacy `SCOPE_DOCUMENTS_*`
 * assignments. Generated symbol names therefore change — migrate callers
 * when regenerating SDKs.
 *
 * @generated from enum api.isa.v1.Scope
 */
export enum Scope {
  /**
   * Default zero value. Never emitted.
   *
   * @generated from enum value: SCOPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * `rapidsign:documents:write` — create new documents.
   *
   * @generated from enum value: SCOPE_RAPIDSIGN_DOCUMENTS_WRITE = 1;
   */
  RAPIDSIGN_DOCUMENTS_WRITE = 1,

  /**
   * `rapidsign:documents:read` — fetch signature state and signed PDFs.
   *
   * @generated from enum value: SCOPE_RAPIDSIGN_DOCUMENTS_READ = 2;
   */
  RAPIDSIGN_DOCUMENTS_READ = 2,

  /**
   * `rapidsign:documents:sign` — submit signatures.
   *
   * @generated from enum value: SCOPE_RAPIDSIGN_DOCUMENTS_SIGN = 3;
   */
  RAPIDSIGN_DOCUMENTS_SIGN = 3,

  /**
   * `rapidsign:documents:notify` — send signer notification emails.
   *
   * @generated from enum value: SCOPE_RAPIDSIGN_DOCUMENTS_NOTIFY = 4;
   */
  RAPIDSIGN_DOCUMENTS_NOTIFY = 4,
}

/**
 * Describes the enum api.isa.v1.Scope.
 */
export const ScopeSchema: GenEnum<Scope> = /*@__PURE__*/
  enumDesc(file_api_isa_v1_common, 1);

