// health.proto defines the shared observability surface every ISA
// platform service exposes: a liveness probe (`/health`) and a
// readiness probe (`/ready`).
//
// The liveness probe reports in-process state only. It MUST NOT touch
// the database, the cache, or any network dependency; a failure means
// the process should be restarted.
//
// The readiness probe reports whether the service can serve real
// traffic right now. The shared ReadinessResponse below carries the
// canonical two typed probes (fields 3–4), a keyed map for additional
// downstream checks (field 5), and the evaluation timestamp (field 6).
// Service-specific handlers populate the typed slots with whichever
// dependencies they probe; wire numbers stay stable across products.
//
// Both endpoints return HTTP 200 with a typed response body when
// healthy. A failing liveness or readiness check returns HTTP 503 with
// a ProblemDetails body (see common.proto).

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file api/isa/v1/health.proto (package api.isa.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/isa/v1/health.proto.
 */
export const file_api_isa_v1_health: GenFile = /*@__PURE__*/
  fileDesc("ChdhcGkvaXNhL3YxL2hlYWx0aC5wcm90bxIKYXBpLmlzYS52MSISChBHZXRIZWFsdGhSZXF1ZXN0Io8BCg5IZWFsdGhSZXNwb25zZRIpCgZzdGF0dXMYASABKA4yGS5hcGkuaXNhLnYxLlNlcnZpbmdTdGF0dXMSDwoHdmVyc2lvbhgCIAEoCRIRCglidWlsZF9zaGEYAyABKAkSLgoKc3RhcnRlZF9hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiFQoTR2V0UmVhZGluZXNzUmVxdWVzdCLyAgoRUmVhZGluZXNzUmVzcG9uc2USDQoFcmVhZHkYASABKAgSKQoGc3RhdHVzGAIgASgOMhkuYXBpLmlzYS52MS5TZXJ2aW5nU3RhdHVzEiMKAmRiGAMgASgLMhcuYXBpLmlzYS52MS5Qcm9iZVJlc3VsdBImCgVjYWNoZRgEIAEoCzIXLmFwaS5pc2EudjEuUHJvYmVSZXN1bHQSUgoTZG93bnN0cmVhbV9zZXJ2aWNlcxgFIAMoCzI1LmFwaS5pc2EudjEuUmVhZGluZXNzUmVzcG9uc2UuRG93bnN0cmVhbVNlcnZpY2VzRW50cnkSLgoKY2hlY2tlZF9hdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAaUgoXRG93bnN0cmVhbVNlcnZpY2VzRW50cnkSCwoDa2V5GAEgASgJEiYKBXZhbHVlGAIgASgLMhcuYXBpLmlzYS52MS5Qcm9iZVJlc3VsdDoCOAEijQEKC1Byb2JlUmVzdWx0EikKBnN0YXR1cxgBIAEoDjIZLmFwaS5pc2EudjEuU2VydmluZ1N0YXR1cxISCgpsYXRlbmN5X21zGAIgASgDEg8KB21lc3NhZ2UYAyABKAkSLgoKY2hlY2tlZF9hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAieAoQTGl2ZW5lc3NSZXNwb25zZRIzCgZzdGF0dXMYASABKA4yIy5hcGkuaXNhLnYxLkxpdmVuZXNzUmVzcG9uc2UuU3RhdHVzIi8KBlN0YXR1cxIWChJTVEFUVVNfVU5TUEVDSUZJRUQQABINCglTVEFUVVNfT0sQASqHAQoNU2VydmluZ1N0YXR1cxIeChpTRVJWSU5HX1NUQVRVU19VTlNQRUNJRklFRBAAEhoKFlNFUlZJTkdfU1RBVFVTX1NFUlZJTkcQARIeChpTRVJWSU5HX1NUQVRVU19OT1RfU0VSVklORxACEhoKFlNFUlZJTkdfU1RBVFVTX1VOS05PV04QAzLHAQoNSGVhbHRoU2VydmljZRJWCglHZXRIZWFsdGgSHC5hcGkuaXNhLnYxLkdldEhlYWx0aFJlcXVlc3QaGi5hcGkuaXNhLnYxLkhlYWx0aFJlc3BvbnNlIg+C0+STAgkSBy9oZWFsdGgSXgoMR2V0UmVhZGluZXNzEh8uYXBpLmlzYS52MS5HZXRSZWFkaW5lc3NSZXF1ZXN0Gh0uYXBpLmlzYS52MS5SZWFkaW5lc3NSZXNwb25zZSIOgtPkkwIIEgYvcmVhZHlCtwEKDmNvbS5hcGkuaXNhLnYxQgtIZWFsdGhQcm90b1ABWkVnaXRodWIuY29tL1NvZnR3YXJlLUF1dG9tYXRpb24tSG9sZGluZ3MtTExDL3Nkay9jb3JlL2FwaS9pc2EvdjE7aXNhdjGiAgNBSViqAhJJc2FTZGsuQ29yZS5BcGkuVjHKAg5TYWhcSXNhXEFwaVxWMeICE1NhaFxJc2FcQXBpXFYxXE1ldGHqAgxBcGk6OklzYTo6VjFiBnByb3RvMw", [file_google_api_annotations, file_google_protobuf_timestamp]);

/**
 * GetHealthRequest is the empty request body for GET /health.
 *
 * @generated from message api.isa.v1.GetHealthRequest
 */
export type GetHealthRequest = Message<"api.isa.v1.GetHealthRequest"> & {
};

/**
 * Describes the message api.isa.v1.GetHealthRequest.
 * Use `create(GetHealthRequestSchema)` to create a new message.
 */
export const GetHealthRequestSchema: GenMessage<GetHealthRequest> = /*@__PURE__*/
  messageDesc(file_api_isa_v1_health, 0);

/**
 * HealthResponse reports liveness (in-process state only). Emitted with
 * HTTP 200; a failing probe returns ProblemDetails on HTTP 503 instead.
 *
 * @generated from message api.isa.v1.HealthResponse
 */
export type HealthResponse = Message<"api.isa.v1.HealthResponse"> & {
  /**
   * Overall liveness status. On HTTP 200 this is always `SERVING`.
   *
   * @generated from field: api.isa.v1.ServingStatus status = 1;
   */
  status: ServingStatus;

  /**
   * Semantic version of the running binary (e.g. `1.42.0`). Matches
   * the git tag when deployed from a release; empty for local builds.
   *
   * @generated from field: string version = 2;
   */
  version: string;

  /**
   * Full git commit SHA the binary was built from. Echoed into logs
   * and used by support to correlate behaviour with a revision.
   *
   * @generated from field: string build_sha = 3;
   */
  buildSha: string;

  /**
   * Wall-clock time at which the process started accepting requests.
   * Paired with the current time to compute uptime client-side.
   *
   * @generated from field: google.protobuf.Timestamp started_at = 4;
   */
  startedAt?: Timestamp | undefined;
};

/**
 * Describes the message api.isa.v1.HealthResponse.
 * Use `create(HealthResponseSchema)` to create a new message.
 */
export const HealthResponseSchema: GenMessage<HealthResponse> = /*@__PURE__*/
  messageDesc(file_api_isa_v1_health, 1);

/**
 * GetReadinessRequest is the empty request body for GET /ready.
 *
 * @generated from message api.isa.v1.GetReadinessRequest
 */
export type GetReadinessRequest = Message<"api.isa.v1.GetReadinessRequest"> & {
};

/**
 * Describes the message api.isa.v1.GetReadinessRequest.
 * Use `create(GetReadinessRequestSchema)` to create a new message.
 */
export const GetReadinessRequestSchema: GenMessage<GetReadinessRequest> = /*@__PURE__*/
  messageDesc(file_api_isa_v1_health, 2);

/**
 * ReadinessResponse is the shared readiness body. Field numbers 1–6
 * match the historical ZyINS layout so existing binary decoders stay
 * compatible; JSON field names for the two typed probes may differ from
 * legacy RapidSign (`storage` / `emailer`) — callers must migrate to the
 * unified keys (`db` / `cache`) alongside this consolidation.
 *
 * @generated from message api.isa.v1.ReadinessResponse
 */
export type ReadinessResponse = Message<"api.isa.v1.ReadinessResponse"> & {
  /**
   * Overall readiness decision. True iff every required sub-probe
   * returned `SERVING`. A single `NOT_SERVING` among the required
   * probes flips this to false and the endpoint returns 503.
   *
   * @generated from field: bool ready = 1;
   */
  ready: boolean;

  /**
   * Overall status mirror of `ready` using the shared enum. Clients
   * that switch on `ServingStatus` across endpoints should read this
   * field; `ready` is retained for simple boolean checks.
   *
   * @generated from field: api.isa.v1.ServingStatus status = 2;
   */
  status: ServingStatus;

  /**
   * Primary dependency probe (ZyINS: database pool; RapidSign: document
   * storage). Same wire type across products; name reflects the ZyINS
   * canonical field label.
   *
   * @generated from field: api.isa.v1.ProbeResult db = 3;
   */
  db?: ProbeResult | undefined;

  /**
   * Secondary dependency probe (ZyINS: cache; RapidSign: emailer).
   *
   * @generated from field: api.isa.v1.ProbeResult cache = 4;
   */
  cache?: ProbeResult | undefined;

  /**
   * Additional downstream probes keyed by logical service name (e.g.
   * `accounts`, `billing`, `eapp`). Order is not significant.
   *
   * @generated from field: map<string, api.isa.v1.ProbeResult> downstream_services = 5;
   */
  downstreamServices: { [key: string]: ProbeResult };

  /**
   * Wall-clock time at which this readiness evaluation ran.
   *
   * @generated from field: google.protobuf.Timestamp checked_at = 6;
   */
  checkedAt?: Timestamp | undefined;
};

/**
 * Describes the message api.isa.v1.ReadinessResponse.
 * Use `create(ReadinessResponseSchema)` to create a new message.
 */
export const ReadinessResponseSchema: GenMessage<ReadinessResponse> = /*@__PURE__*/
  messageDesc(file_api_isa_v1_health, 3);

/**
 * ProbeResult is the per-dependency readiness outcome. Carried inside
 * every readiness response across the platform.
 *
 * @generated from message api.isa.v1.ProbeResult
 */
export type ProbeResult = Message<"api.isa.v1.ProbeResult"> & {
  /**
   * Current serving status of this dependency.
   *
   * @generated from field: api.isa.v1.ServingStatus status = 1;
   */
  status: ServingStatus;

  /**
   * Observed round-trip latency of the probe in milliseconds. Zero
   * when the probe could not complete (status == NOT_SERVING with a
   * synchronous failure or UNKNOWN with a timeout).
   *
   * @generated from field: int64 latency_ms = 2;
   */
  latencyMs: bigint;

  /**
   * Human-readable explanation when `status` is not `SERVING`. Empty
   * on a healthy probe. Intended for operator dashboards; programmatic
   * consumers must switch on `status`, not parse this string.
   *
   * @generated from field: string message = 3;
   */
  message: string;

  /**
   * Wall-clock time at which this specific probe was evaluated.
   *
   * @generated from field: google.protobuf.Timestamp checked_at = 4;
   */
  checkedAt?: Timestamp | undefined;
};

/**
 * Describes the message api.isa.v1.ProbeResult.
 * Use `create(ProbeResultSchema)` to create a new message.
 */
export const ProbeResultSchema: GenMessage<ProbeResult> = /*@__PURE__*/
  messageDesc(file_api_isa_v1_health, 4);

/**
 * LivenessResponse is the minimal success body for GET /health and GET
 * /ready per the platform health/readiness contract. Body is exactly
 * {"status":"ok"}.
 *
 * @generated from message api.isa.v1.LivenessResponse
 */
export type LivenessResponse = Message<"api.isa.v1.LivenessResponse"> & {
  /**
   * Liveness/readiness state. Only `ok` is ever emitted on success; a
   * failing probe returns ProblemDetails on HTTP 503 instead.
   *
   * @generated from field: api.isa.v1.LivenessResponse.Status status = 1;
   */
  status: LivenessResponse_Status;
};

/**
 * Describes the message api.isa.v1.LivenessResponse.
 * Use `create(LivenessResponseSchema)` to create a new message.
 */
export const LivenessResponseSchema: GenMessage<LivenessResponse> = /*@__PURE__*/
  messageDesc(file_api_isa_v1_health, 5);

/**
 * Status enumerates the probe outcomes. Exists inside the message so
 * the wire type is unambiguously scoped to the liveness contract.
 *
 * @generated from enum api.isa.v1.LivenessResponse.Status
 */
export enum LivenessResponse_Status {
  /**
   * Default zero value. Never emitted.
   *
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Process is alive (liveness) or ready to serve traffic (readiness).
   *
   * @generated from enum value: STATUS_OK = 1;
   */
  OK = 1,
}

/**
 * Describes the enum api.isa.v1.LivenessResponse.Status.
 */
export const LivenessResponse_StatusSchema: GenEnum<LivenessResponse_Status> = /*@__PURE__*/
  enumDesc(file_api_isa_v1_health, 5, 0);

/**
 * ServingStatus enumerates the probe outcomes shared by the liveness
 * and readiness responses. Wire values are lowercase
 * (`serving`, `not_serving`, `unknown`).
 *
 * @generated from enum api.isa.v1.ServingStatus
 */
export enum ServingStatus {
  /**
   * Default zero value. Never emitted by the server; indicates a proto
   * deserialization defect on the client side.
   *
   * @generated from enum value: SERVING_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Component is healthy and accepting traffic.
   *
   * @generated from enum value: SERVING_STATUS_SERVING = 1;
   */
  SERVING = 1,

  /**
   * Component is unhealthy; the overall probe returns 503 via
   * ProblemDetails when any required component is in this state.
   *
   * @generated from enum value: SERVING_STATUS_NOT_SERVING = 2;
   */
  NOT_SERVING = 2,

  /**
   * Component state could not be determined within the probe budget
   * (e.g. timeout without a definitive success or failure).
   *
   * @generated from enum value: SERVING_STATUS_UNKNOWN = 3;
   */
  UNKNOWN = 3,
}

/**
 * Describes the enum api.isa.v1.ServingStatus.
 */
export const ServingStatusSchema: GenEnum<ServingStatus> = /*@__PURE__*/
  enumDesc(file_api_isa_v1_health, 0);

/**
 * HealthService groups the liveness and readiness probes. Both RPCs are
 * unauthenticated per the platform health/readiness contract; load
 * balancers and container orchestrators must be able to probe without
 * credentials.
 *
 * @generated from service api.isa.v1.HealthService
 */
export const HealthService: GenService<{
  /**
   * GetHealth is the liveness probe. Verifies in-process state only
   * (binary loaded, request loop running). Does NOT touch the database,
   * the cache, or any downstream dependency. A 503 here means the
   * process should be restarted.
   *
   * @generated from rpc api.isa.v1.HealthService.GetHealth
   */
  getHealth: {
    methodKind: "unary";
    input: typeof GetHealthRequestSchema;
    output: typeof HealthResponseSchema;
  },
  /**
   * GetReadiness is the readiness probe. Exercises every dependency
   * required to serve a real user request. A 503 here drains traffic
   * without restarting the task. Implementations populate the shared
   * ReadinessResponse fields defined in this package.
   *
   * @generated from rpc api.isa.v1.HealthService.GetReadiness
   */
  getReadiness: {
    methodKind: "unary";
    input: typeof GetReadinessRequestSchema;
    output: typeof ReadinessResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_isa_v1_health, 0);

