<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/proxy/v1/proxy.proto

namespace Sah\Proxy\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * AlgosureAuth carries the inbound HMAC envelope the caller signed.
 * The wire headers `*Host`, `*Timestamp`, `*sessionId` map to the
 * `scope_host`, `timestamp`, and `session_id` fields respectively;
 * `authorization` maps to the standard `Authorization` header.
 *
 * Generated from protobuf message <code>api.proxy.v1.AlgosureAuth</code>
 */
class AlgosureAuth extends \Google\Protobuf\Internal\Message
{
    /**
     * Authorization is the literal value of the inbound `Authorization`
     * header (the full `Algosure-HMAC-SHA256 ...` string).
     *
     * Generated from protobuf field <code>string authorization = 1 [json_name = "authorization"];</code>
     */
    protected $authorization = '';
    /**
     * ScopeHost is the Algosure salt-serving scope host — the logical
     * scope the caller is operating against, as carried in the inbound
     * `*Host` header. Distinct from `Target.host`, which is the upstream
     * API hostname the proxy dials. Field number 2 is preserved from
     * the prior `host` name; the rename is source-only.
     *
     * Generated from protobuf field <code>string scope_host = 2 [json_name = "scopeHost"];</code>
     */
    protected $scope_host = '';
    /**
     * Timestamp is the value of the inbound `*Timestamp` header — the
     * RFC3339 wall-clock time the signature was computed.
     *
     * Generated from protobuf field <code>string timestamp = 3 [json_name = "timestamp"];</code>
     */
    protected $timestamp = '';
    /**
     * SessionId is the value of the inbound `*sessionId` header — a
     * caller-chosen opaque token bound into the signature to defeat
     * replay across sessions.
     *
     * Generated from protobuf field <code>string session_id = 4 [json_name = "sessionId"];</code>
     */
    protected $session_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $authorization
     *           Authorization is the literal value of the inbound `Authorization`
     *           header (the full `Algosure-HMAC-SHA256 ...` string).
     *     @type string $scope_host
     *           ScopeHost is the Algosure salt-serving scope host — the logical
     *           scope the caller is operating against, as carried in the inbound
     *           `*Host` header. Distinct from `Target.host`, which is the upstream
     *           API hostname the proxy dials. Field number 2 is preserved from
     *           the prior `host` name; the rename is source-only.
     *     @type string $timestamp
     *           Timestamp is the value of the inbound `*Timestamp` header — the
     *           RFC3339 wall-clock time the signature was computed.
     *     @type string $session_id
     *           SessionId is the value of the inbound `*sessionId` header — a
     *           caller-chosen opaque token bound into the signature to defeat
     *           replay across sessions.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\Proxy\Api\V1\Meta\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Authorization is the literal value of the inbound `Authorization`
     * header (the full `Algosure-HMAC-SHA256 ...` string).
     *
     * Generated from protobuf field <code>string authorization = 1 [json_name = "authorization"];</code>
     * @return string
     */
    public function getAuthorization()
    {
        return $this->authorization;
    }

    /**
     * Authorization is the literal value of the inbound `Authorization`
     * header (the full `Algosure-HMAC-SHA256 ...` string).
     *
     * Generated from protobuf field <code>string authorization = 1 [json_name = "authorization"];</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorization(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->authorization = $var;

        return $this;
    }

    /**
     * ScopeHost is the Algosure salt-serving scope host — the logical
     * scope the caller is operating against, as carried in the inbound
     * `*Host` header. Distinct from `Target.host`, which is the upstream
     * API hostname the proxy dials. Field number 2 is preserved from
     * the prior `host` name; the rename is source-only.
     *
     * Generated from protobuf field <code>string scope_host = 2 [json_name = "scopeHost"];</code>
     * @return string
     */
    public function getScopeHost()
    {
        return $this->scope_host;
    }

    /**
     * ScopeHost is the Algosure salt-serving scope host — the logical
     * scope the caller is operating against, as carried in the inbound
     * `*Host` header. Distinct from `Target.host`, which is the upstream
     * API hostname the proxy dials. Field number 2 is preserved from
     * the prior `host` name; the rename is source-only.
     *
     * Generated from protobuf field <code>string scope_host = 2 [json_name = "scopeHost"];</code>
     * @param string $var
     * @return $this
     */
    public function setScopeHost(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->scope_host = $var;

        return $this;
    }

    /**
     * Timestamp is the value of the inbound `*Timestamp` header — the
     * RFC3339 wall-clock time the signature was computed.
     *
     * Generated from protobuf field <code>string timestamp = 3 [json_name = "timestamp"];</code>
     * @return string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Timestamp is the value of the inbound `*Timestamp` header — the
     * RFC3339 wall-clock time the signature was computed.
     *
     * Generated from protobuf field <code>string timestamp = 3 [json_name = "timestamp"];</code>
     * @param string $var
     * @return $this
     */
    public function setTimestamp(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * SessionId is the value of the inbound `*sessionId` header — a
     * caller-chosen opaque token bound into the signature to defeat
     * replay across sessions.
     *
     * Generated from protobuf field <code>string session_id = 4 [json_name = "sessionId"];</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * SessionId is the value of the inbound `*sessionId` header — a
     * caller-chosen opaque token bound into the signature to defeat
     * replay across sessions.
     *
     * Generated from protobuf field <code>string session_id = 4 [json_name = "sessionId"];</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->session_id = $var;

        return $this;
    }

}

