<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/proxy/v1/proxy.proto

namespace Sah\Proxy\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * CallResponse echoes the upstream response verbatim. The proxy does
 * not interpret the body — pass-through is the contract — but it does
 * surface the upstream HTTP status and forwarded headers so callers
 * can react without parsing the body.
 *
 * Generated from protobuf message <code>api.proxy.v1.CallResponse</code>
 */
class CallResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Status is the upstream HTTP status code.
     *
     * Generated from protobuf field <code>int32 status = 1 [json_name = "status"];</code>
     */
    protected $status = 0;
    /**
     * Body is the raw upstream response body forwarded unchanged.
     *
     * Generated from protobuf field <code>bytes body = 2 [json_name = "body"];</code>
     */
    protected $body = '';
    /**
     * Headers is the upstream response header set after the proxy's
     * egress filter (Set-Cookie and other sensitive headers stripped).
     * Keys are lowercased; duplicate header values are joined with `, `.
     *
     * Generated from protobuf field <code>map<string, string> headers = 3 [json_name = "headers"];</code>
     */
    private $headers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *           Status is the upstream HTTP status code.
     *     @type string $body
     *           Body is the raw upstream response body forwarded unchanged.
     *     @type array|\Google\Protobuf\Internal\MapField $headers
     *           Headers is the upstream response header set after the proxy's
     *           egress filter (Set-Cookie and other sensitive headers stripped).
     *           Keys are lowercased; duplicate header values are joined with `, `.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\Proxy\Api\V1\Meta\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Status is the upstream HTTP status code.
     *
     * Generated from protobuf field <code>int32 status = 1 [json_name = "status"];</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Status is the upstream HTTP status code.
     *
     * Generated from protobuf field <code>int32 status = 1 [json_name = "status"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatus(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Body is the raw upstream response body forwarded unchanged.
     *
     * Generated from protobuf field <code>bytes body = 2 [json_name = "body"];</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Body is the raw upstream response body forwarded unchanged.
     *
     * Generated from protobuf field <code>bytes body = 2 [json_name = "body"];</code>
     * @param string $var
     * @return $this
     */
    public function setBody(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->body = $var;

        return $this;
    }

    /**
     * Headers is the upstream response header set after the proxy's
     * egress filter (Set-Cookie and other sensitive headers stripped).
     * Keys are lowercased; duplicate header values are joined with `, `.
     *
     * Generated from protobuf field <code>map<string, string> headers = 3 [json_name = "headers"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Headers is the upstream response header set after the proxy's
     * egress filter (Set-Cookie and other sensitive headers stripped).
     * Keys are lowercased; duplicate header values are joined with `, `.
     *
     * Generated from protobuf field <code>map<string, string> headers = 3 [json_name = "headers"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHeaders(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->headers = $arr;

        return $this;
    }

}

