<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/proxy/v1/proxy.proto

namespace Sah\Proxy\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Target identifies the upstream endpoint a Call dispatches to.
 * Stripe-style snake_case at the wire level.
 *
 * Generated from protobuf message <code>api.proxy.v1.Target</code>
 */
class Target extends \Google\Protobuf\Internal\Message
{
    /**
     * Host is the upstream hostname (no scheme, no path). Subject to the
     * per-integration allowlist; a host outside the allowlist returns
     * HTTP 403 with `ErrorCode` set to `ERROR_CODE_FORBIDDEN` in the
     * ProblemDetails payload.
     *
     * Generated from protobuf field <code>string host = 1 [json_name = "host"];</code>
     */
    protected $host = '';
    /**
     * Method is the HTTP method to use (e.g. `POST`, `GET`). Overrides
     * the integration's default method when set.
     *
     * Generated from protobuf field <code>string method = 2 [json_name = "method"];</code>
     */
    protected $method = '';
    /**
     * Path is the upstream request path (URL-decoded, leading slash).
     *
     * Generated from protobuf field <code>string path = 3 [json_name = "path"];</code>
     */
    protected $path = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $host
     *           Host is the upstream hostname (no scheme, no path). Subject to the
     *           per-integration allowlist; a host outside the allowlist returns
     *           HTTP 403 with `ErrorCode` set to `ERROR_CODE_FORBIDDEN` in the
     *           ProblemDetails payload.
     *     @type string $method
     *           Method is the HTTP method to use (e.g. `POST`, `GET`). Overrides
     *           the integration's default method when set.
     *     @type string $path
     *           Path is the upstream request path (URL-decoded, leading slash).
     * }
     */
    public function __construct($data = NULL) {
        \Sah\Proxy\Api\V1\Meta\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Host is the upstream hostname (no scheme, no path). Subject to the
     * per-integration allowlist; a host outside the allowlist returns
     * HTTP 403 with `ErrorCode` set to `ERROR_CODE_FORBIDDEN` in the
     * ProblemDetails payload.
     *
     * Generated from protobuf field <code>string host = 1 [json_name = "host"];</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Host is the upstream hostname (no scheme, no path). Subject to the
     * per-integration allowlist; a host outside the allowlist returns
     * HTTP 403 with `ErrorCode` set to `ERROR_CODE_FORBIDDEN` in the
     * ProblemDetails payload.
     *
     * Generated from protobuf field <code>string host = 1 [json_name = "host"];</code>
     * @param string $var
     * @return $this
     */
    public function setHost(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->host = $var;

        return $this;
    }

    /**
     * Method is the HTTP method to use (e.g. `POST`, `GET`). Overrides
     * the integration's default method when set.
     *
     * Generated from protobuf field <code>string method = 2 [json_name = "method"];</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Method is the HTTP method to use (e.g. `POST`, `GET`). Overrides
     * the integration's default method when set.
     *
     * Generated from protobuf field <code>string method = 2 [json_name = "method"];</code>
     * @param string $var
     * @return $this
     */
    public function setMethod(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->method = $var;

        return $this;
    }

    /**
     * Path is the upstream request path (URL-decoded, leading slash).
     *
     * Generated from protobuf field <code>string path = 3 [json_name = "path"];</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Path is the upstream request path (URL-decoded, leading slash).
     *
     * Generated from protobuf field <code>string path = 3 [json_name = "path"];</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

}

