"""Public surface contract — static-check assertions.

This file is checked by ``mypy --strict`` as part of ``hatch run lint``
(it lives under ``src/**``, included by the default mypy source-root
config). It exists purely as a guard: each typed alias / annotated
assignment asserts that a specific public symbol exists with the
locked signature. Mypy fails the moment a guarded export is renamed,
removed, or has its signature drifted.

This complements two pre-existing layers of drift detection:

1. ``packages/python/PUBLIC_API.txt`` — snapshot of every public
   symbol. Captures ANY shape change; regenerated by
   ``scripts/sdk-public-api.sh regenerate`` and diff-gated by CI
   (``.github/workflows/sdk-public-api.yml``). The primary surface guard.

2. ``packages/python/tests/test_locked_surface.py`` (where present) —
   runtime ``hasattr`` / ``isinstance`` checks documenting WHY each
   symbol is locked.

This file's contribution is the strongest tier: assertions that mypy
itself fails on at lint time, identical in spirit to the TypeScript
SDK's ``packages/ts/src/__contract__.ts`` (PR #366). The motivation is
the closed-PR #359 class of bug where a facade method snuck in under a
SUFFIXED name (e.g. ``share_v3`` instead of ``share``). The snapshot
caught the new line, but a diff that only ADDS exports is easy to wave
through; a mypy-enforced positive assertion on the canonical name
makes that mistake fail at lint time.

Maintenance: add a name here only after the locked-spec calls for it.
``# type: ignore[attr-defined]`` markers on future symbols flip from
"directive consumes an error" (green) to "Unused 'type: ignore'
comment" (red) the moment the symbol is implemented — forcing whoever
lands the implementation to remove the marker and replace it with a
real ``assert_type`` so the shipped signature is locked from that
point forward.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping
from typing import Any

import sah_sdk as sdk
from sah_sdk.zyins.cases.storage import CaseRecord, PutResult
from sah_sdk.zyins.reference_v3 import Concept, Sort

# =========================================================================
# Tier 1 — symbols that exist today and MUST remain.
# =========================================================================

# ---------------------------------------------------------------------------
# Top-level constructor + namespace factories.
#
# A rename, signature drift, or removal of any of these fails mypy
# strict immediately. The factories are the entry points every
# integrator uses on the first ``import sah_sdk``; the locked spec §2.7
# names them explicitly.
# ---------------------------------------------------------------------------

# ``Isa`` is the unified constructor class.
_Isa: type[sdk.Isa] = sdk.Isa

# The four named factories: ``with_bearer`` / ``with_keycode`` /
# ``for_form`` / ``authenticate``. Each annotated as a callable
# returning ``Isa`` — mypy errors on rename or return-type drift.
_with_bearer: Callable[..., sdk.Isa] = sdk.Isa.with_bearer
_with_keycode: Callable[..., sdk.Isa] = sdk.Isa.with_keycode
_for_form: Callable[..., sdk.Isa] = sdk.Isa.for_form
_authenticate: Callable[..., sdk.Isa] = sdk.Isa.authenticate

# ---------------------------------------------------------------------------
# Per-surface API-version map.
#
# Per locked-spec §2.7: ``BUNDLED_API_VERSIONS`` is the per-surface
# ``Mapping[str, str]`` of bundled pins. The shape is fixed even if the
# set of keys grows.
# ---------------------------------------------------------------------------

_BundledApiVersions: Mapping[str, str] = sdk.BUNDLED_API_VERSIONS

# ---------------------------------------------------------------------------
# CaseStorage adapter contract.
#
# Per locked-spec ``docs/sdk-syntax-proposal.md`` §cases: every
# implementation pluggable into ``Isa(..., case_storage=...)`` MUST
# implement the ``CaseStorage`` Protocol with ``put`` / ``get`` /
# optional ``delete`` and round-trip ``CaseRecord`` <-> ``PutResult``.
# ---------------------------------------------------------------------------

# ``CaseStorage`` is a Protocol; assignment-as-type would trigger
# ``[type-abstract]``. The module-path import below locks the canonical
# location instead — a rename / removal fails import resolution.
from sah_sdk.zyins.cases.storage import CaseStorage as _CaseStorage  # noqa: E402,F401

_CaseRecord: type[CaseRecord] = CaseRecord
_PutResult: type[PutResult] = PutResult

# Default adapter exists (zero-knowledge envelope) and is constructible.
# Importing the symbol locks the canonical module path.
from sah_sdk.zyins.cases.zero_knowledge import (  # noqa: E402
    ZeroKnowledgeCaseStorage as _ZeroKnowledgeCaseStorage,
)

_zk: type[_ZeroKnowledgeCaseStorage] = _ZeroKnowledgeCaseStorage

# ---------------------------------------------------------------------------
# Reference matcher surface — locked top-level shortcuts.
#
# Per locked-spec ``docs/sdk-syntax-proposal.md`` §reference:
#   * ``isa.zyins.medications.match(text) -> Concept``
#   * ``isa.zyins.conditions.match(text) -> Concept``
#   * ``isa.zyins.concepts.match(text) -> Concept``
#
# All three resolve through bundle-bound matchers exposing ``.match``.
# The ``Sort`` enum members (``MOST_COMMON_FIRST`` / ``ALPHABETICAL``)
# are the documented sort vocabulary on ``Concept.medications`` /
# ``.conditions``.
# ---------------------------------------------------------------------------

_Sort: type[Sort] = Sort

# Sort members — renames break consumer code that pins to the enum.
_sort_most_common_first: Sort = Sort.MOST_COMMON_FIRST
_sort_alphabetical: Sort = Sort.ALPHABETICAL

# Concept handle is the matcher return type; locked shape.
_Concept: type[Concept] = Concept

# ---------------------------------------------------------------------------
# Error hierarchy — root + every documented subclass.
#
# Per locked-spec §errors: integrators MUST be able to catch on the
# canonical names. Renames break ``except`` clauses in user code.
# ---------------------------------------------------------------------------

_ISAError: type[sdk.ISAError] = sdk.ISAError
_IsaApiError: type[sdk.IsaApiError] = sdk.IsaApiError
_IsaConfigError: type[sdk.IsaConfigError] = sdk.IsaConfigError
_IsaIdempotencyConflictError: type[sdk.IsaIdempotencyConflictError] = (
    sdk.IsaIdempotencyConflictError
)
_IsaPermissionError: type[sdk.IsaPermissionError] = sdk.IsaPermissionError
_IsaTransportError: type[sdk.IsaTransportError] = sdk.IsaTransportError
_AuthError: type[sdk.AuthError] = sdk.AuthError
_LicenseError: type[sdk.LicenseError] = sdk.LicenseError
_PrequalifyError: type[sdk.PrequalifyError] = sdk.PrequalifyError
_RateLimitError: type[sdk.RateLimitError] = sdk.RateLimitError
_ValidationError: type[sdk.ValidationError] = sdk.ValidationError

# ---------------------------------------------------------------------------
# Value types — primitives that consumers construct directly.
# ---------------------------------------------------------------------------

_Height: type[sdk.Height] = sdk.Height
_Weight: type[sdk.Weight] = sdk.Weight
_Sex: type[sdk.Sex] = sdk.Sex
_Coverage: type[sdk.Coverage] = sdk.Coverage
_Money: type[sdk.Money] = sdk.Money
_Email: type[sdk.Email] = sdk.Email
_Url: type[sdk.Url] = sdk.Url

# ---------------------------------------------------------------------------
# Envelope + raw-response shape.
#
# Per locked-spec §envelope: every successful response carries
# ``request_id`` / ``idempotency_key`` / ``livemode`` / ``object`` /
# ``data``.
# ---------------------------------------------------------------------------

_Envelope: type[sdk.Envelope[Any]] = sdk.Envelope
_RawResponse: type[sdk.RawResponse] = sdk.RawResponse


# =========================================================================
# Tier 2 — locked-spec names not yet implemented.
# =========================================================================
#
# Each guarded reference below documents a name the locked spec calls
# for but the SDK has not yet shipped. Today the ``# type: ignore``
# marker is green (the symbol is missing, mypy errors on the reference,
# the directive consumes the error). The instant the symbol lands in
# ``sah_sdk/__init__.py``, the directive's expected error disappears
# and mypy flips to red with "Unused 'type: ignore' comment." That's
# the signal to:
#
#   1. Delete the ``# type: ignore`` line.
#   2. Replace it with a real ``assert_type`` (matching Tier 1 style)
#      so the shipped signature is locked from that point forward.
#
# This guards the forward-looking #359 bug class: a future PR cannot
# land an implementation under a suffixed name (e.g. ``save_v2``)
# without the contract review catching the missing canonical.

# Future markers use ``getattr(..., "<name>", None)`` so that mypy
# does NOT flag them as missing today — instead, when the canonical
# typed accessor lands on ``CasesFacade``, the contract reviewer is
# expected to replace the ``getattr`` probe with a real typed
# assignment (e.g. ``_share: Callable[..., Any] = CasesFacade.share``).
# The named placeholder lines below are the ledger of locked-spec
# names that have not yet shipped.

from sah_sdk.zyins.cases import CasesFacade as _CasesFacade  # noqa: E402

# ``isa.zyins.cases.share`` — locked-spec §3 Flow 5. Forwarded today
# through ``CasesFacade.__getattr__`` to the legacy sub-client.
_share_placeholder: Any = getattr(_CasesFacade, "share", None)

# ``isa.zyins.cases.delete`` — locked-spec §3 Flow 5. Future
# ``DeleteableCaseStorage`` protocol extension.
_delete_placeholder: Any = getattr(_CasesFacade, "delete", None)

# ---------------------------------------------------------------------------
# Reference-adapter surface — v3-datasets + adapter cutover spec §2.
#
# Three Protocols + three default implementations + a Suggestion shape.
# Renames/removals/signature drift on any of these fail mypy strict.
# ---------------------------------------------------------------------------

from sah_sdk.zyins.reference.autocomplete_algorithm import (  # noqa: E402
    AutocompleteAlgorithm as _AutocompleteAlgorithm,
)
from sah_sdk.zyins.reference.autocomplete_algorithm import (  # noqa: E402
    AutocompleteOptions as _AutocompleteOptions,
)
from sah_sdk.zyins.reference.autocomplete_algorithm import (  # noqa: E402
    DefaultAutocompleteAlgorithm as _DefaultAutocompleteAlgorithm,
)
from sah_sdk.zyins.reference.autocorrector import (  # noqa: E402
    Autocorrector as _Autocorrector,
)
from sah_sdk.zyins.reference.autocorrector import (  # noqa: E402
    DefaultAutocorrector as _DefaultAutocorrector,
)
from sah_sdk.zyins.reference.match_algorithm import (  # noqa: E402
    DefaultMatchAlgorithm as _DefaultMatchAlgorithm,
)
from sah_sdk.zyins.reference.match_algorithm import (  # noqa: E402
    MatchAlgorithm as _MatchAlgorithm,
)
from sah_sdk.zyins.reference.suggestion import Suggestion as _Suggestion  # noqa: E402

# Protocols are abstract — import-binds the canonical module path.
_autocorrector_protocol_module: Any = _Autocorrector
_match_algorithm_protocol_module: Any = _MatchAlgorithm
_autocomplete_algorithm_protocol_module: Any = _AutocompleteAlgorithm

# Default impls are concrete — assignment locks their constructibility.
_default_autocorrector: type[_DefaultAutocorrector] = _DefaultAutocorrector
_default_match_algorithm: type[_DefaultMatchAlgorithm] = _DefaultMatchAlgorithm
_default_autocomplete_algorithm: type[_DefaultAutocompleteAlgorithm] = (
    _DefaultAutocompleteAlgorithm
)

# Value-shape types — frozen dataclasses; assignment locks the shape.
_autocomplete_options: type[_AutocompleteOptions] = _AutocompleteOptions
_suggestion: type[_Suggestion] = _Suggestion
