<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/rapidsign/v1/documents.proto

namespace Sah\RapidSign\Api\V1;

use UnexpectedValueException;

/**
 * DocumentStatus tracks the lifecycle state of a document.
 *
 * Protobuf type <code>api.rapidsign.v1.DocumentStatus</code>
 */
class DocumentStatus
{
    /**
     * Default zero value. Never emitted by the server.
     *
     * Generated from protobuf enum <code>DOCUMENT_STATUS_UNSPECIFIED = 0;</code>
     */
    const DOCUMENT_STATUS_UNSPECIFIED = 0;
    /**
     * Packet rendered and stored; awaiting signature(s).
     *
     * Generated from protobuf enum <code>DOCUMENT_STATUS_PENDING = 1;</code>
     */
    const DOCUMENT_STATUS_PENDING = 1;
    /**
     * At least one signature captured.
     *
     * Generated from protobuf enum <code>DOCUMENT_STATUS_SAVED = 2;</code>
     */
    const DOCUMENT_STATUS_SAVED = 2;
    /**
     * Signer-notification email accepted by the emailer.
     *
     * Generated from protobuf enum <code>DOCUMENT_STATUS_NOTIFIED = 3;</code>
     */
    const DOCUMENT_STATUS_NOTIFIED = 3;

    private static $valueToName = [
        self::DOCUMENT_STATUS_UNSPECIFIED => 'DOCUMENT_STATUS_UNSPECIFIED',
        self::DOCUMENT_STATUS_PENDING => 'DOCUMENT_STATUS_PENDING',
        self::DOCUMENT_STATUS_SAVED => 'DOCUMENT_STATUS_SAVED',
        self::DOCUMENT_STATUS_NOTIFIED => 'DOCUMENT_STATUS_NOTIFIED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

