<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/rapidsign/v1/documents.proto

namespace Sah\RapidSign\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * PdfRenderSource references one PDF input the renderer must fetch,
 * optionally pinned to an expected SHA-256 hash for integrity. URLs are
 * fetched server-side; the caller never proxies binary content.
 *
 * Generated from protobuf message <code>api.rapidsign.v1.PdfRenderSource</code>
 */
class PdfRenderSource extends \Google\Protobuf\Internal\Message
{
    /**
     * Fully-qualified URL to fetch the source PDF from. Required.
     *
     * Generated from protobuf field <code>string url = 1 [json_name = "url"];</code>
     */
    protected $url = '';
    /**
     * Optional hex-encoded SHA-256 of the expected source bytes. When
     * present the renderer aborts with a validation error if the fetch
     * does not match.
     *
     * Generated from protobuf field <code>string expected_hash = 2 [json_name = "expectedHash"];</code>
     */
    protected $expected_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $url
     *           Fully-qualified URL to fetch the source PDF from. Required.
     *     @type string $expected_hash
     *           Optional hex-encoded SHA-256 of the expected source bytes. When
     *           present the renderer aborts with a validation error if the fetch
     *           does not match.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\RapidSign\Api\V1\Meta\Documents::initOnce();
        parent::__construct($data);
    }

    /**
     * Fully-qualified URL to fetch the source PDF from. Required.
     *
     * Generated from protobuf field <code>string url = 1 [json_name = "url"];</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Fully-qualified URL to fetch the source PDF from. Required.
     *
     * Generated from protobuf field <code>string url = 1 [json_name = "url"];</code>
     * @param string $var
     * @return $this
     */
    public function setUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->url = $var;

        return $this;
    }

    /**
     * Optional hex-encoded SHA-256 of the expected source bytes. When
     * present the renderer aborts with a validation error if the fetch
     * does not match.
     *
     * Generated from protobuf field <code>string expected_hash = 2 [json_name = "expectedHash"];</code>
     * @return string
     */
    public function getExpectedHash()
    {
        return $this->expected_hash;
    }

    /**
     * Optional hex-encoded SHA-256 of the expected source bytes. When
     * present the renderer aborts with a validation error if the fetch
     * does not match.
     *
     * Generated from protobuf field <code>string expected_hash = 2 [json_name = "expectedHash"];</code>
     * @param string $var
     * @return $this
     */
    public function setExpectedHash(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->expected_hash = $var;

        return $this;
    }

}

