<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/rapidsign/v1/documents.proto

namespace Sah\RapidSign\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * SignDocumentResponse is the success body for POST /v1/documents/{sign_id}/sign.
 *
 * Generated from protobuf message <code>api.rapidsign.v1.SignDocumentResponse</code>
 */
class SignDocumentResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The sign id that was signed. Echoed from the path.
     *
     * Generated from protobuf field <code>string sign_id = 1 [json_name = "signId"];</code>
     */
    protected $sign_id = '';
    /**
     * Lifecycle state after the signature was saved. Always `saved`
     * on a 2xx response.
     *
     * Generated from protobuf field <code>.api.rapidsign.v1.DocumentStatus status = 2 [json_name = "status"];</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sign_id
     *           The sign id that was signed. Echoed from the path.
     *     @type int $status
     *           Lifecycle state after the signature was saved. Always `saved`
     *           on a 2xx response.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\RapidSign\Api\V1\Meta\Documents::initOnce();
        parent::__construct($data);
    }

    /**
     * The sign id that was signed. Echoed from the path.
     *
     * Generated from protobuf field <code>string sign_id = 1 [json_name = "signId"];</code>
     * @return string
     */
    public function getSignId()
    {
        return $this->sign_id;
    }

    /**
     * The sign id that was signed. Echoed from the path.
     *
     * Generated from protobuf field <code>string sign_id = 1 [json_name = "signId"];</code>
     * @param string $var
     * @return $this
     */
    public function setSignId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->sign_id = $var;

        return $this;
    }

    /**
     * Lifecycle state after the signature was saved. Always `saved`
     * on a 2xx response.
     *
     * Generated from protobuf field <code>.api.rapidsign.v1.DocumentStatus status = 2 [json_name = "status"];</code>
     * @return int one of the values in {@see \Sah\RapidSign\Api\V1\DocumentStatus}
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Lifecycle state after the signature was saved. Always `saved`
     * on a 2xx response.
     *
     * Generated from protobuf field <code>.api.rapidsign.v1.DocumentStatus status = 2 [json_name = "status"];</code>
     * @param int $var one of the values in {@see \Sah\RapidSign\Api\V1\DocumentStatus}
     * @return $this
     */
    public function setStatus(int $var)
    {
        GPBUtil::checkEnum($var, \Sah\RapidSign\Api\V1\DocumentStatus::class);
        $this->status = $var;

        return $this;
    }

}

