<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/rapidsign/v1/documents.proto

namespace Sah\RapidSign\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * SignDocumentRequest is the body for POST /v1/documents/{sign_id}/sign.
 *
 * Generated from protobuf message <code>api.rapidsign.v1.SignDocumentRequest</code>
 */
class SignDocumentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Sign id path parameter. Required.
     *
     * Generated from protobuf field <code>string sign_id = 1 [json_name = "signId"];</code>
     */
    protected $sign_id = '';
    /**
     * Originating session identifier; must match the session_id used
     * when the document was created.
     *
     * Generated from protobuf field <code>string session_id = 2 [json_name = "sessionId"];</code>
     */
    protected $session_id = '';
    /**
     * Optional signing secret (one-time code) when the document was
     * created with a secret-protected sign_id.
     *
     * Generated from protobuf field <code>string secret = 3 [json_name = "secret"];</code>
     */
    protected $secret = '';
    /**
     * Base64-encoded signature image bytes. Required.
     *
     * Generated from protobuf field <code>string signature = 4 [json_name = "signature"];</code>
     */
    protected $signature = '';
    /**
     * Opaque signer metadata (browser fingerprint, ip, etc.) captured at
     * signing time, stored verbatim for the audit trail.
     *
     * Generated from protobuf field <code>string user_metadata = 5 [json_name = "userMetadata"];</code>
     */
    protected $user_metadata = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sign_id
     *           Sign id path parameter. Required.
     *     @type string $session_id
     *           Originating session identifier; must match the session_id used
     *           when the document was created.
     *     @type string $secret
     *           Optional signing secret (one-time code) when the document was
     *           created with a secret-protected sign_id.
     *     @type string $signature
     *           Base64-encoded signature image bytes. Required.
     *     @type string $user_metadata
     *           Opaque signer metadata (browser fingerprint, ip, etc.) captured at
     *           signing time, stored verbatim for the audit trail.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\RapidSign\Api\V1\Meta\Documents::initOnce();
        parent::__construct($data);
    }

    /**
     * Sign id path parameter. Required.
     *
     * Generated from protobuf field <code>string sign_id = 1 [json_name = "signId"];</code>
     * @return string
     */
    public function getSignId()
    {
        return $this->sign_id;
    }

    /**
     * Sign id path parameter. Required.
     *
     * Generated from protobuf field <code>string sign_id = 1 [json_name = "signId"];</code>
     * @param string $var
     * @return $this
     */
    public function setSignId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->sign_id = $var;

        return $this;
    }

    /**
     * Originating session identifier; must match the session_id used
     * when the document was created.
     *
     * Generated from protobuf field <code>string session_id = 2 [json_name = "sessionId"];</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * Originating session identifier; must match the session_id used
     * when the document was created.
     *
     * Generated from protobuf field <code>string session_id = 2 [json_name = "sessionId"];</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Optional signing secret (one-time code) when the document was
     * created with a secret-protected sign_id.
     *
     * Generated from protobuf field <code>string secret = 3 [json_name = "secret"];</code>
     * @return string
     */
    public function getSecret()
    {
        return $this->secret;
    }

    /**
     * Optional signing secret (one-time code) when the document was
     * created with a secret-protected sign_id.
     *
     * Generated from protobuf field <code>string secret = 3 [json_name = "secret"];</code>
     * @param string $var
     * @return $this
     */
    public function setSecret(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->secret = $var;

        return $this;
    }

    /**
     * Base64-encoded signature image bytes. Required.
     *
     * Generated from protobuf field <code>string signature = 4 [json_name = "signature"];</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Base64-encoded signature image bytes. Required.
     *
     * Generated from protobuf field <code>string signature = 4 [json_name = "signature"];</code>
     * @param string $var
     * @return $this
     */
    public function setSignature(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->signature = $var;

        return $this;
    }

    /**
     * Opaque signer metadata (browser fingerprint, ip, etc.) captured at
     * signing time, stored verbatim for the audit trail.
     *
     * Generated from protobuf field <code>string user_metadata = 5 [json_name = "userMetadata"];</code>
     * @return string
     */
    public function getUserMetadata()
    {
        return $this->user_metadata;
    }

    /**
     * Opaque signer metadata (browser fingerprint, ip, etc.) captured at
     * signing time, stored verbatim for the audit trail.
     *
     * Generated from protobuf field <code>string user_metadata = 5 [json_name = "userMetadata"];</code>
     * @param string $var
     * @return $this
     */
    public function setUserMetadata(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->user_metadata = $var;

        return $this;
    }

}

