<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/zyins/v1/licenses.proto

namespace Sah\ZyINS\Api\V1\PublicActivateResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Auth is the activation response's authentication block. The
 * embedded `headers` map is the ready-to-use header set for the
 * legacy License base64 scheme; consumers that migrate to
 * LicenseHMAC (ADR-018) ignore it and compute their own signatures.
 *
 * Generated from protobuf message <code>api.zyins.v1.PublicActivateResponse.Auth</code>
 */
class Auth extends \Google\Protobuf\Internal\Message
{
    /**
     * Always `License` for v1 activations. Future LicenseHMAC
     * activations will return `LicenseHMAC`.
     *
     * Generated from protobuf field <code>string scheme = 1 [json_name = "scheme"];</code>
     */
    protected $scheme = '';
    /**
     * The license key returned to the client.
     *
     * Generated from protobuf field <code>string license_key = 2 [json_name = "licenseKey"];</code>
     */
    protected $license_key = '';
    /**
     * BPP keycode (XXX-XXX-XXX).
     *
     * Generated from protobuf field <code>string keycode = 3 [json_name = "keycode"];</code>
     */
    protected $keycode = '';
    /**
     * Email associated with the license.
     *
     * Generated from protobuf field <code>string email = 4 [json_name = "email"];</code>
     */
    protected $email = '';
    /**
     * Device fingerprint registered during activation.
     *
     * Generated from protobuf field <code>string device_id = 5 [json_name = "deviceId"];</code>
     */
    protected $device_id = '';
    /**
     * Pre-computed request headers for the legacy scheme.
     *
     * Generated from protobuf field <code>.api.zyins.v1.PublicActivateResponse.Auth.Headers headers = 6 [json_name = "headers"];</code>
     */
    protected $headers = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $scheme
     *           Always `License` for v1 activations. Future LicenseHMAC
     *           activations will return `LicenseHMAC`.
     *     @type string $license_key
     *           The license key returned to the client.
     *     @type string $keycode
     *           BPP keycode (XXX-XXX-XXX).
     *     @type string $email
     *           Email associated with the license.
     *     @type string $device_id
     *           Device fingerprint registered during activation.
     *     @type \Sah\ZyINS\Api\V1\PublicActivateResponse\Auth\Headers $headers
     *           Pre-computed request headers for the legacy scheme.
     * }
     */
    public function __construct($data = NULL) {
        \Sah\ZyINS\Api\V1\Meta\Licenses::initOnce();
        parent::__construct($data);
    }

    /**
     * Always `License` for v1 activations. Future LicenseHMAC
     * activations will return `LicenseHMAC`.
     *
     * Generated from protobuf field <code>string scheme = 1 [json_name = "scheme"];</code>
     * @return string
     */
    public function getScheme()
    {
        return $this->scheme;
    }

    /**
     * Always `License` for v1 activations. Future LicenseHMAC
     * activations will return `LicenseHMAC`.
     *
     * Generated from protobuf field <code>string scheme = 1 [json_name = "scheme"];</code>
     * @param string $var
     * @return $this
     */
    public function setScheme(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->scheme = $var;

        return $this;
    }

    /**
     * The license key returned to the client.
     *
     * Generated from protobuf field <code>string license_key = 2 [json_name = "licenseKey"];</code>
     * @return string
     */
    public function getLicenseKey()
    {
        return $this->license_key;
    }

    /**
     * The license key returned to the client.
     *
     * Generated from protobuf field <code>string license_key = 2 [json_name = "licenseKey"];</code>
     * @param string $var
     * @return $this
     */
    public function setLicenseKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->license_key = $var;

        return $this;
    }

    /**
     * BPP keycode (XXX-XXX-XXX).
     *
     * Generated from protobuf field <code>string keycode = 3 [json_name = "keycode"];</code>
     * @return string
     */
    public function getKeycode()
    {
        return $this->keycode;
    }

    /**
     * BPP keycode (XXX-XXX-XXX).
     *
     * Generated from protobuf field <code>string keycode = 3 [json_name = "keycode"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeycode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->keycode = $var;

        return $this;
    }

    /**
     * Email associated with the license.
     *
     * Generated from protobuf field <code>string email = 4 [json_name = "email"];</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Email associated with the license.
     *
     * Generated from protobuf field <code>string email = 4 [json_name = "email"];</code>
     * @param string $var
     * @return $this
     */
    public function setEmail(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->email = $var;

        return $this;
    }

    /**
     * Device fingerprint registered during activation.
     *
     * Generated from protobuf field <code>string device_id = 5 [json_name = "deviceId"];</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Device fingerprint registered during activation.
     *
     * Generated from protobuf field <code>string device_id = 5 [json_name = "deviceId"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Pre-computed request headers for the legacy scheme.
     *
     * Generated from protobuf field <code>.api.zyins.v1.PublicActivateResponse.Auth.Headers headers = 6 [json_name = "headers"];</code>
     * @return \Sah\ZyINS\Api\V1\PublicActivateResponse\Auth\Headers|null
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    public function hasHeaders()
    {
        return isset($this->headers);
    }

    public function clearHeaders()
    {
        unset($this->headers);
    }

    /**
     * Pre-computed request headers for the legacy scheme.
     *
     * Generated from protobuf field <code>.api.zyins.v1.PublicActivateResponse.Auth.Headers headers = 6 [json_name = "headers"];</code>
     * @param \Sah\ZyINS\Api\V1\PublicActivateResponse\Auth\Headers $var
     * @return $this
     */
    public function setHeaders(\Sah\ZyINS\Api\V1\PublicActivateResponse\Auth\Headers|null $var)
    {
        $this->headers = $var;

        return $this;
    }

}

